<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
	<div id="content" class="render-grid">
	    <h1 class="content-heading bg-white border-bottom">Fluid Grid System <span>12 Column</span></h1>
	    <div class="innerAll spacing-x2">
	        <!-- 2 Column / Half -->
	        <div class="widget widget-inverse">

	            <!-- Widget heading -->
	            <div class="widget-head">
	                <h4 class="heading">2 Column / Half</h4>
	            </div>
	            <!-- // Widget heading END -->

	            <div class="widget-body">

	                <!-- 2 Column Grid / Half -->
	                <div class="row">

	                    <!-- Half Column -->
	                    <div class="col-12 col-md-6">
	                        <h4>Column</h4>
	                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
	                    </div>
	                    <!-- // Half Column END -->

	                    <!-- Half Column -->
	                    <div class="col-12 col-md-6">
	                        <h4>Column</h4>
	                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
	                    </div>
	                    <!-- // Half Column END -->

	                </div>
	                <!-- // 2 Column Grid / Half END -->

	            </div>
	        </div>
	        <!-- // 2 Column / Half END -->

	        <!-- 3 Column / One Third -->
	        <div class="widget widget-inverse">

	            <!-- Widget heading -->
	            <div class="widget-head">
	                <h4 class="heading">3 Column / One Third</h4>
	            </div>
	            <!-- // Widget heading END -->

	            <div class="widget-body">

	                <!-- 3 Column Grid / One Third -->
	                <div class="row">

	                    <!-- One Third Column -->
	                    <div class="col-md-4">
	                        <h4>Column</h4>
	                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
	                    </div>
	                    <!-- // One Third Column END -->

	                    <!-- One Third Column -->
	                    <div class="col-md-4">
	                        <h4>Column</h4>
	                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
	                    </div>
	                    <!-- // One Third Column END -->

	                    <!-- One Third Column -->
	                    <div class="col-md-4">
	                        <h4>Column</h4>
	                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
	                    </div>
	                    <!-- // One Third Column END -->

	                </div>
	                <!-- // 3 Column Grid / One Third END -->

	            </div>
	        </div>
	        <!-- // 3 Column / One Third END -->

	        <!-- 2 Column / One Third & Two Third -->
	        <div class="widget widget-inverse">

	            <!-- Widget heading -->
	            <div class="widget-head">
	                <h4 class="heading">2 Column / One Third &amp; Two Third</h4>
	            </div>
	            <!-- // Widget heading END -->
	            <div class="widget-body">

	                <!-- 2 Column Grid / One Third & Two Third -->
	                <div class="row">

	                    <!-- One Third Column -->
	                    <div class="col-md-4">
	                        <h4>Column</h4>
	                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
	                    </div>
	                    <!-- // One Third Column END -->

	                    <!-- Two Third Column -->
	                    <div class="col-md-8">
	                        <h4>Column</h4>
	                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
	                    </div>
	                    <!-- // Two Third Column END -->

	                </div>
	                <!-- // 2 Column Grid / One Third & Two Third END -->

	            </div>
	        </div>
	        <!-- // 2 Column / One Third & Two Third END -->

	        <!-- 4 Column / One Fourth -->
	        <div class="widget widget-inverse">

	            <!-- Widget heading -->
	            <div class="widget-head">
	                <h4 class="heading">4 Column / One Fourth</h4>
	            </div>
	            <!-- // Widget heading END -->

	            <div class="widget-body">

	                <!-- 4 Column Grid / One Fourth -->
	                <div class="row">

	                    <!-- One Fourth Column -->
	                    <div class="col-md-3">
	                        <h4>Column</h4>
	                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
	                    </div>
	                    <!-- // One Fourth Column END -->

	                    <!-- One Fourth Column -->
	                    <div class="col-md-3">
	                        <h4>Column</h4>
	                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
	                    </div>
	                    <!-- // One Fourth Column END -->

	                    <!-- One Fourth Column -->
	                    <div class="col-md-3">
	                        <h4>Column</h4>
	                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
	                    </div>
	                    <!-- // One Fourth Column END -->

	                    <!-- One Fourth Column -->
	                    <div class="col-md-3">
	                        <h4>Column</h4>
	                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
	                    </div>
	                    <!-- // One Fourth Column END -->

	                </div>
	                <!-- // 4 Column Grid / One Fourth END -->

	            </div>
	        </div>
	        <!-- // 4 Column / One Fourth END -->

	        <!-- 2 Column / One Fourth & Three Fourth -->
	        <div class="widget widget-inverse">

	            <!-- Widget heading -->
	            <div class="widget-head">
	                <h4 class="heading">2 Column / One Fourth &amp; Three Fourth</h4>
	            </div>
	            <!-- // Widget heading END -->

	            <div class="widget-body">

	                <!-- 2 Column Grid / One Fourth & Three Fourth -->
	                <div class="row">

	                    <!-- One Fourth Column -->
	                    <div class="col-md-3">
	                        <h4>Column</h4>
	                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
	                    </div>
	                    <!-- // One Fourth Column END -->

	                    <!-- Three Fourth Column -->
	                    <div class="col-md-9">
	                        <h4>Column</h4>
	                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
	                    </div>
	                    <!-- // Three Fourth Column END -->

	                </div>
	                <!-- // 2 Column Grid / One Fourth & Three Fourth -->

	            </div>
	        </div>
	        <!-- // 2 Column / One Fourth & Three Fourth END -->

	    </div>


	</div>
	<!-- // Content END -->


    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->