<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    <div id="content" class="render-file-manager">
        <h1 class="content-heading bg-white border-bottom">File Managers</h1>
        <div class="innerAll spacing-x2">

            <!-- Widget -->
            <div class="widget widget-inverse">

                <!-- Widget heading -->
                <div class="widget-head">
                    <h4 class="heading glyphicons file_import"><i></i>Dropzone File Upload</h4>
                </div>
                <!-- // Widget heading END -->

                <div class="widget-body">
                    <!-- Dropzone -->
                    <div id="dropzone">
                        <form action="/MelisDesign/upload.php" class="dropzone" id="demo-upload">
                            <div class="fallback">
                                <input name="file" type="file" multiple />
                            </div>
                        </form>
                    </div>

                    <div class="separator top d-flex flex-row justify-content-between">
                        <!-- <button type="button" class="btn btn-primary btn-remove-all-files">Remove all files</button> -->
                        <small>* Maximum filesize per file is 20MB</small>
                    </div>
                    <!-- // Dropzone END -->

                </div>
            </div>
            <!-- // Widget END -->
            
            <!-- Widget -->
            <div class="widget widget-inverse">

                <!-- Widget heading -->
                <div class="widget-head">
                    <h4 class="heading glyphicons file_import"><i></i>Plupload File Upload</h4>
                </div>
                <!-- // Widget heading END -->

                <div class="widget-body">
                    <!-- Plupload -->
                    <form id="pluploadForm">
                        <div id="pluploadUploader">
                            <p>You browser doesn't have Flash, Silverlight, Gears, BrowserPlus or HTML5 support.</p>
                        </div>
                    </form>
                    <!-- // Plupload END -->


                </div>
            </div>
            <!-- // Widget END -->
        </div>


    </div>
    <!-- // Content END -->

    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->

<!-- <div id="remove-all-modal" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Dropzone</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to remove the file?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="remove-all" type="button" class="btn btn-danger">Remove</button>
            </div>
        </div>
    </div>
</div> -->