<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;
        
?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    <div id="content" class="render-dashboard">
        <h1 class="bg-white content-heading border-bottom">Dashboard</h1>
        <div class="bg-white innerAll border-bottom">
            <ul class="menubar">
                <li class="active"><a href="index.html?lang=en">Dashboard</a></li>
                <li><a href="#"><span class="badge badge-primary float-right">30</span> Button</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Dropdown Link #1</a></li>
                        <li><a href="#">Dropdown Link #2</a></li>
                        <li><a href="#">Dropdown Link #3</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    
        <div class="innerAll spacing-x2">

            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="panel-3d">
                        <div class="front">

                            <div class="widget text-center">
                                <div class="widget-body padding-none">
                                    <div>
                                        <div class="innerAll bg-inverse">
                                            <p class="lead text-white strong margin-none"><i class="icon-graph-up-1"></i><br/>47,340</p>
                                        </div>
                                        <div class="innerAll">
                                            <button class="btn btn-inverse">View Statistics</button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="back">

                            <div class="widget widget-inverse widget-scroll" data-scroll-height="165px">
                                <div class="widget-head">
                                    <button class="btn btn-xs btn-default float-right"><i class="fa fa-times"></i></button>
                                    <h4 class="heading">Statistics</h4>
                                </div>
                                <div class="widget-body padding-none">
                                    
                                    <div>
                                        <table class="table table-condensed">
                                            <!-- Table body -->
                                            <tbody>
                                                
                                                                                        <!-- Table row -->
                                                <tr>
                                                    <td class="center">Oct</td>
                                                    <td><strong>27,340</strong></td>
                                                    <td><a href="#">mycompany.biz</a></td>
                                                </tr>
                                                <!-- // Table row END -->
                                                <!-- Table row -->
                                                <tr>
                                                    <td class="center">Oct</td>
                                                    <td><strong>10,340</strong></td>    
                                                    <td><a href="#">themeforest.net</a></td>
                                                </tr>
                                                <!-- // Table row END -->
                                                <!-- Table row -->
                                                <tr>
                                                    <td class="center">Oct</td>
                                                    <td><strong>1,130</strong></td>
                                                    <td><a href="#">mycompany.biz</a></td>
                                                </tr>
                                                <!-- // Table row END -->
                                                <!-- Table row -->
                                                <tr>
                                                    <td class="center">Oct</td>
                                                    <td><strong>130</strong></td>
                                                    <td><a href="#">johndoe.biz</a></td>
                                                </tr>
                                                <!-- // Table row END -->
                                                                                        <!-- Table row -->
                                                <tr>
                                                    <td class="center">Oct</td>
                                                    <td><strong>27,340</strong></td>
                                                    <td><a href="#">mycompany.biz</a></td>
                                                </tr>
                                                <!-- // Table row END -->
                                                <!-- Table row -->
                                                <tr>
                                                    <td class="center">Oct</td>
                                                    <td><strong>10,340</strong></td>    
                                                    <td><a href="#">themeforest.net</a></td>
                                                </tr>
                                                <!-- // Table row END -->
                                                <!-- Table row -->
                                                <tr>
                                                    <td class="center">Oct</td>
                                                    <td><strong>1,130</strong></td>
                                                    <td><a href="#">mycompany.biz</a></td>
                                                </tr>
                                                <!-- // Table row END -->
                                                <!-- Table row -->
                                                <tr>
                                                    <td class="center">Oct</td>
                                                    <td><strong>130</strong></td>
                                                    <td><a href="#">johndoe.biz</a></td>
                                                </tr>
                                                <!-- // Table row END -->
                                                
                                            </tbody>
                                            <!-- // Table body END -->
                                            
                                        </table>
                                        <!-- // Table END -->

                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="panel-3d">
                        <div class="front">

                            <div class="widget text-center">
                                <div class="widget-body padding-none">
                                    <div>
                                        <div class="innerAll bg-default">
                                            <p class="lead strong margin-none"><i class="icon-add-to-cart"></i><br/>7 Orders</p>
                                        </div>
                                        <div class="innerAll">
                                            <button class="btn btn-default">View Orders</button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="back">
                            <div class="widget widget-inverse widget-scroll" data-scroll-height="165px">
                                <div class="widget-head">
                                    <button class="btn btn-xs btn-default float-right"><i class="fa fa-times"></i></button>
                                    <h4 class="heading">Orders</h4>
                                </div>
                                <div class="widget-body padding-none">
                                    <div>
                                        <div class="box-generic border-none text-center">
                                            <p class="margin-none">Orders Total</p>
                                            <p><strong class="text-large text-primary">&#8364;  99,134</strong></p>
                                            <p class="margin-none"><span class="text-success strong">15%</span> <i class="fa fa-fw fa-arrow-up text-success"></i> last 30 days</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="panel-3d">
                        <div class="front">
                            
                            <div class="widget text-center">
                                <div class="widget-body padding-none">
                                    <div>
                                        <div class="innerAll bg-success">
                                            <p class="lead strong margin-none text-white"><i class="icon-note-pad"></i><br/>2 Bookings</p>
                                        </div>
                                        <div class="innerAll">
                                            <button class="btn btn-success">View Bookings</button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="back">
                            <div class="widget widget-inverse widget-scroll" data-scroll-height="165px">
                                <div class="widget-head">
                                    <button class="btn btn-xs btn-default float-right"><i class="fa fa-times"></i></button>
                                    <h4 class="heading">Meetings</h4>
                                </div>
                                <div class="widget-body padding-none">
                                    <div>
                                        <div class="media innerAll half margin-none">
                                            <a class="float-left" href="#">
                                                <img src="/MelisDesign/images/people/50/15.jpg" alt="" class="rounded-circle media-object"> 
                                            </a>
                                            <div class="media-body ">
                                                <a href="" class="strong text-success"> <i class="fa fa-circle"></i> Jane Smith</a> 
                                                <div class="clearfix"></div>
                                                <em>10:20 AM - 21/11/2013</em>
                                            </div>
                                        </div>
                                        <hr class="margin-none"/>

                                        <div class="media innerAll half margin-none">
                                            <a class="float-left" href="#">
                                                <img src="/MelisDesign/images/people/50/19.jpg" alt="" class="rounded-circle media-object"> 
                                            </a>
                                            <div class="media-body ">
                                                <a href="" class="strong text-primary"> <i class="fa fa-circle"></i> Mary Deidre</a> 
                                                <div class="clearfix"></div>
                                                <em>10:20 AM - 21/11/2013</em>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="panel-3d">
                        <div class="front">

                            <div class="widget text-center">
                                <div class="widget-body padding-none">
                                    <div>
                                        <div class="bg-info innerAll">
                                            <p class="lead strong margin-none text-white"><i class="icon-envelope-2"></i><br/>4 Messages</p>
                                        </div>
                                        <div class="innerAll">
                                            <button class="btn btn-info">View Messages</button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="back">

                            <div class="widget widget-inverse widget-scroll" data-scroll-height="165px">
                                <div class="widget-head">
                                    <button class="btn btn-xs btn-default float-right"><i class="fa fa-times"></i></button>
                                    <h4 class="heading">Messages</h4>
                                </div>
                                <div class="widget-body padding-none">
                                    
                                    <div>
                                        <div class="media innerAll">
                                            <i class="fa fa-chat fa-2x float-left disabled"></i>
                                            <div class="media-body">
                                                <div class="float-right label label-default">2 days</div>
                                                <a href="" class="text-info">John Doe</a> <em>wrote: </em>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>
                                                <a href="" class="btn btn-info btn-xs">read message</a>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-9">

                    <div class="widget">
                        <div class="widget-body padding-none">

                            <div class="row row-merge">
                                <div class="col-sm-4">

                                    <div class="text-center innerAll border-bottom">
                                        <div class="separator bottom"></div>
                                        <div data-percent="85" data-size="140" class="easy-pie inline-block primary" data-scale-color="false" data-track-color="#ffffff" data-line-width="5">
                                            <div class="value text-center">
                                                <span class="strong"><i class="icon-graph-up-1 fa-4x text-primary"></i></span>
                                            </div>
                                        </div>
                                        <div class="separator bottom"></div>
                                        <p class="lead"><span class="text-large text-regular">8,320</span> <span class="text-primary">Visits</span></p>
                                    </div>
                                    <div class="text-center innerAll">
                                        <div class="separator bottom"></div>
                                        <div data-percent="85" data-size="140" class="easy-pie inline-block success" data-scale-color="false" data-track-color="#ffffff" data-line-width="5">
                                            <div class="value text-center">
                                                <span class="strong"><i class="icon-cash-bag fa-5x text-success"></i></span>
                                            </div>
                                        </div>
                                        <div class="separator bottom"></div>
                                        <p class="lead"><span class="text-large text-regular">&#8364; 3,470</span> <span class="text-success">Income</span></p>
                                    </div>

                                </div>
                                <div class="col-sm-8 bg-white">

                                    <div class="widget-head bg-gray">
                                        <div class="btn-group float-right btn-group-xs">
                                            <a href="#chart-simple-lines-001" class="btn btn-default active" data-toggle="tab"><i class="fa fa-bars"></i></a>
                                            <a href="#chart-simple-bars-001" class="btn btn-default" data-toggle="tab"><i class="fa fa-bar-chart-o"></i></a>
                                        </div>
                                        <h3 class="heading text-regular"><i class="icon-stocks-up"></i> Statistics</h3>
                                    </div>
                                    
                                    <div class="innerAll">
                                        <div class="tab-content ">
                                            <div class="tab-pane active" id="chart-simple-lines-001">
                                                <!-- Simple Chart -->
                                                <div id="chart_simple_001" class="flotchart-holder"></div>
                                            </div>
                                            <div class="tab-pane" id="chart-simple-bars-001">
                                                <!-- Simple Chart -->
                                                <div id="chart_simple_bars_001" class="flotchart-holder"></div>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Table -->
                                    <div class="overflow-x ">
                                        <table class="table table-condensed border-top margin-none">
                                        
                                            <!-- Table heading -->
                                            <thead class="bg-gray">
                                                <tr>
                                                    <th class="center">No.</th>
                                                    <th>Name</th>
                                                    <th>Location</th>
                                                    <th>Position</th>
                                                    <th class="center">Rating</th>
                                                </tr>
                                            </thead>
                                            <!-- // Table heading END -->
                                            
                                            <!-- Table body -->
                                            <tbody>
                                                

                                                <!-- Table row -->
                                                <tr>
                                                    <td class="center">1</td>
                                                    <td> <img src="/MelisDesign/images/people/35/8.jpg" width="20" class="rounded-circle"> <span >John Doe</span></td>
                                                    <td>MI, USA </td>
                                                    <td>Senior UI Designer</td>
                                                    <td class="center">
                                                        <div class="rating text-faded">
                                                            <span class="star"></span>
                                                            <span class="star"></span>
                                                            <span class="star"></span>
                                                            <span class="star active"></span>
                                                            <span class="star"></span>
                                                        </div>  
                                                    </td>
                                                </tr>
                                                <!-- // Table row END -->
                                                    
                                                <!-- Table row -->
                                                <tr>
                                                    <td class="center">3</td>
                                                    <td> <img src="/MelisDesign/images/people/35/3.jpg" width="20" class="rounded-circle"> <span >Mary Dawson</span></td>
                                                    <td>DUBLIN, IE </td>
                                                    <td>Project Manager</td>
                                                    <td class="center">
                                                        <div class="rating text-faded">
                                                            <span class="star"></span>
                                                            <span class="star"></span>
                                                            <span class="star"></span>
                                                            <span class="star active"></span>
                                                            <span class="star"></span>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <!-- // Table row END -->
                                                
                                                <!-- Table row -->
                                                <tr>
                                                    <td class="center">1</td>
                                                    <td> <img src="/MelisDesign/images/people/35/2.jpg" width="20" class="rounded-circle"> <span >Laza Bogdan</span></td>
                                                    <td>MI, USA </td>
                                                    <td>Evangelist Developer</td>
                                                    <td class="center">
                                                        <div class="rating text-faded">
                                                                <span class="star"></span>
                                                                <span class="star"></span>
                                                                <span class="star"></span>
                                                                <span class="star active"></span>
                                                                <span class="star"></span>
                                                        </div>  
                                                    </td>
                                                </tr>
                                                <!-- // Table row END -->

                                                <!-- Table row -->
                                                <tr>
                                                    <td class="center">1</td>
                                                    <td> <img src="/MelisDesign/images/people/35/2.jpg" width="20" class="rounded-circle"> <span >Laza Bogdan</span></td>
                                                    <td>MI, USA </td>
                                                    <td>Evangelist Developer</td>
                                                    <td class="center">
                                                        <div class="rating text-faded">
                                                                <span class="star"></span>
                                                                <span class="star"></span>
                                                                <span class="star"></span>
                                                                <span class="star active"></span>
                                                                <span class="star"></span>
                                                        </div>  
                                                    </td>
                                                </tr>
                                                <!-- // Table row END -->

                                                <!-- Table row -->
                                                <tr>
                                                    <td class="center">1</td>
                                                    <td> <img src="/MelisDesign/images/people/35/2.jpg" width="20" class="rounded-circle"> <span >Laza Bogdan</span></td>
                                                    <td>MI, USA </td>
                                                    <td>Evangelist Developer</td>
                                                    <td class="center">
                                                        <div class="rating text-faded">
                                                            <span class="star"></span>
                                                            <span class="star"></span>
                                                            <span class="star"></span>
                                                            <span class="star active"></span>
                                                            <span class="star"></span>
                                                        </div>  
                                                    </td>
                                                </tr>
                                                <!-- // Table row END -->
                                            </tbody>
                                            <!-- // Table body END -->
                                        </table>
                                        <!-- // Table END -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <a href="" class="widget widget-inverse innerAll text-center text-regular widget-alerts-link">
                                <i class="display-block icon-alarm-clock text-xlarge"></i>
                                <span class="lead">3 Alerts</span>
                            </a>
                        </div>
                        <div class="col-md-4">
                            <a href="" class="widget widget-primary innerAll text-center widget-sign-ups-link">
                                <i class="display-block fa fa-group text-xlarge"></i>
                                <span class="lead">7 Sign Ups</span>
                            </a>
                        </div>
                        <div class="col-md-4">
                            <a href="" class="widget widget-info innerAll text-center widget-visits-link">
                                <i class="display-block icon-lab-beaker text-xlarge"></i>
                                <span class="lead">5,412 Visits</span>
                            </a>
                        </div>
                    </div>
                            
                    <!-- Widget -->
                    <div class="widget widget-inverse">
                        <div class="widget-head">
                            <h3 class="heading"><i class="icon-stocks-up fa fa-fw"></i> Recent Activity</h3>
                        </div>
                        
                        <div class="widget-body padding-none">

                            <div class="widget widget-tabs widget-tabs-icons-only-2 widget-activity margin-none border-none">

                                <!-- Tabs Heading -->
                                <div class="widget-head">
                                    <ul class="nav nav-tabs">
                                        <li class="nav-item active"><a class="nav-link glyphicons user_add" data-toggle="tab" href="#filterUsersTab"><i></i>Users</a></li>
                                        <li class="nav-item"><a class="nav-link glyphicons shopping_cart" data-toggle="tab" href="#filterOrdersTab"><i></i>Orders</a></li>
                                        <li class="nav-item"><a class="nav-link glyphicons envelope" data-toggle="tab" href="#filterMessagesTab"><i></i></a></li>
                                        <li class="nav-item"><a class="nav-link glyphicons link" data-toggle="tab" href="#filterLinksTab"><i></i></a></li>
                                        <li class="nav-item"><a class="nav-link glyphicons camera" data-toggle="tab" href="#filterPhotosTab"><i></i></a></li>
                                    </ul>
                                </div>
                                <!-- // Tabs Heading END -->
                                
                                <div class="widget-body padding-none">
                                    <div class="tab-content">
                                            
                                                            
                                        <!-- Filter Users Tab -->
                                        <div class="tab-pane active" id="filterUsersTab">
                                            <ul class="list">
                                            
                                                                            <!-- Activity item -->
                                                <li>
                                                    <span class="date">21/03</span>
                                                    <span class="glyphicons activity-icon user_add"><i></i></span>
                                                    <span class="ellipsis"><a href="">John Doe</a> registered at <a href="">Darius Jackson's</a> suggestion.</span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                            <!-- Activity item -->
                                                <li>
                                                    <span class="date">21/03</span>
                                                    <span class="glyphicons activity-icon user_add"><i></i></span>
                                                    <span class="ellipsis"><a href="">Martin Glades</a> registered at <a href="">Jane Doe's</a> suggestion.</span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                            <!-- Activity item -->
                                                <li>
                                                    <span class="date">21/03</span>
                                                    <span class="glyphicons activity-icon user_add"><i></i></span>
                                                    <span class="ellipsis"><a href="">John Doe</a> registered at <a href="">Melisa Ragae's</a> suggestion.</span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                            <!-- Activity item -->
                                                <li>
                                                    <span class="date">21/03</span>
                                                    <span class="glyphicons activity-icon user_add"><i></i></span>
                                                    <span class="ellipsis"><a href="">John Doe</a> registered at <a href="">Jane Doe's</a> suggestion.</span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                    <!-- Activity item -->
                                                <li>
                                                    <span class="date">21/03</span>
                                                    <span class="glyphicons activity-icon user_add"><i></i></span>
                                                    <span class="ellipsis"><a href="">Jane Doe</a> registered at <a href="">Martin Glades's</a> suggestion.</span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                            
                                            </ul>
                                        </div>
                                        <!-- // Filter Users Tab END -->
                                        
                                        <!-- Filter Orders Tab -->
                                        <div class="tab-pane" id="filterOrdersTab">
                                            <ul class="list">
                                            
                                                                            <!-- Activity item -->
                                                <li>
                                                    <span class="date">21/03</span>
                                                    <span class="glyphicons activity-icon shopping_cart"><i></i></span>
                                                    <span class="ellipsis"><a href="">Martin Glades</a> bought 10 items worth of &#8364; 50 (<a href="">order #2301</a>)</span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                            <!-- Activity item -->
                                                <li>
                                                    <span class="date">21/03</span>
                                                    <span class="glyphicons activity-icon shopping_cart"><i></i></span>
                                                    <span class="ellipsis"><a href="">Darius Jackson</a> bought 10 items worth of &#8364; 50 (<a href="">order #2302</a>)</span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                            <!-- Activity item -->
                                                <li>
                                                    <span class="date">21/03</span>
                                                    <span class="glyphicons activity-icon shopping_cart"><i></i></span>
                                                    <span class="ellipsis"><a href="">John Doe</a> bought 10 items worth of &#8364; 50 (<a href="">order #2303</a>)</span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                            <!-- Activity item -->
                                                <li>
                                                    <span class="date">21/03</span>
                                                    <span class="glyphicons activity-icon shopping_cart"><i></i></span>
                                                    <span class="ellipsis"><a href="">Melisa Ragae</a> bought 10 items worth of &#8364; 50 (<a href="">order #2304</a>)</span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                            <!-- Activity item -->
                                                <li>
                                                    <span class="date">21/03</span>
                                                    <span class="glyphicons activity-icon shopping_cart"><i></i></span>
                                                    <span class="ellipsis"><a href="">Martin Glades</a> bought 10 items worth of &#8364; 50 (<a href="">order #2305</a>)</span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                            
                                            </ul>
                                        </div>
                                        <!-- // Filter Orders Tab END -->
                                        
                                        <!-- Filter Messages Tab -->
                                        <div class="tab-pane" id="filterMessagesTab">
                                            <ul class="list">
                                            
                                                                                                        <!-- Activity item -->
                                                <li class="double">
                                                    <span class="glyphicons activity-icon envelope"><i></i></span>
                                                    <span class="ellipsis">
                                                        You have received an email from <a href="">Darius Jackson</a> (darius.jackson@fake-email.net)
                                                        <span class="meta">on 29 March, 2013 <span>1 hour ago</span></span>
                                                    </span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                                                        <!-- Activity item -->
                                                <li class="double highlight">
                                                    <span class="glyphicons activity-icon envelope"><i></i></span>
                                                    <span class="ellipsis">
                                                        You have received an email from <a href="">Martin Glades</a> (martin.glades@wee-email.com)
                                                        <span class="meta">on 29 March, 2013 <span>1 hour ago</span></span>
                                                    </span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                                                        <!-- Activity item -->
                                                <li class="double">
                                                    <span class="glyphicons activity-icon envelope"><i></i></span>
                                                    <span class="ellipsis">
                                                        You have received an email from <a href="">Martin Glades</a> (martin.glades@wee-email.com)
                                                        <span class="meta">on 29 March, 2013 <span>1 hour ago</span></span>
                                                    </span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                                                        <!-- Activity item -->
                                                <li class="double">
                                                    <span class="glyphicons activity-icon envelope"><i></i></span>
                                                    <span class="ellipsis">
                                                        You have received an email from <a href="">Jane Doe</a> (jane.doe@lovely-email.net)
                                                        <span class="meta">on 29 March, 2013 <span>1 hour ago</span></span>
                                                    </span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                                                        <!-- Activity item -->
                                                <li class="double">
                                                    <span class="glyphicons activity-icon envelope"><i></i></span>
                                                    <span class="ellipsis">
                                                        You have received an email from <a href="">Martin Glades</a> (martin.glades@wee-email.com)
                                                        <span class="meta">on 29 March, 2013 <span>1 hour ago</span></span>
                                                    </span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                            
                                            </ul>
                                        </div>
                                        <!-- // Filter Messages Tab END -->
                                        
                                        <!-- Filter Links Tab -->
                                        <div class="tab-pane" id="filterLinksTab">
                                            <ul class="list">
                                            
                                                                            <!-- Activity item -->
                                                <li>
                                                    <span class="date">21/03</span>
                                                    <span class="glyphicons activity-icon link"><i></i></span>
                                                    <span class="ellipsis"><a href="">Martin Glades</a> bought 10 items worth of &#8364; 50 (<a href="">order #2301</a>)</span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                            <!-- Activity item -->
                                                <li>
                                                    <span class="date">21/03</span>
                                                    <span class="glyphicons activity-icon link"><i></i></span>
                                                    <span class="ellipsis"><a href="">Melisa Ragae</a> bought 10 items worth of &#8364; 50 (<a href="">order #2302</a>)</span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                            <!-- Activity item -->
                                                <li>
                                                    <span class="date">21/03</span>
                                                    <span class="glyphicons activity-icon link"><i></i></span>
                                                    <span class="ellipsis"><a href="">John Doe</a> bought 10 items worth of &#8364; 50 (<a href="">order #2303</a>)</span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                            <!-- Activity item -->
                                                <li>
                                                    <span class="date">21/03</span>
                                                    <span class="glyphicons activity-icon link"><i></i></span>
                                                    <span class="ellipsis"><a href="">Jane Doe</a> bought 10 items worth of &#8364; 50 (<a href="">order #2304</a>)</span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                            <!-- Activity item -->
                                                <li>
                                                    <span class="date">21/03</span>
                                                    <span class="glyphicons activity-icon link"><i></i></span>
                                                    <span class="ellipsis"><a href="">Jane Doe</a> bought 10 items worth of &#8364; 50 (<a href="">order #2305</a>)</span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                            
                                            </ul>
                                        </div>
                                        <!-- // Filter Links Tab END -->
                                        
                                        <!-- Filter Photos Tab -->
                                        <div class="tab-pane" id="filterPhotosTab">
                                            <ul class="list">
                                            
                                                                            <!-- Activity item -->
                                                <li>
                                                    <span class="date">21/03</span>
                                                    <span class="glyphicons activity-icon camera"><i></i></span>
                                                    <span class="ellipsis"><a href="">Jane Doe</a> bought 10 items worth of &#8364; 50 (<a href="">order #2301</a>)</span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                            <!-- Activity item -->
                                                <li>
                                                    <span class="date">21/03</span>
                                                    <span class="glyphicons activity-icon camera"><i></i></span>
                                                    <span class="ellipsis"><a href="">Melisa Ragae</a> bought 10 items worth of &#8364; 50 (<a href="">order #2302</a>)</span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                            <!-- Activity item -->
                                                <li>
                                                    <span class="date">21/03</span>
                                                    <span class="glyphicons activity-icon camera"><i></i></span>
                                                    <span class="ellipsis"><a href="">John Doe</a> bought 10 items worth of &#8364; 50 (<a href="">order #2303</a>)</span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                            <!-- Activity item -->
                                                <li>
                                                    <span class="date">21/03</span>
                                                    <span class="glyphicons activity-icon camera"><i></i></span>
                                                    <span class="ellipsis"><a href="">Melisa Ragae</a> bought 10 items worth of &#8364; 50 (<a href="">order #2304</a>)</span>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <!-- // Activity item END -->
                                                                            
                                            </ul>
                                        </div>
                                        <!-- // Filter Photos Tab END -->
                                    
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>


                    <!-- Chat -->
                    <div class="widget widget-inverse widget-chat">

                        <div class="widget-head">
                            <h4 class="heading"><i class="icon-comment-fill-1"></i> Chat</h4>
                        </div>
                        <div class="widget-body padding-none border-bottom">
                        
                            <!-- Slim Scroll -->
                            <div class="slim-scroll chat-items" data-scroll-height="235px" data-scroll-size="0">
                                
                                <!-- Media item -->
                                <div class="media innerAll border-bottom">
                                    <small class="author"><a href="#" title="" class="strong">Martin</a></small>
                                    <img src="/MelisDesign/images/people/50/2.jpg" alt="" class="rounded-circle media-object float-left">
                                    <div class="media-body">
                                        <small class="date"><cite>just now</cite></small>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae accumsan mauris. Donec vitae nibh felis, facilisis bibendum sapien.</p>
                                    </div>
                                </div>
                                <!-- // Media item END -->
                                
                                <!-- Media item -->
                                <div class="media innerAll border-bottom right">
                                    <small class="author"><a href="#" title="" class="strong">John Doe</a></small>
                                    <img src="/MelisDesign/images/people/50/5.jpg" alt="" class="rounded-circle media-object float-right" > 
                                    <div class="media-body">
                                        <small class="date"><cite>15 seconds ago</cite></small>
                                        <p>In ultricies ante eget tortor euismod vitae molestie eros hendrerit. Cras tristique, orci ac lacinia aliquet, velit risus laoreet lectus, eget sollicitudin metus orci non nulla.</p>
                                    </div>
                                </div>
                                <!-- // Media item END -->
                                
                                <!-- Media item -->
                                <div class="media innerAll">
                                    <small class="author"><a href="#" title="" class="strong">Ricky</a></small>
                                    <img src="/MelisDesign/images/people/50/7.jpg" alt="" class="rounded-circle media-object float-left" > 
                                    <div class="media-body">
                                        <small class="date"><cite>5 minutes ago</cite></small>
                                        <p>Pellentesque ac turpis turpis. Aliquam erat volutpat. Proin semper auctor mauris vel tempor. Ut eget turpis neque. Nam ultricies tortor eu odio ultricies euismod.</p>
                                    </div>
                                </div>
                                <!-- // Media item END -->
                                
                            </div>
                            <!-- // Slim Scroll END -->
                        
                        </div>
                        
                        <div class="chat-controls bg-default innerAll half">
                            <div class="">
                                <form class="margin-none">
                                    <div class="input-group">
                                        <input type="text" name="message" class="form-control" placeholder="Type your message .." />
                                        <div class="input-group-btn">
                                            <a type="submit" class="btn btn-primary"><i class="fa fa-comments-o"></i></a>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        
                    </div> <!-- // Chat END -->

                </div>
            
                <div class="col-md-3">
                    
                    <div class="widget widget-inverse">
                        <div class="widget-head border-bottom-none">
                            <h4 class="heading"><i class="icon-wind-speed-censor fa fa-fw"></i> Demographics</h4>
                        </div>
                        <div class="widget-body padding-none">
                            
                            <div class="innerAll text-center border-bottom">
                                <p class="lead margin-none"><span class="strong">1,210</span> of <span class="text-primary">your customers</span></p>
                            </div>
                            <div class="innerAll">
                                <div class="innerLR text-center">
                                    <div class="progress progress-mini">
                                        <div class="progress-bar progress-bar-primary" style="width: 30%"></div>
                                    </div>
                                    <p class="margin-none">living in <span class="strong">United States</span>, aged <span class="strong">45+</span> suffer from a <span class="strong text-primary">deadly disease</span></p>
                                </div>
                            </div>
                                    
                        </div>
                    </div>

                    <div class="widget widget-profile">
                        <div class="widget-head bg-primary">
                            <a href="" class="float-right"><i class="fa fa-cog float-right"></i></a>
                            <img src="/MelisDesign/images/people/100/8.jpg" alt="" class="rounded-circle">
                            <div class="clearfix"></div>
                             <a href=""> John Doe <i class="fa fa-arrow-right"></i></a>
                        </div>
                        <div class="widget-body text-center">
                            <div class="btn-group">
                                <a href="" class="btn btn-primary "><i class="icon-user-1"></i></a>
                                <a href="" class="btn btn-default btn-stroke "><i class="icon-location-fill-1"></i></a>
                                <a href="" class="btn btn-default btn-stroke"><i class="icon-star-fill"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="widget widget-inverse">
                        <div class="widget-head">
                            <h4 class="heading"><i class="icon-user-1 fa fa-fw"></i> Team Members</h4>
                        </div>
                        <div class="widget-body padding-none">
                            <div class="media innerAll border-bottom margin-none half">
                                <a class="float-left" href="#"><img src="/MelisDesign/images/people/50/8.jpg" alt="" class="rounded-circle media-object"></a>
                                <div class="media-body">
                                    <a href="" class="strong text-primary"> John Doe</a> 
                                    <div class="clearfix"></div>
                                    Senior UI Designer
                                </div>
                            </div>
                            <div class="media innerAll border-bottom margin-none half">
                                <a class="float-left" href="#"><img src="/MelisDesign/images/people/50/3.jpg" alt="" class="rounded-circle media-object"></a>
                                <div class="media-body">
                                    <a href="" class="strong text-primary"> Jane Millbury</a> 
                                    <div class="clearfix"></div>
                                    Senior UI Designer
                                </div>
                            </div>
                            <div class="media innerAll margin-none half">
                                <a class="float-left" href="#"><img src="/MelisDesign/images/people/50/18.jpg" alt="" class="rounded-circle media-object"></a>
                                <div class="media-body">
                                    <a href="" class="strong text-primary"> Bogdan Laza</a> 
                                    <div class="clearfix"></div>
                                    Senior UI Designer
                                </div>
                            </div>
                        </div>
                    </div>
                
                    <!-- To do -->
                    <div class="widget widget-inverse">
                        <div class="widget-head border-none">
                            <h3 class="heading"><i class="icon-task-check fa fa-fw"></i> To do</h3>
                        </div>
                        <div class="widget-body padding-none">
                            <div class="border-bottom">
                                <div class="input-group">
                                    <input type="text" class="form-control border-none" placeholder="Add new task">
                                    <div class="input-group-btn">
                                        <button class="btn btn-success"><i class="fa fa-plus-circle"></i></button>
                                    </div>
                                </div>
                            </div>
                            <div class="innerLR half">
                                <div class="checkbox">
                                    <label><input type="checkbox" value="1">Client Meeting</label>
                                </div>
                                <div class="checkbox">
                                    <label class="done"><input type="checkbox" checked="checked" value="1"><strike>Find new Developer</strike></label>
                                </div>
                                <div class="checkbox">
                                    <label><input type="checkbox" value="1">Create a Quote!</label>
                                </div>
                                <div class="checkbox check-success">
                                    <label><input type="checkbox" value="1">This will be your next task</label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Widget -->
                    <div class="widget widget-inverse">
                            
                        <!-- Widget Heading -->
                        <div class="widget-head">
                            <h4 class="heading glyphicons calendar"><i></i>Mini Calendar</h4>
                        </div>
                        <!-- // Widget Heading END -->
                        
                        <div class="widget-body innerAll half">
                            <div id="datepicker-inline"></div>
                        </div>
                    </div>
                    <!-- // Widget END -->

                </div>
            </div>
        </div>
    </div>
    <!-- // Content END -->
        
<div class="clearfix"></div>
<!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->