<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;
?>
<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    <div id="content">
        <div class="heading-buttons bg-white border-bottom innerAll">
            <h1 class="content-heading padding-none pull-left">Contacts</h1>
            <div class="clearfix"></div>
        </div>
        <div class="input-group input-lg ">
            <input type="text" class="form-control" placeholder="Search Contact">
            <div class="input-group-btn">
                <button class="btn btn-default" type="button"><i class="fa fa-search"></i>
                </button>
            </div>
        </div>

        <div class="innerLR border-top">

            <div class="row row-merge">

                <div class="col-md-6 bg-white border-bottom ">
                    <div class="row">

                        <div class="col-sm-9">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object" src="MelisDesign/images/people/100/1.jpg" alt="...">
                                </a>
                                <div class="media-body innerAll half">
                                    <h4 class="media-heading padding-none"><a href="">First Surname</a> </h4>
                                    <small class="text-success"><i class="fa fa-check"></i> Friend</small>
                                    <p>Lives in Michigan, USA</p>
                                </div>
                            </div>

                        </div>
                        <div class="col-sm-3 ">
                            <div class="innerAll half text-right">
                                <div class="innerT half">
                                    <a href="" class="btn btn-info btn-xs btn-regular"><i class="fa fa-thumbs-up"></i> Like</a>
                                </div>
                                <div class="innerT half">
                                    <a href="" class="btn btn-primary btn-xs margin-top "><i class="fa fa-envelope-o"></i> Chat</a>
                                </div>
                            </div>
                        </div>


                    </div>


                </div>
                <div class="col-md-6 bg-white border-bottom ">
                    <div class="row">

                        <div class="col-sm-9">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object" src="MelisDesign/images/people/100/2.jpg" alt="...">
                                </a>
                                <div class="media-body innerAll half">
                                    <h4 class="media-heading padding-none"><a href="">Name Surname</a> </h4>
                                    <small class="text-success"><i class="fa fa-check"></i> Friend</small>
                                    <p>Lives in Michigan, USA</p>
                                </div>
                            </div>

                        </div>
                        <div class="col-sm-3 ">
                            <div class="innerAll half text-right">
                                <div class="innerT half">
                                    <a href="" class="btn btn-info btn-xs btn-regular"><i class="fa fa-thumbs-up"></i> Like</a>
                                </div>
                                <div class="innerT half">
                                    <a href="" class="btn btn-primary btn-xs margin-top "><i class="fa fa-envelope-o"></i> Chat</a>
                                </div>
                            </div>
                        </div>


                    </div>


                </div>
                <div class="col-md-6 bg-white border-bottom ">
                    <div class="row">

                        <div class="col-sm-9">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object" src="MelisDesign/images/people/100/3.jpg" alt="...">
                                </a>
                                <div class="media-body innerAll half">
                                    <h4 class="media-heading padding-none"><a href="">First Surname</a> </h4>
                                    <small class="text-success"><i class="fa fa-check"></i> Friend</small>
                                    <p>Lives in Michigan, USA</p>
                                </div>
                            </div>

                        </div>
                        <div class="col-sm-3 ">
                            <div class="innerAll half text-right">
                                <div class="innerT half">
                                    <a href="" class="btn btn-info btn-xs btn-regular"><i class="fa fa-thumbs-up"></i> Like</a>
                                </div>
                                <div class="innerT half">
                                    <a href="" class="btn btn-primary btn-xs margin-top "><i class="fa fa-envelope-o"></i> Chat</a>
                                </div>
                            </div>
                        </div>


                    </div>


                </div>
                <div class="col-md-6 bg-white border-bottom ">
                    <div class="row">

                        <div class="col-sm-9">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object" src="MelisDesign/images/people/100/4.jpg" alt="...">
                                </a>
                                <div class="media-body innerAll half">
                                    <h4 class="media-heading padding-none"><a href="">Name Surname</a> </h4>
                                    <small class="text-success"><i class="fa fa-check"></i> Friend</small>
                                    <p>Lives in Michigan, USA</p>
                                </div>
                            </div>

                        </div>
                        <div class="col-sm-3 ">
                            <div class="innerAll half text-right">
                                <div class="innerT half">
                                    <a href="" class="btn btn-info btn-xs btn-regular"><i class="fa fa-thumbs-up"></i> Like</a>
                                </div>
                                <div class="innerT half">
                                    <a href="" class="btn btn-primary btn-xs margin-top "><i class="fa fa-envelope-o"></i> Chat</a>
                                </div>
                            </div>
                        </div>


                    </div>


                </div>
                <div class="col-md-6 bg-white border-bottom ">
                    <div class="row">

                        <div class="col-sm-9">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object" src="MelisDesign/images/people/100/5.jpg" alt="...">
                                </a>
                                <div class="media-body innerAll half">
                                    <h4 class="media-heading padding-none"><a href="">First Surname</a> </h4>
                                    <small class="text-success"><i class="fa fa-check"></i> Friend</small>
                                    <p>Lives in Michigan, USA</p>
                                </div>
                            </div>

                        </div>
                        <div class="col-sm-3 ">
                            <div class="innerAll half text-right">
                                <div class="innerT half">
                                    <a href="" class="btn btn-info btn-xs btn-regular"><i class="fa fa-thumbs-up"></i> Like</a>
                                </div>
                                <div class="innerT half">
                                    <a href="" class="btn btn-primary btn-xs margin-top "><i class="fa fa-envelope-o"></i> Chat</a>
                                </div>
                            </div>
                        </div>


                    </div>


                </div>
                <div class="col-md-6 bg-white border-bottom ">
                    <div class="row">

                        <div class="col-sm-9">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object" src="MelisDesign/images/people/100/6.jpg" alt="...">
                                </a>
                                <div class="media-body innerAll half">
                                    <h4 class="media-heading padding-none"><a href="">Name Surname</a> </h4>
                                    <small class="text-success"><i class="fa fa-check"></i> Friend</small>
                                    <p>Lives in Michigan, USA</p>
                                </div>
                            </div>

                        </div>
                        <div class="col-sm-3 ">
                            <div class="innerAll half text-right">
                                <div class="innerT half">
                                    <a href="" class="btn btn-info btn-xs btn-regular"><i class="fa fa-thumbs-up"></i> Like</a>
                                </div>
                                <div class="innerT half">
                                    <a href="" class="btn btn-primary btn-xs margin-top "><i class="fa fa-envelope-o"></i> Chat</a>
                                </div>
                            </div>
                        </div>


                    </div>


                </div>
                <div class="col-md-6 bg-white border-bottom ">
                    <div class="row">

                        <div class="col-sm-9">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object" src="MelisDesign/images/people/100/7.jpg" alt="...">
                                </a>
                                <div class="media-body innerAll half">
                                    <h4 class="media-heading padding-none"><a href="">First Surname</a> </h4>
                                    <small class="text-success"><i class="fa fa-check"></i> Friend</small>
                                    <p>Lives in Michigan, USA</p>
                                </div>
                            </div>

                        </div>
                        <div class="col-sm-3 ">
                            <div class="innerAll half text-right">
                                <div class="innerT half">
                                    <a href="" class="btn btn-info btn-xs btn-regular"><i class="fa fa-thumbs-up"></i> Like</a>
                                </div>
                                <div class="innerT half">
                                    <a href="" class="btn btn-primary btn-xs margin-top "><i class="fa fa-envelope-o"></i> Chat</a>
                                </div>
                            </div>
                        </div>


                    </div>


                </div>
                <div class="col-md-6 bg-white border-bottom ">
                    <div class="row">

                        <div class="col-sm-9">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object" src="MelisDesign/images/people/100/8.jpg" alt="...">
                                </a>
                                <div class="media-body innerAll half">
                                    <h4 class="media-heading padding-none"><a href="">Name Surname</a> </h4>
                                    <small class="text-success"><i class="fa fa-check"></i> Friend</small>
                                    <p>Lives in Michigan, USA</p>
                                </div>
                            </div>

                        </div>
                        <div class="col-sm-3 ">
                            <div class="innerAll half text-right">
                                <div class="innerT half">
                                    <a href="" class="btn btn-info btn-xs btn-regular"><i class="fa fa-thumbs-up"></i> Like</a>
                                </div>
                                <div class="innerT half">
                                    <a href="" class="btn btn-primary btn-xs margin-top "><i class="fa fa-envelope-o"></i> Chat</a>
                                </div>
                            </div>
                        </div>


                    </div>


                </div>
                <div class="col-md-6 bg-white border-bottom ">
                    <div class="row">

                        <div class="col-sm-9">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object" src="MelisDesign/images/people/100/9.jpg" alt="...">
                                </a>
                                <div class="media-body innerAll half">
                                    <h4 class="media-heading padding-none"><a href="">First Surname</a> </h4>
                                    <small class="text-success"><i class="fa fa-check"></i> Friend</small>
                                    <p>Lives in Michigan, USA</p>
                                </div>
                            </div>

                        </div>
                        <div class="col-sm-3 ">
                            <div class="innerAll half text-right">
                                <div class="innerT half">
                                    <a href="" class="btn btn-info btn-xs btn-regular"><i class="fa fa-thumbs-up"></i> Like</a>
                                </div>
                                <div class="innerT half">
                                    <a href="" class="btn btn-primary btn-xs margin-top "><i class="fa fa-envelope-o"></i> Chat</a>
                                </div>
                            </div>
                        </div>


                    </div>


                </div>
                <div class="col-md-6 bg-white border-bottom ">
                    <div class="row">

                        <div class="col-sm-9">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object" src="MelisDesign/images/people/100/10.jpg" alt="...">
                                </a>
                                <div class="media-body innerAll half">
                                    <h4 class="media-heading padding-none"><a href="">Name Surname</a> </h4>
                                    <small class="text-success"><i class="fa fa-check"></i> Friend</small>
                                    <p>Lives in Michigan, USA</p>
                                </div>
                            </div>

                        </div>
                        <div class="col-sm-3 ">
                            <div class="innerAll half text-right">
                                <div class="innerT half">
                                    <a href="" class="btn btn-info btn-xs btn-regular"><i class="fa fa-thumbs-up"></i> Like</a>
                                </div>
                                <div class="innerT half">
                                    <a href="" class="btn btn-primary btn-xs margin-top "><i class="fa fa-envelope-o"></i> Chat</a>
                                </div>
                            </div>
                        </div>


                    </div>


                </div>
                <div class="col-md-6 bg-white border-bottom ">
                    <div class="row">

                        <div class="col-sm-9">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object" src="MelisDesign/images/people/100/11.jpg" alt="...">
                                </a>
                                <div class="media-body innerAll half">
                                    <h4 class="media-heading padding-none"><a href="">First Surname</a> </h4>
                                    <small class="text-success"><i class="fa fa-check"></i> Friend</small>
                                    <p>Lives in Michigan, USA</p>
                                </div>
                            </div>

                        </div>
                        <div class="col-sm-3 ">
                            <div class="innerAll half text-right">
                                <div class="innerT half">
                                    <a href="" class="btn btn-info btn-xs btn-regular"><i class="fa fa-thumbs-up"></i> Like</a>
                                </div>
                                <div class="innerT half">
                                    <a href="" class="btn btn-primary btn-xs margin-top "><i class="fa fa-envelope-o"></i> Chat</a>
                                </div>
                            </div>
                        </div>


                    </div>


                </div>
                <div class="col-md-6 bg-white border-bottom ">
                    <div class="row">

                        <div class="col-sm-9">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object" src="MelisDesign/images/people/100/12.jpg" alt="...">
                                </a>
                                <div class="media-body innerAll half">
                                    <h4 class="media-heading padding-none"><a href="">Name Surname</a> </h4>
                                    <small class="text-success"><i class="fa fa-check"></i> Friend</small>
                                    <p>Lives in Michigan, USA</p>
                                </div>
                            </div>

                        </div>
                        <div class="col-sm-3 ">
                            <div class="innerAll half text-right">
                                <div class="innerT half">
                                    <a href="" class="btn btn-info btn-xs btn-regular"><i class="fa fa-thumbs-up"></i> Like</a>
                                </div>
                                <div class="innerT half">
                                    <a href="" class="btn btn-primary btn-xs margin-top "><i class="fa fa-envelope-o"></i> Chat</a>
                                </div>
                            </div>
                        </div>


                    </div>


                </div>
                <div class="col-md-6 bg-white border-bottom ">
                    <div class="row">

                        <div class="col-sm-9">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object" src="MelisDesign/images/people/100/13.jpg" alt="...">
                                </a>
                                <div class="media-body innerAll half">
                                    <h4 class="media-heading padding-none"><a href="">First Surname</a> </h4>
                                    <small class="text-success"><i class="fa fa-check"></i> Friend</small>
                                    <p>Lives in Michigan, USA</p>
                                </div>
                            </div>

                        </div>
                        <div class="col-sm-3 ">
                            <div class="innerAll half text-right">
                                <div class="innerT half">
                                    <a href="" class="btn btn-info btn-xs btn-regular"><i class="fa fa-thumbs-up"></i> Like</a>
                                </div>
                                <div class="innerT half">
                                    <a href="" class="btn btn-primary btn-xs margin-top "><i class="fa fa-envelope-o"></i> Chat</a>
                                </div>
                            </div>
                        </div>


                    </div>


                </div>
                <div class="col-md-6 bg-white border-bottom ">
                    <div class="row">

                        <div class="col-sm-9">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object" src="MelisDesign/images/people/100/14.jpg" alt="...">
                                </a>
                                <div class="media-body innerAll half">
                                    <h4 class="media-heading padding-none"><a href="">Name Surname</a> </h4>
                                    <small class="text-success"><i class="fa fa-check"></i> Friend</small>
                                    <p>Lives in Michigan, USA</p>
                                </div>
                            </div>

                        </div>
                        <div class="col-sm-3 ">
                            <div class="innerAll half text-right">
                                <div class="innerT half">
                                    <a href="" class="btn btn-info btn-xs btn-regular"><i class="fa fa-thumbs-up"></i> Like</a>
                                </div>
                                <div class="innerT half">
                                    <a href="" class="btn btn-primary btn-xs margin-top "><i class="fa fa-envelope-o"></i> Chat</a>
                                </div>
                            </div>
                        </div>


                    </div>


                </div>

            </div>
        </div>




    </div>
    <!-- // Content END -->
    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->