<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;
        
?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    <div id="content">
        <h1 class="content-heading bg-white border-bottom">Ratings <span>Components</span></h1>
        <div class="innerAll spacing-x2">

            <div class="row">
                <div class="col-md-3">
                    <div class="widget widget-heading-simple widget-body-white">
                        <div class="widget-body padding-none">
                            <div class="row row-merge">
                                <div class="col-md-6">
                                    <h5 class="innerAll margin-none bg-gray border-bottom text-center strong muted text-uppercase"><i class="fa fa-fw fa-coffee text-faded"></i> Guest</h5>
                                    <div class="innerAll center inner-2x">
                                        <span class="text-xxlarge strong text-primary">4</span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <h5 class="innerAll margin-none bg-gray border-bottom text-center strong muted text-uppercase"><i class="fa fa-fw fa-beer text-faded"></i> Host</h5>
                                    <div class="innerAll center inner-2x muted">
                                        <span class="text-xxlarge strong">1</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>



                </div>
                <div class="col-md-3">
                    <div class="widget widget-body-white">
                        <div class="widget-head">
                            <h4 class="heading text-uppercase">Icon ratings</h4>
                        </div>
                        <div class="widget-body center innerAll inner-2x" data-height="111px">
                            <span class="text-medium text-primary"><i class="fa fa-trophy"></i></span>
                            <span class="text-medium text-primary"><i class="fa fa-trophy"></i></span>
                            <span class="text-medium text-primary"><i class="fa fa-trophy"></i></span>
                            <span class="text-medium text-faded"><i class="fa fa-trophy"></i></span>
                            <span class="text-medium text-faded"><i class="fa fa-trophy"></i></span>
                            <div class="separator bottom"></div>
                            <p class="lead">Total rating: <strong>3.4</strong>
                            </p>
                        </div>
                    </div>



                </div>
                <div class="col-md-6">
                    <div class="widget">
                        <div class="widget-head">
                            <h4 class="heading">CSS Star rating</h4>
                        </div>
                        <div class="widget-body center innerAll inner-2x" data-height="111px">
                            <div class="rating text-medium text-faded margin-top-none">
                                <span class="star"></span>
                                <span class="star"></span>
                                <span class="star"></span>
                                <span class="star active"></span>
                                <span class="star"></span>
                            </div>
                            <div class="separator bottom"></div>
                            <p class="lead">Current rating: <strong>2/5</strong>
                            </p>
                        </div>
                    </div>



                </div>
            </div>


            <table class="table table-white table-vertical-center margin-none table-striped footable">
                <thead>
                    <tr>
                        <th data-class="expand" class="center">Photo</th>
                        <th data-hide="phone" class="center">Full name</th>
                        <th data-hide="phone" class="center">Location</th>
                        <th data-hide="phone,tablet" class="center">Rating</th>
                        <th data-hide="phone" class="center">Bonus</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="center"><img data-src="holder.js/50x50/dark" alt="Image" />
                        </td>
                        <td class="strong center">Lorem Ipsum Dolor</td>
                        <td class="center">Romania <a href="" class="innerL text-underline">view on map <i class="fa fa-map-marker"></i></a>
                        </td>
                        <td class="center">
                            <div class="rating text-medium text-faded read-only">
                                <span class="star active"></span>
                                <span class="star"></span>
                                <span class="star"></span>
                                <span class="star"></span>
                                <span class="star"></span>
                            </div>
                        </td>
                        <td class="center"><span class="strong text-medium">5 <i class="fa fa-gift"></i></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="center"><img data-src="holder.js/50x50/dark" alt="Image" />
                        </td>
                        <td class="strong center">John Doe</td>
                        <td class="center">United States <a href="" class="innerL text-underline">view on map <i class="fa fa-map-marker"></i></a>
                        </td>
                        <td class="center">
                            <div class="rating text-medium read-only">
                                <span class="star"></span>
                                <span class="star"></span>
                                <span class="star active"></span>
                                <span class="star"></span>
                                <span class="star"></span>
                            </div>
                        </td>
                        <td class="center"><span class="strong text-medium">4 <i class="fa fa-gift"></i></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="center"><img data-src="holder.js/50x50/dark" alt="Image" />
                        </td>
                        <td class="strong center">Jane Doe</td>
                        <td class="center">Europe <a href="" class="innerL text-underline">view on map <i class="fa fa-map-marker"></i></a>
                        </td>
                        <td class="center">
                            <div class="rating text-medium text-faded read-only">
                                <span class="star"></span>
                                <span class="star"></span>
                                <span class="star"></span>
                                <span class="star"></span>
                                <span class="star"></span>
                            </div>
                        </td>
                        <td class="center"><span class="strong text-medium text-faded">2 <i class="fa fa-gift"></i></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="center"><img data-src="holder.js/50x50/dark" alt="Image" />
                        </td>
                        <td class="strong center">Hulky Bean</td>
                        <td class="center">On the Moon <a href="" class="innerL text-underline">view on map <i class="fa fa-map-marker"></i></a>
                        </td>
                        <td class="center">
                            <div class="rating text-medium text-faded read-only">
                                <span class="star"></span>
                                <span class="star"></span>
                                <span class="star"></span>
                                <span class="star"></span>
                                <span class="star"></span>
                            </div>
                        </td>
                        <td class="center"><span class="strong text-medium text-faded">1 <i class="fa fa-gift"></i></span>
                        </td>
                    </tr>
                </tbody>
            </table>





        </div>


    </div>
    <!-- // Content END -->

        
<div class="clearfix"></div>
<!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->


<script>
    $(function() {
        $.getScript('/MelisCore/assets/components/plugins/holder/holder.js');
    });
</script>