<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    <div id="content">
        <div class="heading-buttons bg-white border-bottom innerAll">
            <h1 class="content-heading padding-none pull-left">Filterable Portfolio</h1>
            <div class="clearfix"></div>
        </div>

        <div class="innerAll spacing-x2">

            <div class="innerB">
                <div class="button-filters">
                    <button class="btn btn-inverse filter active" data-filter=".mixit-filter-1">Filter 1</button>
                    <button class="btn btn-inverse filter" data-filter=".mixit-filter-2">Filter 2</button>
                    <button class="btn btn-inverse filter" data-filter="all">Show all</button>
                </div>
            </div>

            <div class="mixitup">
                <div class="row">
                    <div class="mix-target mixit-filter-1 col-md-4" data-order="1">
                        <div class="widget bg-none widget-pinterest active">
                            <div class="widget-body bg-none padding-none">
                                <a href="http://vimeo.com/59015141" data-toggle="prettyPhoto" class="thumb overflow-hidden" data-height="150">
                                    <img src="/MelisDesign/images/video/1.jpg" alt="photo" />
                                </a>
                                <div class="description bg-white overflow-hidden" data-height="130">
                                    <h5 class="text-uppercase">Publix Sprinkler</h5>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, consequuntur iure commodi omnis at pariatur quis hic mollitia impedit error.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mix-target mixit-filter-2 col-md-4" data-order="2">
                        <div class="widget bg-none widget-pinterest">
                            <div class="widget-body bg-none padding-none">
                                <a href="http://vimeo.com/50522981" data-toggle="prettyPhoto" class="thumb overflow-hidden" data-height="150">
                                    <img src="/MelisDesign/images/video/2.jpg" alt="photo" />
                                </a>
                                <div class="description bg-white overflow-hidden" data-height="130">
                                    <h5 class="text-uppercase">One More Beer!</h5>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, consequuntur iure commodi omnis at pariatur quis hic mollitia impedit error.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mix-target mixit-filter-1 col-md-4" data-order="1">
                        <div class="widget bg-none widget-pinterest">
                            <div class="widget-body bg-none padding-none">
                                <a href="http://vimeo.com/54932277" data-toggle="prettyPhoto" class="thumb overflow-hidden" data-height="150">
                                    <img src="/MelisDesign/images/video/3.jpg" alt="photo" />
                                </a>
                                <div class="description bg-white overflow-hidden" data-height="130">
                                    <h5 class="text-uppercase">Spacebound: Models &amp; Props</h5>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, consequuntur iure commodi omnis at pariatur quis hic mollitia impedit error.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mix-target mixit-filter-2 col-md-4" data-order="2">
                        <div class="widget bg-none widget-pinterest">
                            <div class="widget-body bg-none padding-none">
                                <a href="http://vimeo.com/4749536" data-toggle="prettyPhoto" class="thumb overflow-hidden" data-height="150">
                                    <img src="/MelisDesign/images/video/4.jpg" alt="photo" />
                                </a>
                                <div class="description bg-white overflow-hidden" data-height="130">
                                    <h5 class="text-uppercase">Alma</h5>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, consequuntur iure commodi omnis at pariatur quis hic mollitia impedit error.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mix-target mixit-filter-1 col-md-4" data-order="1">
                        <div class="widget bg-none widget-pinterest active">
                            <div class="widget-body bg-none padding-none">
                                <a href="http://vimeo.com/33670490" data-toggle="prettyPhoto" class="thumb overflow-hidden" data-height="150">
                                    <img src="/MelisDesign/images/video/5.jpg" alt="photo" />
                                </a>
                                <div class="description bg-white overflow-hidden" data-height="130">
                                    <h5 class="text-uppercase">The Artists</h5>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, consequuntur iure commodi omnis at pariatur quis hic mollitia impedit error.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mix-target mixit-filter-2 col-md-4" data-order="2">
                        <div class="widget bg-none widget-pinterest">
                            <div class="widget-body bg-none padding-none">
                                <a href="http://vimeo.com/8706167" data-toggle="prettyPhoto" class="thumb overflow-hidden" data-height="150">
                                    <img src="/MelisDesign/images/video/6.jpg" alt="photo" />
                                </a>
                                <div class="description bg-white overflow-hidden" data-height="130">
                                    <h5 class="text-uppercase">Les Dangereux</h5>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, consequuntur iure commodi omnis at pariatur quis hic mollitia impedit error.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mix-target mixit-filter-1 col-md-4" data-order="1">
                        <div class="widget bg-none widget-pinterest">
                            <div class="widget-body bg-none padding-none">
                                <a href="http://vimeo.com/51478122" data-toggle="prettyPhoto" class="thumb overflow-hidden" data-height="150">
                                    <img src="/MelisDesign/images/video/7.jpg" alt="photo" />
                                </a>
                                <div class="description bg-white overflow-hidden" data-height="130">
                                    <h5 class="text-uppercase">Dum Spiro - HD</h5>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, consequuntur iure commodi omnis at pariatur quis hic mollitia impedit error.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mix-target mixit-filter-2 col-md-4" data-order="2">
                        <div class="widget bg-none widget-pinterest">
                            <div class="widget-body bg-none padding-none">
                                <a href="http://vimeo.com/29573040" data-toggle="prettyPhoto" class="thumb overflow-hidden" data-height="150">
                                    <img src="/MelisDesign/images/video/8.jpg" alt="photo" />
                                </a>
                                <div class="description bg-white overflow-hidden" data-height="130">
                                    <h5 class="text-uppercase">A Shadow of Blue</h5>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, consequuntur iure commodi omnis at pariatur quis hic mollitia impedit error.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mix-target mixit-filter-1 col-md-4" data-order="1">
                        <div class="widget bg-none widget-pinterest">
                            <div class="widget-body bg-none padding-none">
                                <a href="http://vimeo.com/50540814" data-toggle="prettyPhoto" class="thumb overflow-hidden" data-height="150">
                                    <img src="/MelisDesign/images/video/9.jpg" alt="photo" />
                                </a>
                                <div class="description bg-white overflow-hidden" data-height="130">
                                    <h5 class="text-uppercase">50 Jahre Orion</h5>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, consequuntur iure commodi omnis at pariatur quis hic mollitia impedit error.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mix-target mixit-filter-2 col-md-4" data-order="2">
                        <div class="widget bg-none widget-pinterest">
                            <div class="widget-body bg-none padding-none">
                                <a href="http://vimeo.com/14989162" data-toggle="prettyPhoto" class="thumb overflow-hidden" data-height="150">
                                    <img src="/MelisDesign/images/video/10.jpg" alt="photo" />
                                </a>
                                <div class="description bg-white overflow-hidden" data-height="130">
                                    <h5 class="text-uppercase">JOBS: THE BAKER</h5>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, consequuntur iure commodi omnis at pariatur quis hic mollitia impedit error.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mix-target mixit-filter-1 col-md-4" data-order="1">
                        <div class="widget bg-none widget-pinterest">
                            <div class="widget-body bg-none padding-none">
                                <a href="http://vimeo.com/2480635" data-toggle="prettyPhoto" class="thumb overflow-hidden" data-height="150">
                                    <img src="/MelisDesign/images/video/11.jpg" alt="photo" />
                                </a>
                                <div class="description bg-white overflow-hidden" data-height="130">
                                    <h5 class="text-uppercase">Eatliz - Hey Animation</h5>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, consequuntur iure commodi omnis at pariatur quis hic mollitia impedit error.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mix-target mixit-filter-2 col-md-4" data-order="2">
                        <div class="widget bg-none widget-pinterest">
                            <div class="widget-body bg-none padding-none">
                                <a href="http://vimeo.com/28355660" data-toggle="prettyPhoto" class="thumb overflow-hidden" data-height="150">
                                    <img src="/MelisDesign/images/video/12.jpg" alt="photo" />
                                </a>
                                <div class="description bg-white overflow-hidden" data-height="130">
                                    <h5 class="text-uppercase">Back to the Start</h5>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, consequuntur iure commodi omnis at pariatur quis hic mollitia impedit error.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- // Content END -->
    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->
</div>
<!-- // Tab END -->