<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    <div id="content" class="render-form-wizards form-wizards">
        <h1 class="content-heading bg-white border-bottom">Form Wizards</h1>
        <div class="innerAll spacing-x2">
            <!-- Form Wizard / Widget Tabs / Vertical -->
            <div class="wizard wizard-design">
                <div class="widget widget-tabs widget-tabs-double widget-tabs-vertical row row-merge widget-tabs-gray">
                    <div class="col-md-3">
                        <!-- Widget heading -->
                        <div class="widget-head">
                            <ul class="nav nav-tabs">
                                <li class="nav-item active">
                                    <a href="#tab1-4" class="nav-link glyphicons user" data-bs-toggle="tab"><i></i><span class="strong">Step 1</span><span>Personal details</span></a>
                                </li>
                                <li class="nav-item">
                                    <a href="#tab2-4" class="nav-link glyphicons calculator" data-bs-toggle="tab"><i></i><span class="strong">Step 2</span><span>Billing details</span></a>
                                </li>
                                <li class="nav-item">
                                    <a href="#tab3-4" class="nav-link glyphicons credit_card" data-bs-toggle="tab"><i></i><span class="strong">Step 3</span><span>Payment</span></a>
                                </li>
                                <li class="nav-item">
                                    <a href="#tab4-4" class="nav-link glyphicons circle_ok" data-bs-toggle="tab"><i></i><span class="strong">Step 4</span><span>Confirmation</span></a>
                                </li>
                            </ul>
                        </div>
                        <!-- // Widget heading END -->
                    </div>
                    <div class="col-md-9">
                        <div class="widget-body">
                            <div class="tab-content">

                                <!-- Step 1 -->
                                <div class="tab-pane active" id="tab1-4">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <strong>Product title</strong>
                                            <p class="muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                        </div>
                                        <div class="col-md-9">
                                            <label for="inputTitle">Title</label>
                                            <input type="text" id="inputTitle" class="form-control col-md-6" value="" placeholder="Enter product title ..." />
                                            <div class="separator"></div>
                                        </div>
                                    </div>
                                </div>
                                <!-- // Step 1 END -->

                                <!-- Step 2 -->
                                <div class="tab-pane" id="tab2-4">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <strong>Description</strong>
                                            <p class="muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                        </div>
                                        <div class="col-md-9">
                                            <label for="textDescription">Description</label>
                                            <textarea id="textDescription" class="wysihtml5" style="width: 96%;" rows="5">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.</textarea>
                                        </div>
                                    </div>
                                </div>
                                <!-- // Step 2 END -->

                                <!-- Step 3 -->
                                <div class="tab-pane" id="tab3-4">
                                    <h4>Third tab</h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
                                </div>
                                <!-- // Step 3 END -->

                                <!-- Step 4 -->
                                <div class="tab-pane" id="tab4-4">
                                    <h4>Fourth tab</h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
                                </div>
                                <!-- // Step 4 END -->

                                <!-- Wizard pagination controls -->
                                <div class="margin-bottom-none float-left">
                                    <nav>
                                        <ul class="pagination">
                                            <li class="page-item primary previous first">
                                                <a class="page-link" href="#">First</a>
                                            </li>
                                            <li class="page-item last primary">
                                                <a class="page-link" href="#">Last</a>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                                <div class="margin-bottom-none float-right">
                                    <nav>
                                        <ul class="pagination">
                                            <li class="page-item primary previous">
                                                <a class="page-link" href="#">Previous</a>
                                            </li>
                                            <li class="page-item next primary">
                                                <a class="page-link" href="#">Next</a>
                                            </li>
                                            <li class="page-item next finish primary" style="display:none;">
                                                <a class="page-link" href="#">Finish</a>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                                <div class="clearfix"></div>
                                <!-- // Wizard pagination controls END -->

                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <!-- // Form Wizard / Widget Tabs / Vertical END -->



            <!-- Form Wizard / Widget Tabs / Simple -->
            <div class="wizard wizard-design">
                <div class="widget widget-tabs widget-tabs-gray">

                    <!-- Widget heading -->
                    <div class="widget-head">
                        <ul class="nav nav-tabs">
                            <li class="nav-item active">
                                <a href="#tab1-1" class="nav-link glyphicons home" data-bs-toggle="tab"><i></i>First</a>
                            </li>
                            <li class="nav-item">
                                <a href="#tab2-1" class="nav-link glyphicons umbrella" data-bs-toggle="tab"><i></i>Second</a>
                            </li>
                            <li class="nav-item">
                                <a href="#tab3-1" class="nav-link glyphicons fishes" data-bs-toggle="tab"><i></i>Third</a>
                            </li>
                            <li class="nav-item">
                                <a href="#tab4-1" class="nav-link glyphicons car" data-bs-toggle="tab"><i></i>Fourth</a>
                            </li>
                            <li class="nav-item">
                                <a href="#tab5-1" class="nav-link glyphicons leaf" data-bs-toggle="tab"><i></i>Fifth</a>
                            </li>
                            <li class="nav-item">
                                <a href="#tab6-1" class="nav-link glyphicons cup" data-bs-toggle="tab"><i></i>Sixth</a>
                            </li>
                            <li class="nav-item">
                                <a href="#tab7-1" class="nav-link glyphicons tie" data-bs-toggle="tab"><i></i>Seventh</a>
                            </li>
                        </ul>
                    </div>
                    <!-- // Widget heading END -->

                    <div class="widget-body">
                        <div class="tab-content">

                            <!-- Step 1 -->
                            <div class="tab-pane active" id="tab1-1">
                                <div class="row">
                                    <div class="col-md-3">
                                        <strong>Product title</strong>
                                        <p class="muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                    </div>
                                    <div class="col-md-9">
                                        <label for="inputTitle">Title</label>
                                        <input type="text" id="inputTitle" class="col-md-6 form-control" value="" placeholder="Enter product title ..." />
                                        <div class="separator"></div>
                                    </div>
                                </div>
                            </div>
                            <!-- // Step 1 END -->

                            <!-- Step 2 -->
                            <div class="tab-pane" id="tab2-1">
                                <div class="row">
                                    <div class="col-md-3">
                                        <strong>Description</strong>
                                        <p class="muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                    </div>
                                    <div class="col-md-9">
                                        <label for="textDescription">Description</label>
                                        <textarea id="textDescription" class="wysihtml5 form-control" style="width: 96%;" rows="5">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.</textarea>
                                    </div>
                                </div>
                            </div>
                            <!-- // Step 2 END -->

                            <!-- Step 3 -->
                            <div class="tab-pane" id="tab3-1">
                                <h4>Third tab</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
                            </div>
                            <!-- // Step 3 END -->

                            <!-- Step 4 -->
                            <div class="tab-pane" id="tab4-1">
                                <h4>Fourth tab</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
                            </div>
                            <!-- // Step 4 END -->

                            <!-- Step 5 -->
                            <div class="tab-pane" id="tab5-1">
                                <h4>Fifth tab</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
                            </div>
                            <!-- // Step 5 END -->

                            <!-- Step 6 -->
                            <div class="tab-pane" id="tab6-1">
                                <h4>Sixth tab</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
                            </div>
                            <!-- // Step 6 END -->

                            <!-- Step 7 -->
                            <div class="tab-pane" id="tab7-1">
                                <h4>Seventh tab</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
                            </div>
                            <!-- // Step 7 END -->

                        </div>

                        <!-- Wizard pagination controls -->
                        <nav>
                            <ul class="pagination margin-bottom-none">
                                <li class="page-item primary previous first">
                                    <a href="#" class="page-link no-ajaxify">First</a>
                                </li>
                                <li class="page-item primary previous">
                                    <a href="#" class="page-link no-ajaxify">Previous</a>
                                </li>
                                <li class="page-item last primary">
                                    <a href="#" class="page-link no-ajaxify">Last</a>
                                </li>
                                <li class="page-item next primary">
                                    <a href="#" class="page-link no-ajaxify">Next</a>
                                </li>
                                <li class="page-item next finish primary" style="display:none;">
                                    <a href="#" class="page-link no-ajaxify">Finish</a>
                                </li>
                            </ul>
                        </nav>
                        <!-- // Wizard pagination controls END -->

                    </div>
                </div>
            </div>
            <!-- // Form Wizard / Widget Tabs / Simple END -->



            <!-- Form Wizard / Widget Tabs / Double Style -->
            <div class="wizard wizard-design">
                <div class="widget widget-tabs widget-tabs-double widget-tabs-gray">

                    <!-- Widget heading -->
                    <div class="widget-head">
                        <ul class="nav nav-tabs">
                            <li class="nav-item active">
                                <a href="#tab1-2" class="nav-link glyphicons user" data-bs-toggle="tab"><i></i><span class="strong">Step 1</span><span>Personal details</span></a>
                            </li>
                            <li class="nav-item">
                                <a href="#tab2-2" class="nav-link glyphicons calculator" data-bs-toggle="tab"><i></i><span class="strong">Step 2</span><span>Billing details</span></a>
                            </li>
                            <li class="nav-item">
                                <a href="#tab3-2" class="nav-link glyphicons credit_card" data-bs-toggle="tab"><i></i><span class="strong">Step 3</span><span>Payment</span></a>
                            </li>
                            <li class="nav-item">
                                <a href="#tab4-2" class="nav-link glyphicons circle_ok" data-bs-toggle="tab"><i></i><span class="strong">Step 4</span><span>Confirmation</span></a>
                            </li>
                        </ul>
                    </div>
                    <!-- // Widget heading END -->

                    <div class="widget-body">
                        <div class="tab-content">

                            <!-- Step 1 -->
                            <div class="tab-pane active" id="tab1-2">
                                <div class="row">
                                    <div class="col-md-3">
                                        <strong>Product title</strong>
                                        <p class="muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                    </div>
                                    <div class="col-md-9">
                                        <label for="inputTitle">Title</label>
                                        <input type="text" id="inputTitle" class="col-md-6 form-control" value="" placeholder="Enter product title ..." />
                                        <div class="separator"></div>
                                    </div>
                                </div>
                            </div>
                            <!-- // Step 1 END -->

                            <!-- Step 2 -->
                            <div class="tab-pane" id="tab2-2">
                                <div class="row">
                                    <div class="col-md-3">
                                        <strong>Description</strong>
                                        <p class="muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                    </div>
                                    <div class="col-md-9">
                                        <label for="textDescription">Description</label>
                                        <textarea id="textDescription" class="wysihtml5 form-control" style="width: 96%;" rows="5">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.</textarea>
                                    </div>
                                </div>
                            </div>
                            <!-- // Step 2 END -->

                            <!-- Step 3 -->
                            <div class="tab-pane" id="tab3-2">
                                <h4>Third tab</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
                            </div>
                            <!-- // Step 3 END -->

                            <!-- Step 4 -->
                            <div class="tab-pane" id="tab4-2">
                                <h4>Fourth tab</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
                            </div>
                            <!-- // Step 4 END -->

                        </div>

                        <!-- Wizard pagination controls -->
                        <nav>
                            <ul class="pagination margin-bottom-none">
                                <li class="page-item primary previous first">
                                    <a href="#" class="page-link no-ajaxify">First</a>
                                </li>
                                <li class="page-item primary previous">
                                    <a href="#" class="page-link no-ajaxify">Previous</a>
                                </li>
                                <li class="page-item last primary">
                                    <a href="#" class="page-link no-ajaxify">Last</a>
                                </li>
                                <li class="page-item next primary">
                                    <a href="#" class="page-link no-ajaxify">Next</a>
                                </li>
                                <li class="page-item next finish primary" style="display:none;">
                                    <a href="#" class="page-link no-ajaxify">Finish</a>
                                </li>
                            </ul>
                        </nav>
                        <!-- // Wizard pagination controls END -->

                    </div>
                </div>
            </div>
            <!-- // Form Wizard / Widget Tabs / Double Style END -->


            <!-- Form Wizard / Widget Pills -->
            <div class="wizard wizard-design">
                <div class="widget widget-tabs widget-wizard-pills widget-tabs-gray">
                    <!-- Widget heading -->
                    <div class="widget-head widget-steps-head">
                        <ul class="nav nav-tabs">
                            <li class="status">
                                <span class="r">Step <span class="step-current">2</span> of <span class="steps-total">5</span></span><span class="r text-primary">Completed: <span class="steps-complete">1</span></span>
                            </li>
                            <li class="nav-item active no-padding">
                                <a class="nav-link" href="#tab1-3" data-bs-toggle="tab">1</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#tab2-3" data-bs-toggle="tab">2</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#tab3-3" data-bs-toggle="tab">3</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#tab4-3" data-bs-toggle="tab">4</a>
                            </li>
                        </ul>
                    </div>
                    <!-- // Widget heading END -->

                    <div class="widget-body">
                        <div class="tab-content">

                            <!-- Step 1 -->
                            <div class="tab-pane active" id="tab1-3">
                                <div class="row">
                                    <div class="col-md-3">
                                        <strong>Product title</strong>
                                        <p class="muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                    </div>
                                    <div class="col-md-9">
                                        <label for="inputTitle">Title</label>
                                        <input type="text" id="inputTitle" class="col-md-6 form-control" value="" placeholder="Enter product title ..." />
                                        <div class="separator"></div>
                                    </div>
                                </div>
                            </div>
                            <!-- // Step 1 END -->

                            <!-- Step 2 -->
                            <div class="tab-pane" id="tab2-3">
                                <div class="row">
                                    <div class="col-md-3">
                                        <strong>Description</strong>
                                        <p class="muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                    </div>
                                    <div class="col-md-9">
                                        <label for="textDescription">Description</label>
                                        <textarea id="textDescription" class="wysihtml5 form-control" style="width: 96%;" rows="5">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.</textarea>
                                    </div>
                                </div>
                            </div>
                            <!-- // Step 2 END -->

                            <!-- Step 3 -->
                            <div class="tab-pane" id="tab3-3">
                                <h4>Third tab</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
                            </div>
                            <!-- // Step 3 END -->

                            <!-- Step 4 -->
                            <div class="tab-pane" id="tab4-3">
                                <h4>Fourth tab</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
                            </div>
                            <!-- // Step 4 END -->

                        </div>

                        <!-- Wizard pagination controls -->
                        <nav>
                            <ul class="pagination margin-bottom-none float-left">
                                <li class="page-item primary previous first">
                                    <a href="#" class="page-link no-ajaxify">First</a>
                                </li>
                                <li class="page-item last primary">
                                    <a href="#" class="page-link no-ajaxify">Last</a>
                                </li>
                            </ul>
                        </nav>
                        <nav>
                            <ul class="pagination margin-bottom-none float-right">
                                <li class="page-item primary previous">
                                    <a href="#" class="page-link no-ajaxify">Previous</a>
                                </li>
                                <li class="page-item next primary">
                                    <a href="#" class="page-link no-ajaxify">Next</a>
                                </li>
                                <li class="page-item next finish primary" style="display:none;">
                                    <a href="#" class="page-link no-ajaxify">Finish</a>
                                </li>
                            </ul>
                        </nav>
                        <div class="clearfix"></div>
                        <!-- // Wizard pagination controls END -->

                    </div>
                </div>
            </div>
            <!-- // Form Wizard / Widget Pills END -->



            <!-- Form Wizard / Arrow navigation & Progress bar -->
            <div id="rootwizard" class="wizard wizard-design">

                <!-- Wizard heading -->
                <div class="wizard-head">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link" href="#tab1" data-bs-toggle="tab">First</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#tab2" data-bs-toggle="tab">Second</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#tab3" data-bs-toggle="tab">Third</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#tab4" data-bs-toggle="tab">Fourth</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#tab5" data-bs-toggle="tab">Fifth</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#tab6" data-bs-toggle="tab">Sixth</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#tab7" data-bs-toggle="tab">Seventh</a>
                        </li>
                    </ul>
                </div>
                <!-- // Wizard heading END -->

                <div class="widget">

                    <!-- Wizard Progress bar -->
                    <div class="widget-head progress" id="bar">
                        <div class="progress-bar progress-bar-primary">Step <strong class="step-current">1</strong> of <strong class="steps-total">3</strong> - <strong class="steps-percent">100%</strong>
                        </div>
                    </div>
                    <!-- // Wizard Progress bar END -->

                    <div class="widget-body">
                        <div class="tab-content">

                            <!-- Step 1 -->
                            <div class="tab-pane active" id="tab1">
                                <div class="row">
                                    <div class="col-md-3">
                                        <strong>Product title</strong>
                                        <p class="muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                    </div>
                                    <div class="col-md-9">
                                        <label for="inputTitle">Title</label>
                                        <input type="text" id="inputTitle" class="col-md-6 form-control" value="" placeholder="Enter product title ..." />
                                        <div class="separator"></div>
                                    </div>
                                </div>
                            </div>
                            <!-- // Step 1 END -->

                            <!-- Step 2 -->
                            <div class="tab-pane" id="tab2">
                                <div class="row">
                                    <div class="col-md-3">
                                        <strong>Description</strong>
                                        <p class="muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                    </div>
                                    <div class="col-md-9">
                                        <label for="textDescription">Description</label>
                                        <textarea id="textDescription" class="wysihtml5 form-control" style="width: 96%;" rows="5">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.</textarea>
                                    </div>
                                </div>
                            </div>
                            <!-- // Step 2 END -->

                            <!-- Step 3 -->
                            <div class="tab-pane" id="tab3">
                                <h4>Third tab</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
                            </div>
                            <!-- // Step 3 END -->

                            <!-- Step 4 -->
                            <div class="tab-pane" id="tab4">
                                <h4>Fourth tab</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
                            </div>
                            <!-- // Step 4 END -->

                            <!-- Step 5 -->
                            <div class="tab-pane" id="tab5">
                                <h4>Fifth tab</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
                            </div>
                            <!-- // Step 5 END -->

                            <!-- Step 6 -->
                            <div class="tab-pane" id="tab6">
                                <h4>Sixth tab</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
                            </div>
                            <!-- // Step 6 END -->

                            <!-- Step 7 -->
                            <div class="tab-pane" id="tab7">
                                <h4>Seventh tab</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
                            </div>
                            <!-- // Step 7 END -->

                        </div>

                        <!-- Wizard pagination controls -->
                        <nav>
                            <ul class="pagination margin-bottom-none">
                                <li class="page-item primary previous first">
                                    <a href="#" class="page-link no-ajaxify">First</a>
                                </li>
                                <li class="page-item primary previous">
                                    <a href="#" class="page-link no-ajaxify">Previous</a>
                                </li>
                                <li class="page-item last primary">
                                    <a href="#" class="page-link no-ajaxify">Last</a>
                                </li>
                                <li class="page-item next primary">
                                    <a href="#" class="page-link no-ajaxify">Next</a>
                                </li>
                                <li class="page-item next finish primary" style="display:none;">
                                    <a href="#" class="page-link no-ajaxify">Finish</a>
                                </li>
                            </ul>
                        </nav>
                        <!-- // Wizard pagination controls END -->

                    </div>
                </div>
            </div>
            <!-- // Form Wizard / Arrow navigation & Progress bar END -->
        </div>


    </div>
    <!-- // Content END -->

    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->