<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    <div id="content" class="render-typography">
        <h1 class="content-heading bg-white border-bottom">Typography <span>and content elements</span></h1>
        <div class="innerAll spacing-x2">

            <div class="widget">
                <div class="widget-body padding-none">
                    <div class="jumbotron bg-white margin-none center">
                        <h1 class="separator bottom">Really getting your attention!</h1>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ac dictum mauris. Vivamus blandit, odio et suscipit dictum, nisl velit rhoncus est, at elementum urna sapien ac nisi. Nulla sit amet odio vestibulum quam commodo egestas.</p>
                        <p class="margin-none innerT"><a class="btn btn-primary btn-lg">Very long and big button</a>
                        </p>
                    </div>
                </div>
            </div>


            <div class="lead center innerTB">
                <h2>Leading Heading &amp; Paragraph</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ac dictum mauris. Vivamus blandit, odio et suscipit dictum, nisl velit rhoncus est, at elementum urna sapien ac nisi. Nulla sit amet odio vestibulum quam commodo egestas.</p>
            </div>

            <!-- Widget Container Start  -->
            <div class="widget">
                <div class="widget-body">

                    <div class="row">
                        <div class="col-md-4">
                            <div class="widget widget-heading-simple widget-body-white">
                                <div class="widget-body">
                                    <div class="glyphicons glyphicon-xlarge glyphicon-top display">
                                        <i></i>
                                        <h4>Large Top Icons</h4>
                                        <p class="margin-none">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an
                                            <br> <a href="">learn more</a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="innerTB">
                                <div class="glyphicons glyphicon-xlarge glyphicon-top eyedropper glyphicon-primary">
                                    <i></i>
                                    <h4>Primary Icon &amp; No background</h4>
                                    <p class="margin-none">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an
                                        <br> <a href="">learn more</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="widget widget-heading-simple widget-body-gray">
                                <div class="widget-body">
                                    <div class="glyphicons glyphicon-xlarge glyphicon-top eyedropper">
                                        <i></i>
                                        <h4>Gray Background</h4>
                                        <p class="margin-none">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an
                                            <br> <a href="">learn more</a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <div class="widget widget-heading-simple widget-body-white">
                                <div class="widget-body">
                                    <div class="innerL">

                                        <div class="separator bottom"></div>
                                        <div class="glyphicons glyphicon-large group">
                                            <i></i>
                                            <h4>Large Left Icons</h4>
                                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an
                                                <br> <a href="">learn more</a>
                                            </p>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="innerTB">
                                <div class="separator bottom"></div>
                                <div class="glyphicons glyphicon-large iphone">
                                    <i></i>
                                    <h4>No Background</h4>
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an
                                        <br> <a href="">learn more</a>
                                    </p>
                                </div>
                                <div class="separator bottom"></div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="widget widget-heading-simple widget-body-gray">
                                <div class="widget-body">

                                    <div class="separator bottom"></div>
                                    <div class="glyphicons glyphicon-large magic group-column">
                                        <i></i>
                                        <h4>Gray Background</h4>
                                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an
                                            <br> <a href="">learn more</a>
                                        </p>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="lead separator center relativeWrap">
                        <p class="innerTB margin-none">
                            <i class="fa fa-spinner fa-spin fa-large"></i> Spinner icon when loading content ...
                        </p>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <div class="widget widget-heading-simple widget-body-white">
                                <div class="widget-head">
                                    <h4 class="heading strong text-uppercase">Left Quote</h4>
                                </div>
                                <div class="widget-body">
                                    <p><i class="fa fa-quote-left fa-4x float-left fa-muted"></i> Aliquam rutrum, sem at scelerisque tempor, nulla diam pulvinar tortor, id pulvinar massa velit eu purus. Curabitur eu fringilla diam, sed suscipit lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras iaculis enim vel odio imperdiet faucibus. Aliquam erat volutpat.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="widget widget-heading-simple widget-body-white">
                                <div class="widget-head">
                                    <h4 class="heading strong text-uppercase">Right Quote</h4>
                                </div>
                                <div class="widget-body">
                                    <p><i class="fa fa-quote-right fa-4x float-right fa-muted"></i> Aliquam rutrum, sem at scelerisque tempor, nulla diam pulvinar tortor, id pulvinar massa velit eu purus. Curabitur eu fringilla diam, sed suscipit lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras iaculis enim vel odio imperdiet faucibus. Aliquam erat volutpat.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="widget widget-heading-simple widget-body-primary">
                                <div class="widget-head">
                                    <h4 class="heading strong text-uppercase">Great Content Addon</h4>
                                </div>
                                <div class="widget-body">
                                    <p><i class="fa fa-gift fa-4x float-right text-primary"></i> Aliquam rutrum, sem at scelerisque tempor, nulla diam pulvinar tortor, id pulvinar massa velit eu purus. Curabitur eu fringilla diam, sed suscipit lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras iaculis enim vel odio imperdiet faucibus. Aliquam erat volutpat.</p>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <!-- Widget Container End  -->
            <div class="widget">
                <div class="widget-body padding-none">
                    <div class="row">
                        <div class="col-md-4 relativeWrap">
                            <div class="innerAll center">
                                <h5 class="strong text-uppercase">Headings</h5>
                                <div data-toggle="source-code">
                                    <h1>h1. Heading 1</h1>
                                    <h2>h2. Heading 2</h2>
                                    <h3>h3. Heading 3</h3>
                                    <h4>h4. Heading 4</h4>
                                    <h5>h5. Heading 5</h5>
                                    <h6>h6. Heading 6</h6>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-8 relativeWrap">
                            <div class="innerAll">
                                <h5 class="strong text-uppercase">Paragraphs, Links &amp; Text Utilities</h5>
                                <div data-toggle="source-code">
                                    <p><span class="strong">Strong text lorem ipsum dolor sit amet</span>, consectetur adipiscing elit. <a href="">Regular link morbi ac dictum mauris</a>. Odio et suscipit dictum, nisl velit rhoncus est, at elementum urna sapien ac nisi. Nulla sit amet odio vestibulum quam commodo egestas. Phasellus dolor libero, tristique non sapien id, malesuada pretium orci. Proin tellus neque, pellentesque eget eros ut, convallis mattis dolor. Aenean pretium, enim ac eleifend placerat, tortor justo tristique turpis, eget eleifend nunc lacus a nibh. Curabitur eu consectetur nulla. Duis vulputate augue nisi, eget egestas lacus tempus eget.</p>
                                    <p><span class="text-primary strong text-uppercase">Primary color & uppercase text</span> Duis pellentesque sed mauris convallis tristique. Suspendisse potenti. Donec dictum ullamcorper bibendum. Quisque tristique neque id sodales vehicula. <span class="text-underline">Underline text, dolor a porttitor auctor, nisl urna interdum ipsum</span>, vel sodales urna nunc nec neque. Curabitur rutrum gravida mi eget congue. Suspendisse tincidunt urna in quam adipiscing, ut cursus massa porttitor. Fusce viverra enim eu suscipit tristique. Etiam nec augue ut nibh varius scelerisque vitae ac mi. Nam hendrerit dui vel sagittis vestibulum. Quisque aliquet neque vitae interdum varius. Pellentesque eget nibh fermentum, vestibulum mauris scelerisque, lacinia ligula.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="lead center innerTB">
                <h2>Awesome Lists</h2>
                <p>With FLAT PLUS, you have all different kinds of lists at hand. Ordered lists, Unordered lists, Unstyled lists, Lists with Icons.</p>
            </div>

            <div class="row">
                <div class="col-md-4 ">
                    <div class="widget widget-heading-simple widget-body-white">
                        <div class="widget-head">
                            <h4 class="heading strong text-uppercase">Unstyled List</h4>
                        </div>
                        <div class="widget-body" data-toggle="source-code" class="innerAll">
                            <ul class="list-regular list-unstyled">
                                <li>Lorem ipsum dolor sit amet</li>
                                <li>Consectetur adipiscing elit</li>
                                <li>Fusce nec lacus faucibus</li>
                                <li>Malesuada tortor ac ornare</li>
                                <li>Integer mauris velit mattis
                                    <ul class="list-regular list-unstyled">
                                        <li>Quis purus sed pulvinar pulvinar</li>
                                        <li>Lacus ut laoreet sapien est</li>
                                        <li>Id placerat felis pulvinar et</li>
                                        <li>Curabitur a augue sapien donec</li>
                                    </ul>
                                </li>
                                <li>Lobortis lorem sed urna ornare</li>
                                <li>Accumsan aliquam rutrum sem at</li>
                                <li>Scelerisque tempor nulla diam</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="widget widget-heading-simple widget-body-white">
                        <div class="widget-head">
                            <h4 class="heading strong text-uppercase">Unordered List</h4>
                        </div>
                        <div class="widget-body" data-toggle="source-code" class="innerAll">
                            <ul class="list-regular">
                                <li>Lorem ipsum dolor sit amet</li>
                                <li>Consectetur adipiscing elit</li>
                                <li>Fusce nec lacus faucibus</li>
                                <li>Malesuada tortor ac ornare</li>
                                <li>Integer mauris velit mattis
                                    <ul class="list-regular">
                                        <li>Quis purus sed pulvinar pulvinar</li>
                                        <li>Lacus ut laoreet sapien est</li>
                                        <li>Id placerat felis pulvinar et</li>
                                        <li>Curabitur a augue sapien donec</li>
                                    </ul>
                                </li>
                                <li>Lobortis lorem sed urna ornare</li>
                                <li>Accumsan aliquam rutrum sem at</li>
                                <li>Scelerisque tempor nulla diam</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="widget widget-heading-simple widget-body-white">
                        <div class="widget-head">
                            <h4 class="heading strong text-uppercase">Ordered List</h4>
                        </div>
                        <div class="widget-body" data-toggle="source-code">
                            <ol>
                                <li>Lorem ipsum dolor sit amet</li>
                                <li>Consectetur adipiscing elit</li>
                                <li>Fusce nec lacus faucibus</li>
                                <li>Malesuada tortor ac ornare</li>
                                <li>Integer mauris velit mattis
                                    <ol>
                                        <li>Quis purus sed pulvinar pulvinar</li>
                                        <li>Lacus ut laoreet sapien est</li>
                                        <li>Id placerat felis pulvinar et</li>
                                        <li>Curabitur a augue sapien donec</li>
                                    </ol>
                                </li>
                                <li>Lobortis lorem sed urna ornare</li>
                                <li>Accumsan aliquam rutrum sem at</li>
                                <li>Scelerisque tempor nulla diam</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <div class="widget widget-heading-simple widget-body-white">
                        <div class="widget-head">
                            <h4 class="heading strong text-uppercase">Checkmark List</h4>
                        </div>
                        <div class="widget-body" data-toggle="source-code">
                            <ul class="fa-ul">
                                <li><span class="fa fa-li fa-check"></span> Lorem ipsum dolor sit amet</li>
                                <li><span class="fa fa-li fa-check"></span> Consectetur adipiscing elit</li>
                                <li><span class="fa fa-li fa-check"></span> Fusce nec lacus faucibus</li>
                                <li><span class="fa fa-li fa-check"></span> Malesuada tortor ac ornare</li>
                                <li><span class="fa fa-li fa-check"></span> Integer mauris velit mattis
                                    <ul class="fa-ul">
                                        <li><span class="fa fa-li fa-check"></span> Quis purus sed pulvinar pulvinar</li>
                                        <li><span class="fa fa-li fa-check"></span> Lacus ut laoreet sapien est</li>
                                        <li><span class="fa fa-li fa-check"></span> Id placerat felis pulvinar et</li>
                                        <li><span class="fa fa-li fa-check"></span> Curabitur a augue sapien donec</li>
                                    </ul>
                                </li>
                                <li><span class="fa fa-li fa-check"></span> Lobortis lorem sed urna ornare</li>
                                <li><span class="fa fa-li fa-check"></span> Accumsan aliquam rutrum sem at</li>
                                <li><span class="fa fa-li fa-check"></span> Scelerisque tempor nulla diam</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="widget widget-heading-simple widget-body-white">
                        <div class="widget-head">
                            <h4 class="heading strong text-uppercase">Crossmark List</h4>
                        </div>
                        <div class="widget-body" data-toggle="source-code">
                            <ul class="fa-ul">
                                <li><span class="fa fa-li fa-times"></span> Lorem ipsum dolor sit amet</li>
                                <li><span class="fa fa-li fa-times"></span> Consectetur adipiscing elit</li>
                                <li><span class="fa fa-li fa-times"></span> Fusce nec lacus faucibus</li>
                                <li><span class="fa fa-li fa-times"></span> Malesuada tortor ac ornare</li>
                                <li><span class="fa fa-li fa-times"></span> Integer mauris velit mattis
                                    <ul class="fa-ul">
                                        <li><span class="fa fa-li fa-times"></span> Quis purus sed pulvinar pulvinar</li>
                                        <li><span class="fa fa-li fa-times"></span> Lacus ut laoreet sapien est</li>
                                        <li><span class="fa fa-li fa-times"></span> Id placerat felis pulvinar et</li>
                                        <li><span class="fa fa-li fa-times"></span> Curabitur a augue sapien donec</li>
                                    </ul>
                                </li>
                                <li><span class="fa fa-li fa-times"></span> Lobortis lorem sed urna ornare</li>
                                <li><span class="fa fa-li fa-times"></span> Accumsan aliquam rutrum sem at</li>
                                <li><span class="fa fa-li fa-times"></span> Scelerisque tempor nulla diam</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="widget widget-heading-simple widget-body-white">
                        <div class="widget-head">
                            <h4 class="heading strong text-uppercase">Mixed List</h4>
                            <a href="" class="details float-right text-underline">See all icons</a>
                            <div class="clearfix"></div>
                        </div>
                        <div class="widget-body" data-toggle="source-code">
                            <ul class="fa-ul">
                                <li><span class="fa fa-li fa-check"></span> Lorem ipsum dolor sit amet</li>
                                <li><span class="fa fa-li fa-times"></span> Consectetur adipiscing elit</li>
                                <li><span class="fa fa-li fa-play"></span> Fusce nec lacus faucibus</li>
                                <li><span class="fa fa-li fa-gift"></span> Malesuada tortor ac ornare</li>
                                <li><span class="fa fa-li fa-facebook"></span> Integer mauris velit mattis
                                    <ul class="fa-ul">
                                        <li><span class="fa fa-li fa-twitter"></span> Quis purus sed pulvinar pulvinar</li>
                                        <li><span class="fa fa-li fa-linkedin"></span> Lacus ut laoreet sapien est</li>
                                        <li><span class="fa fa-li fa-youtube"></span> Id placerat felis pulvinar et</li>
                                        <li><span class="fa fa-li fa-stop"></span> Curabitur a augue sapien donec</li>
                                    </ul>
                                </li>
                                <li><span class="fa fa-li fa-umbrella"></span> Lobortis lorem sed urna ornare</li>
                                <li><span class="fa fa-li fa-truck"></span> Accumsan aliquam rutrum sem at</li>
                                <li><span class="fa fa-li fa-trello"></span> Scelerisque tempor nulla diam</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

        </div>


    </div>
    <!-- // Content END -->

    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->