<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    <div id="content" class="video-gallery">
        <h1 class="content-heading bg-white border-bottom">Video</h1>
        <div class="innerAll bg-white border-bottom">
            <ul class="menubar">
                <li class="active"><a>Video Gallery</a>
                </li>
            </ul>
        </div>
        <div class="innerAll spacing-x2">

            <div data-toggle="gridalicious" data-gridalicious-width="380" data-gridalicious-gutter="10">
                <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                    <div class="widget-body padding-none">
                        <a href="http://vimeo.com/59015141" rel="prettyPhoto" class="thumb">
                            <img src="/MelisDesign/images/video/1.jpg" alt="Video" />
                        </a>
                        <div class="description">
                            <h5 class="text-uppercase">Publix Sprinkler</h5>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                        </div>
                    </div>
                </div>
                <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                    <div class="widget-body padding-none">
                        <a href="http://vimeo.com/50522981" rel="prettyPhoto" class="thumb">
                            <img src="/MelisDesign/images/video/2.jpg" alt="Video" />
                        </a>
                        <div class="description">
                            <h5 class="text-uppercase">One More Beer!</h5>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, consequuntur iure commodi omnis at pariatur quis hic mollitia impedit error.</p>
                        </div>
                    </div>
                </div>
                <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                    <div class="widget-body padding-none">
                        <a href="http://vimeo.com/54932277" rel="prettyPhoto" class="thumb">
                            <img src="/MelisDesign/images/video/3.jpg" alt="Video" />
                        </a>
                        <div class="description">
                            <h5 class="text-uppercase">Spacebound: Models &amp; Props</h5>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                        </div>
                    </div>
                </div>
                <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                    <div class="widget-body padding-none">
                        <a href="http://vimeo.com/4749536" rel="prettyPhoto" class="thumb">
                            <img src="/MelisDesign/images/video/4.jpg" alt="Video" />
                        </a>
                        <div class="description">
                            <h5 class="text-uppercase">Alma</h5>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                        </div>
                    </div>
                </div>
                <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                    <div class="widget-body padding-none">
                        <a href="http://vimeo.com/33670490" rel="prettyPhoto" class="thumb">
                            <img src="/MelisDesign/images/video/5.jpg" alt="Video" />
                        </a>
                        <div class="description">
                            <h5 class="text-uppercase">The Artists</h5>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, consequuntur iure commodi omnis at pariatur quis hic mollitia impedit error.</p>
                        </div>
                    </div>
                </div>
                <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                    <div class="widget-body padding-none">
                        <a href="http://vimeo.com/8706167" rel="prettyPhoto" class="thumb">
                            <img src="/MelisDesign/images/video/6.jpg" alt="Video" />
                        </a>
                        <div class="description">
                            <h5 class="text-uppercase">Les Dangereux</h5>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, consequuntur iure commodi omnis at pariatur quis hic mollitia impedit error.</p>
                        </div>
                    </div>
                </div>
                <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                    <div class="widget-body padding-none">
                        <a href="http://vimeo.com/51478122" rel="prettyPhoto" class="thumb">
                            <img src="/MelisDesign/images/video/7.jpg" alt="Video" />
                        </a>
                        <div class="description">
                            <h5 class="text-uppercase">Dum Spiro - HD</h5>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                        </div>
                    </div>
                </div>
                <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                    <div class="widget-body padding-none">
                        <a href="http://vimeo.com/29573040" rel="prettyPhoto" class="thumb">
                            <img src="/MelisDesign/images/video/8.jpg" alt="Video" />
                        </a>
                        <div class="description">
                            <h5 class="text-uppercase">A Shadow of Blue</h5>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                        </div>
                    </div>
                </div>
                <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                    <div class="widget-body padding-none">
                        <a href="http://vimeo.com/50540814" rel="prettyPhoto" class="thumb">
                            <img src="/MelisDesign/images/video/9.jpg" alt="Video" />
                        </a>
                        <div class="description">
                            <h5 class="text-uppercase">50 Jahre Orion</h5>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                        </div>
                    </div>
                </div>
                <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                    <div class="widget-body padding-none">
                        <a href="http://vimeo.com/14989162" rel="prettyPhoto" class="thumb">
                            <img src="/MelisDesign/images/video/10.jpg" alt="Video" />
                        </a>
                        <div class="description">
                            <h5 class="text-uppercase">JOBS : THE BAKER / LES METIERS : LE BOULANGER</h5>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, consequuntur iure commodi omnis at pariatur quis hic mollitia impedit error.</p>
                        </div>
                    </div>
                </div>
                <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                    <div class="widget-body padding-none">
                        <a href="http://vimeo.com/2480635" rel="prettyPhoto" class="thumb">
                            <img src="/MelisDesign/images/video/11.jpg" alt="Video" />
                        </a>
                        <div class="description">
                            <h5 class="text-uppercase">Eatliz - Hey Animation Music Video</h5>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, consequuntur iure commodi omnis at pariatur quis hic mollitia impedit error.</p>
                        </div>
                    </div>
                </div>
                <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                    <div class="widget-body padding-none">
                        <a href="http://vimeo.com/28355660" rel="prettyPhoto" class="thumb">
                            <img src="/MelisDesign/images/video/12.jpg" alt="Video" />
                        </a>
                        <div class="description">
                            <h5 class="text-uppercase">Back to the Start</h5>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, consequuntur iure commodi omnis at pariatur quis hic mollitia impedit error.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- // Content END -->
    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->
</div>
<!-- // Tab END -->