<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">

	<div id="content">
	    <h1 class="content-heading bg-white border-bottom">Responsive Tables</h1>
	    <div class="innerAll bg-white border-bottom">
	        <ul class="menubar">
	            <li class="active"><a>Responsive Tables</a>
	            </li>
	        </ul>
	    </div>
	    <div class="innerAll spacing-x2">

	        <!-- Widget -->
	        <div class="widget">
	            <div class="widget-body center">
	                <p class="lead margin-none">Unlimited Columns &amp; Expandable Rows. Tables for Desktop, Tablet &amp; Mobile. Resize your browser to try them.</p>
	            </div>
	        </div>

	        <div class="widget">
	            <div class="widget-head">
	                <h4 class="heading">Example Using jQuery</h4>
	            </div>
	            <div class="widget-body innerAll inner-2x">

	                <!-- Table -->
	                <table class="footable table table-striped table-primary">

	                    <!-- Table heading -->
	                    <thead>
	                        <tr>
	                            <th data-class="expand">Rendering eng.</th>
	                            <th data-hide="phone,tablet">Browser</th>
	                            <th data-hide="phone,tablet">Platform(s)</th>
	                            <th data-hide="phone">Eng. vers.</th>
	                            <th>CSS grade</th>
	                        </tr>
	                    </thead>
	                    <!-- // Table heading END -->

	                    <!-- Table body -->
	                    <tbody>

	                        <!-- Table row -->
	                        <tr class="gradeX">
	                            <td>Trident</td>
	                            <td>Internet Explorer 4.0</td>
	                            <td>Win 95+</td>
	                            <td class="center">4</td>
	                            <td class="center">X</td>
	                        </tr>
	                        <!-- // Table row END -->

	                        <!-- Table row -->
	                        <tr class="gradeC">
	                            <td>Trident</td>
	                            <td>Internet Explorer 5.0</td>
	                            <td>Win 95+</td>
	                            <td class="center">5</td>
	                            <td class="center">C</td>
	                        </tr>
	                        <!-- // Table row END -->

	                        <!-- Table row -->
	                        <tr class="gradeA">
	                            <td>Trident</td>
	                            <td>Internet Explorer 5.5</td>
	                            <td>Win 95+</td>
	                            <td class="center">5.5</td>
	                            <td class="center">A</td>
	                        </tr>
	                        <!-- // Table row END -->

	                        <!-- Table row -->
	                        <tr class="gradeA">
	                            <td>Trident</td>
	                            <td>Internet Explorer 6</td>
	                            <td>Win 98+</td>
	                            <td class="center">6</td>
	                            <td class="center">A</td>
	                        </tr>
	                        <!-- // Table row END -->

	                        <!-- Table row -->
	                        <tr class="gradeA">
	                            <td>Trident</td>
	                            <td>Internet Explorer 7</td>
	                            <td>Win XP SP2+</td>
	                            <td class="center">7</td>
	                            <td class="center">A</td>
	                        </tr>
	                        <!-- // Table row END -->

	                        <!-- Table row -->
	                        <tr class="gradeA">
	                            <td>Trident</td>
	                            <td>AOL browser (AOL desktop)</td>
	                            <td>Win XP</td>
	                            <td class="center">6</td>
	                            <td class="center">A</td>
	                        </tr>
	                        <!-- // Table row END -->

	                        <!-- Table row -->
	                        <tr class="gradeA">
	                            <td>Gecko</td>
	                            <td>Firefox 1.0</td>
	                            <td>Win 98+ / OSX.2+</td>
	                            <td class="center">1.7</td>
	                            <td class="center">A</td>
	                        </tr>
	                        <!-- // Table row END -->

	                        <!-- Table row -->
	                        <tr class="gradeA">
	                            <td>Gecko</td>
	                            <td>Firefox 1.5</td>
	                            <td>Win 98+ / OSX.2+</td>
	                            <td class="center">1.8</td>
	                            <td class="center">A</td>
	                        </tr>
	                        <!-- // Table row END -->

	                        <!-- Table row -->
	                        <tr class="gradeA">
	                            <td>Gecko</td>
	                            <td>Firefox 2.0</td>
	                            <td>Win 98+ / OSX.2+</td>
	                            <td class="center">1.8</td>
	                            <td class="center">A</td>
	                        </tr>
	                        <!-- // Table row END -->

	                        <!-- Table row -->
	                        <tr class="gradeA">
	                            <td>Gecko</td>
	                            <td>Firefox 3.0</td>
	                            <td>Win 2k+ / OSX.3+</td>
	                            <td class="center">1.9</td>
	                            <td class="center">A</td>
	                        </tr>
	                        <!-- // Table row END -->

	                    </tbody>
	                    <!-- // Table body END -->

	                </table>
	                <!-- // Table END -->

	            </div>
	        </div>



	        <div class="separator bottom"></div>

	        <div class="widget">
	            <div class="widget-head">
	                <h4 class="heading">Example Using CSS Only</h4>
	            </div>
	            <div class="widget-body innerAll inner-2x">

	                <!-- Table -->
	                <table class="table table-striped table-responsive swipe-horizontal table-primary">

	                    <!-- Table heading -->
	                    <thead>
	                        <tr>
	                            <th>Rendering eng.</th>
	                            <th>Browser</th>
	                            <th>Platform(s)</th>
	                            <th>Eng. vers.</th>
	                            <th>CSS grade</th>
	                        </tr>
	                    </thead>
	                    <!-- // Table heading END -->

	                    <!-- Table body -->
	                    <tbody>

	                        <!-- Table row -->
	                        <tr class="gradeA">
	                            <td>Gecko</td>
	                            <td>Camino 1.0</td>
	                            <td>OSX.2+</td>
	                            <td class="center">1.8</td>
	                            <td class="center">A</td>
	                        </tr>
	                        <!-- // Table row END -->

	                        <!-- Table row -->
	                        <tr class="gradeA">
	                            <td>Gecko</td>
	                            <td>Camino 1.5</td>
	                            <td>OSX.3+</td>
	                            <td class="center">1.8</td>
	                            <td class="center">A</td>
	                        </tr>
	                        <!-- // Table row END -->

	                        <!-- Table row -->
	                        <tr class="gradeA">
	                            <td>Gecko</td>
	                            <td>Netscape 7.2</td>
	                            <td>Win 95+ / Mac OS 8.6-9.2</td>
	                            <td class="center">1.7</td>
	                            <td class="center">A</td>
	                        </tr>
	                        <!-- // Table row END -->

	                        <!-- Table row -->
	                        <tr class="gradeA">
	                            <td>Gecko</td>
	                            <td>Netscape Browser 8</td>
	                            <td>Win 98SE+</td>
	                            <td class="center">1.7</td>
	                            <td class="center">A</td>
	                        </tr>
	                        <!-- // Table row END -->

	                        <!-- Table row -->
	                        <tr class="gradeA">
	                            <td>Gecko</td>
	                            <td>Netscape Navigator 9</td>
	                            <td>Win 98+ / OSX.2+</td>
	                            <td class="center">1.8</td>
	                            <td class="center">A</td>
	                        </tr>
	                        <!-- // Table row END -->

	                        <!-- Table row -->
	                        <tr class="gradeA">
	                            <td>Gecko</td>
	                            <td>Mozilla 1.0</td>
	                            <td>Win 95+ / OSX.1+</td>
	                            <td class="center">1</td>
	                            <td class="center">A</td>
	                        </tr>
	                        <!-- // Table row END -->

	                        <!-- Table row -->
	                        <tr class="gradeA">
	                            <td>Gecko</td>
	                            <td>Mozilla 1.1</td>
	                            <td>Win 95+ / OSX.1+</td>
	                            <td class="center">1.1</td>
	                            <td class="center">A</td>
	                        </tr>
	                        <!-- // Table row END -->

	                        <!-- Table row -->
	                        <tr class="gradeA">
	                            <td>Gecko</td>
	                            <td>Mozilla 1.2</td>
	                            <td>Win 95+ / OSX.1+</td>
	                            <td class="center">1.2</td>
	                            <td class="center">A</td>
	                        </tr>
	                        <!-- // Table row END -->

	                        <!-- Table row -->
	                        <tr class="gradeA">
	                            <td>Gecko</td>
	                            <td>Mozilla 1.3</td>
	                            <td>Win 95+ / OSX.1+</td>
	                            <td class="center">1.3</td>
	                            <td class="center">A</td>
	                        </tr>
	                        <!-- // Table row END -->

	                        <!-- Table row -->
	                        <tr class="gradeA">
	                            <td>Gecko</td>
	                            <td>Mozilla 1.4</td>
	                            <td>Win 95+ / OSX.1+</td>
	                            <td class="center">1.4</td>
	                            <td class="center">A</td>
	                        </tr>
	                        <!-- // Table row END -->

	                    </tbody>
	                    <!-- // Table body END -->

	                </table>
	                <!-- // Table END -->

	            </div>
	        </div>



	    </div>


	</div>
	<!-- // Content END -->

	<div class="clearfix"></div>
	<!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->

<script>
	$.getScript("/MelisCore/assets/components/modules/admin/tables/responsive/assets/lib/js/footable.min.js").done(function() {
		$.getScript("/MelisCore/assets/components/modules/admin/tables/responsive/assets/custom/js/tables-responsive-footable.init.js");
	});
</script>