<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
	<div id="content">
	    <div class="heading-buttons bg-white border-bottom innerAll">
	        <h1 class="content-heading padding-none float-left">Forum</h1>
	        <div class="clearfix"></div>
	    </div>

	    <div class="innerAll spacing-x2">

	        <!-- row -->
	        <div class="row">

	            <!-- col -->
	            <div class="col-md-3">

	                <div class="widget">

	                    <h4 class="innerAll half bg-inverse margin-none">Categories</h4>
	                    <ul class="list-group list-group-1 margin-none borders-none">
	                        <li class="list-group-item animated fadeInUp"><a href="#"><span class="badge float-right badge-default hidden-md">15</span> Category #1</a>
	                        </li>
	                        <li class="list-group-item animated fadeInUp"><a href="#"><span class="badge float-right badge-default hidden-md">10</span> Second Category</a>
	                        </li>
	                        <li class="list-group-item animated fadeInUp"><a href="#"><span class="badge float-right badge-default hidden-md">10</span> Third Category</a>
	                        </li>
	                        <li class="list-group-item border-bottom-none animated fadeInUp"><a href="#"><span class="badge float-right badge-default hidden-md">10</span> Forth Category</a>
	                        </li>
	                    </ul>
	                </div>
	                <div class="widget">
	                    <h5 class="innerAll half border-bottom margin-bottom-none bg-gray">Search question</h5>
	                    <form role="form">
	                        <div class="innerAll half">
	                            <div class="form-group">
	                                <div class="input-group">
	                                    <span class="input-group-addon"><i class="fa fa-question-circle text-faded"></i></span>
	                                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Type here...">
	                                </div>
	                            </div>
	                            <div class="form-group margin-none">
	                                <div class="checkbox">
	                                    <label class="checkbox-custom">
	                                        <i class="fa fa-fw fa-square-o"></i>
	                                        <input type="checkbox" id="inlineCheckbox1" class="checkbox" value="option1" checked="checked"> Unanswered
	                                    </label>
	                                </div>
	                                <div class="checkbox margin-none">
	                                    <label class="checkbox-custom">
	                                        <i class="fa fa-fw fa-square-o"></i>
	                                        <input type="checkbox" id="inlineCheckbox2" value="option2" class="checkbox"> Answered
	                                    </label>
	                                </div>
	                            </div>
	                        </div>
	                        <div class="text-center border-top innerTB half"><a href="support_questions.html?lang=en" class="btn btn-primary"><i class="fa fa-fw fa-search"></i> Search</a>
	                        </div>
	                    </form>

	                </div>
	                <!-- // END col-separator -->

	            </div>
	            <!-- // END col -->

	            <!-- col -->
	            <div class="col-md-9">


	                <div class="widget">

	                    <div class="innerAll border-bottom half media">
	                        <a class="float-left" href="#"><img src="MelisDesign/images/people/50/2.jpg" alt="...">
	                        </a>
	                        <div class="media-body">
	                            <h3 class="margin-bottom-none padding-none">What makes Coral such an outstanding Template?
						</h3>
	                            <span class="text-muted-dark">posted by <a href="">mycompany</a> <i class="icon-time-clock fa fa-fw"></i> 12:51 AM</span>
	                        </div>
	                    </div>

	                    <div class="innerAll inner-2x">
	                        <p>Lorem ipsum dolor sit amet, consectetur <strong>adipisicing</strong> elit. Distinctio, magnam necessitatibus earum labore adipisci ab praesentium nostrum consectetur atque asperiores.</p>
	                        <p>Any ideas?</p>
	                        <p class="text-faded">Thanks,
	                            <br/><em> mycompany</em>
	                        </p>
	                    </div>

	                    <div class="border-top border-bottom text-center innerAll half bg-gray">
	                        <a href="#write" data-toggle="collapse" class="btn btn-primary strong btn-sm">Write an Answer <i class="icon-compose fa fa-fw"></i></a>
	                    </div>

	                    <div class="collapse" id="write">
	                        <div class="innerAll bg-gray inner-2x border-bottom">
	                            <textarea class="  form-control" rows="3" placeholder="Write your content here..."></textarea>
	                            <div class="text-right innerT">
	                                <button class="btn btn-success">Submit</button>
	                            </div>
	                        </div>
	                    </div>


	                    <div class="innerAll half border-bottom tickets">
	                        <ul class="media-list">
	                            <li class="media">
	                                <a class="float-left" href="#">
	                                    <img class="media-object" src="MelisDesign/images/people/50/1.jpg" alt="...">
	                                </a>
	                                <div class="media-body">
	                                    <div class="btn-group float-right btn-group-xs">
	                                        <a class="btn btn-info"><i class="fa fa-reply"></i> reply</a>
	                                        <a href="" class="btn btn-default "><i class="fa fa-flag"></i></a>
	                                    </div>
	                                    <small>posted by <a href="" class="text-primary strong"> Suzanne Marie</a> <i class="icon-time-clock fw"></i> 12:51 AM</small>
	                                    <p>Nemo dolore dolor dignissimos assumenda libero.</p>
	                                    <div class="clearfix"></div>

	                                    <div class="media">
	                                        <a class="float-left" href="#"><span class="empty-photo"><i class="icon-user-2 fa-2x"></i></span></a>
	                                        <div class="media-body">
	                                            <a href="" class="btn btn-default btn-xs float-right"><i class="fa fa-flag"></i></a>
	                                            <small>posted by <a href="">Guest</a> <i class="icon-time-clock fw"></i> 12:51 AM</small>
	                                            <p>Nemo dolore dolor dignissimos assumenda libero.</p>
	                                            <div class="clearfix"></div>
	                                            <a class="btn btn-info btn-xs"><i class="fa fa-reply"></i></a>
	                                        </div>
	                                    </div>
	                                </div>
	                            </li>
	                        </ul>

	                    </div>

	                    <div class="innerAll half border-bottom tickets">
	                        <ul class="media-list">
	                            <li class="media">
	                                <a class="float-left" href="#">
	                                    <span class="empty-photo"><i class="icon-blood-sample fa-2x"></i></span>
	                                </a>
	                                <div class="media-body">
	                                    <div class="btn-group float-right btn-group-xs">
	                                        <a class="btn btn-info"><i class="fa fa-reply"></i> reply</a>
	                                        <a href="" class="btn btn-default "><i class="fa fa-flag"></i></a>
	                                    </div>
	                                    <small>posted by <a href="" class="text-primary strong"> Mary Dawson</a> <i class="icon-time-clock fw"></i> 12:51 AM</small>
	                                    <p>Nemo dolore dolor dignissimos assumenda libero.</p>
	                                    <div class="clearfix"></div>

	                                </div>
	                            </li>
	                        </ul>

	                    </div>

	                    <div class="innerAll half border-bottom tickets">
	                        <ul class="media-list">
	                            <li class="media">
	                                <a class="float-left" href="#">
	                                    <img class="media-object" src="MelisDesign/images/people/50/3.jpg" alt="...">
	                                </a>
	                                <div class="media-body">
	                                    <div class="btn-group float-right btn-group-xs">
	                                        <a class="btn btn-info"><i class="fa fa-reply"></i> reply</a>
	                                        <a href="" class="btn btn-default "><i class="fa fa-flag"></i></a>
	                                    </div>
	                                    <small>posted by <a href="" class="text-primary strong"> Stephanie</a> <i class="icon-time-clock fw"></i> 12:51 AM</small>
	                                    <p>Nemo dolore dolor dignissimos assumenda libero.</p>
	                                    <div class="clearfix"></div>

	                                </div>
	                            </li>
	                        </ul>

	                    </div>

	                </div>
	                <!-- // END col-separator -->

	            </div>
	            <!-- // END col -->

	        </div>
	        <!-- // END row -->

	    </div>



	</div>
	<!-- // Content END -->

    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->