<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">

	<div id="content">
	    <h1 class="content-heading bg-white border-bottom">Notification <span>Plugins</span></h1>
	    <div class="innerAll spacing-x2">

	        <!-- Top Notyfy Options & Styles Live Demo -->
	        <div class="widget widget-inverse">

	            <!-- Widget heading -->
	            <div class="widget-head">
	                <h4 class="heading">Top notifications</h4>
	            </div>
	            <!-- // Widget heading END -->

	            <div class="widget-body center">
	                <span class="btn btn-default btn-regular" data-layout="top" data-type="alert" data-toggle="notyfy">Alert</span>
	                <span class="btn btn-success btn-regular" data-layout="top" data-type="success" data-toggle="notyfy">Success</span>
	                <span class="btn btn-danger btn-regular" data-layout="top" data-type="error" data-toggle="notyfy">Danger</span>
	                <span class="btn btn-warning" data-layout="top" data-type="warning" data-toggle="notyfy">Warning</span>
	                <span class="btn btn-info btn-regular" data-layout="top" data-type="information" data-toggle="notyfy">Information</span>
	                <span class="btn btn-inverse" data-layout="top" data-type="confirm" data-toggle="notyfy">Confirm</span>


	            </div>
	        </div>
	        <!-- // Top Notyfy Options & Styles Live Demo END -->

	        <div class="row">

	            <!-- Left Notyfy Options Live Demo -->
	            <div class="col-md-4">
	                <div class="widget widget-inverse">

	                    <!-- Widget heading -->
	                    <div class="widget-head">
	                        <h4 class="heading">Left</h4>
	                    </div>
	                    <!-- // Widget heading END -->

	                    <div class="widget-body center">
	                        <span class="btn btn-default" data-layout="topLeft" data-type="primary" data-toggle="notyfy">Top</span>
	                        <span class="btn btn-default" data-layout="centerLeft" data-type="primary" data-toggle="notyfy">Center</span>
	                        <span class="btn btn-default" data-layout="bottomLeft" data-type="primary" data-toggle="notyfy">Bottom</span>


	                    </div>
	                </div>
	            </div>
	            <!-- // Left Notyfy Options Live Demo END -->

	            <!-- Center Notyfy Options Live Demo -->
	            <div class="col-md-4">
	                <div class="widget widget-inverse">

	                    <!-- Widget heading -->
	                    <div class="widget-head">
	                        <h4 class="heading">Center</h4>
	                    </div>
	                    <!-- // Widget heading END -->

	                    <div class="widget-body center">
	                        <span class="btn btn-default btn-block" data-layout="center" data-type="primary" data-toggle="notyfy">Center notification</span>


	                    </div>
	                </div>
	            </div>
	            <!-- // Center Notyfy Options Live Demo END -->

	            <!-- Right Notyfy Options Live Demo -->
	            <div class="col-md-4">
	                <div class="widget widget-inverse">

	                    <!-- Widget heading -->
	                    <div class="widget-head">
	                        <h4 class="heading">Right</h4>
	                    </div>
	                    <!-- // Widget heading END -->

	                    <div class="widget-body center">
	                        <span class="btn btn-default" data-layout="topRight" data-type="primary" data-toggle="notyfy">Top</span>
	                        <span class="btn btn-default" data-layout="centerRight" data-type="primary" data-toggle="notyfy">Center</span>
	                        <span class="btn btn-default" data-layout="bottomRight" data-type="primary" data-toggle="notyfy">Bottom</span>


	                    </div>
	                </div>
	            </div>
	            <!-- // Right Notyfy Options Live Demo END -->

	        </div>

	        <h3>Gritter <span>Notifications plugin</span></h3>
	        <div class="row">

	            <!-- Color Options Column -->
	            <div class="col-md-4">
	                <div class="widget widget-inverse">

	                    <!-- Widget heading -->
	                    <div class="widget-head">
	                        <h4 class="heading">Color options</h4>
	                    </div>
	                    <!-- // Widget heading END -->

	                    <div class="widget-body center">
	                        <span class="gritter-add-white btn btn-default btn-block">Light</span>
	                        <span class="gritter-add-regular btn btn-inverse btn-block">Dark</span>
	                        <span class="gritter-add-primary btn btn-primary btn-block">Primary</span>


	                    </div>
	                </div>
	            </div>
	            <!-- // Color Options Column END -->

	            <!-- Other Examples Column -->
	            <div class="col-md-8">
	                <div class="widget widget-inverse">

	                    <!-- Widget heading -->
	                    <div class="widget-head">
	                        <h4 class="heading">Other examples</h4>
	                    </div>
	                    <!-- // Widget heading END -->

	                    <div class="widget-body center">
	                        <span class="gritter-add-sticky btn btn-default btn-block btn-icon-stacked glyphicons right_arrow"><i></i><strong>Add sticky notification</strong><span>Has to be manually removed</span></span>
	                        <span class="gritter-add-without-image btn btn-default btn-block btn-icon glyphicons right_arrow"><i></i>Add notification without image</span>
	                        <span class="gritter-add-white btn btn-default btn-block btn-icon-stacked glyphicons right_arrow"><i></i><strong>Add white notification</strong><span>Has a "gritter-light" class applied</span></span>
	                        <span class="gritter-add-max btn btn-default btn-block btn-icon-stacked glyphicons right_arrow"><i></i><strong>Add notification with max. of 3</strong><span>Only if there are &lt;= 3 messages already on screen</span></span>


	                    </div>
	                </div>
	            </div>
	            <!-- // Other Examples Column END -->

	        </div>

	    </div>


	</div>
	<!-- // Content END -->

    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->