<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    <div id="content" class="render-carousel">
        <h1 class="content-heading bg-white border-bottom">Carousels <span>Component for cycling through elements</span></h1>
        <div class="innerAll bg-white border-bottom">
            <ul class="menubar">
                <li class="active"><a>Carousels</a>
                </li>
            </ul>
        </div>
        <div class="innerAll spacing-x2">
            <div class="row">
                <div class="col-md-6">
                    <div id="carouselBig" class="carousel slide" data-ride="carousel">
                        <!-- // Indicators END -->
                        <!-- Items -->
                        <div class="carousel-inner">
                            <!-- Item -->
                            <div class="carousel-item active">
                                <img src="/MelisDesign/images/gallery-2/1.jpg" alt="" class="img-fluid" />
                                <div class="carousel-caption d-none d-md-block">
                                    <h4>Thumbnail heading</h4>
                                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                                </div>
                            </div>
                            <!-- // Item END -->
                            <!-- Item -->
                            <div class="carousel-item">
                                <img src="/MelisDesign/images/gallery-2/2.jpg" alt="" class="img-fluid" />
                                <div class="carousel-caption d-none d-md-block">
                                    <h4>Thumbnail heading</h4>
                                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                                </div>
                            </div>
                            <!-- // Item END -->
                            <!-- Item -->
                            <div class="carousel-item">
                                <img src="/MelisDesign/images/gallery-2/3.jpg" alt="" class="img-fluid" />
                                <div class="carousel-caption d-none d-md-block">
                                    <h4>Thumbnail heading</h4>
                                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                                </div>
                            </div>
                            <!-- // Item END -->
                            <!-- Item -->
                            <div class="carousel-item">
                                <img src="/MelisDesign/images/gallery-2/4.jpg" alt="" class="img-fluid" />
                                <div class="carousel-caption d-none d-md-block">
                                    <h4>Thumbnail heading</h4>
                                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                                </div>
                            </div>
                            <!-- // Item END -->
                            <!-- Item -->
                            <div class="carousel-item">
                                <img src="/MelisDesign/images/gallery-2/5.jpg" alt="" class="img-fluid" />
                                <div class="carousel-caption d-none d-md-block">
                                    <h4>Thumbnail heading</h4>
                                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                                </div>
                            </div>
                            <!-- // Item END -->
                        </div>
                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                            <li data-target="#carouselBig" data-slide-to="0" class="active"></li>
                            <li data-target="#carouselBig" data-slide-to="1"></li>
                            <li data-target="#carouselBig" data-slide-to="2"></li>
                            <li data-target="#carouselBig" data-slide-to="3"></li>
                            <li data-target="#carouselBig" data-slide-to="4"></li>
                        </ol>
                        <!-- // Items END -->
                        <!-- Navigation -->
                        <!-- <a class="left carousel-control carousel-control-prev" href="#carousel-1" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control carousel-control-next" href="#carousel-1" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a> -->
                        <!-- // Navigation END -->
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="carousel slide" data-ride="carousel" id="myCarousel">
                        <div class="carousel-inner">
                            <!-- Item -->
                            <div class="carousel-item active">
                                <div class="row">
                                    <div class="col-5 relativeWrap">
                                        <div class="carousel-caption d-none d-md-block">
                                            <h4>Get this item now!</h4>
                                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut.
                                                <br/> <a href="" class="separator top" target="_blank">Buy FLAT PLUS!</a>
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-7">
                                        <img src="/MelisDesign/images/gallery-2/6.jpg" alt="" class="img-fluid" />
                                    </div>
                                </div>
                            </div>
                            <!-- // Item END -->
                            <!-- Item -->
                            <div class="carousel-item">
                                <div class="row">
                                    <div class="col-5 relativeWrap">
                                        <div class="carousel-caption d-none d-md-block">
                                            <h4>Get this item now!</h4>
                                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut.
                                                <br/> <a href="" class="separator top" target="_blank">Buy FLAT PLUS!</a>
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-7">
                                        <img src="/MelisDesign/images/gallery-2/7.jpg" alt="" class="img-fluid" />
                                    </div>
                                </div>
                            </div>
                            <!-- // Item END -->
                            <!-- Item -->
                            <div class="carousel-item">
                                <div class="row">
                                    <div class="col-5 relativeWrap">
                                        <div class="carousel-caption d-none d-md-block">
                                            <h4>Get this item now!</h4>
                                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut.
                                                <br/> <a href="" class="separator top" target="_blank">Buy FLAT PLUS!</a>
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-7">
                                        <img src="/MelisDesign/images/gallery-2/8.jpg" alt="" class="img-fluid" />
                                    </div>
                                </div>
                            </div>
                            <!-- // Item END -->
                        </div>
                        <ol class="carousel-indicators">
                            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                            <li data-target="#myCarousel" data-slide-to="1"></li>
                            <li data-target="#myCarousel" data-slide-to="2"></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- // Content END -->
    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->
</div>
<!-- // Tab END -->