<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    <div id="content">
        <div class="heading-buttons bg-white border-bottom innerAll">
            <h1 class="content-heading padding-none pull-left">Forum</h1>
            <div class="clearfix"></div>
        </div>

        <div class="innerAll spacing-x2">
            <!-- Search Bar -->
            <div class="input-group innerB">
                <input type="text" class="form-control" placeholder="Search this forum...">
                <span class="input-group-btn">
            		<button class="btn btn-primary rounded-none" type="button"><i class="fa fa-search"></i></button>
          		</span>
            </div>
            <!-- End Search Bar -->


            <!-- row -->
            <div class="row">


                <div class="col-md-9">
                    <div class="widget no-bg">

                        <!-- Category Heading -->
                        <div class="innerAll half bg-gray border-bottom">
                            <a href="#" class="btn btn-xs btn-inverse pull-right"><i class="fa fa-plus fa-fw"></i> New Topic</a>
                            <h4 class=" margin-bottom-none">General Discussion</h4>
                            <div class="clearfix"></div>
                        </div>
                        <!-- End Category Heading -->

                        <!-- Category Listing -->
                        <div class="row innerAll  half border-bottom row-hover">
                            <div class="col-sm-6 col-xs-8">
                                <ul class="media-list margin-none">
                                    <li class="media">
                                        <a class="pull-left innerAll half " href="#">
                                            <span class="empty-photo"><i class="fa fa-folder fa-2x text-muted"></i></span>
                                        </a>
                                        <div class="media-body">
                                            <div class="innerAll half">
                                                <h4 class="margin-none"><a href="" class="media-heading strong text-primary">Getting Started</a></h4>
                                                <div class="clearfix"></div>
                                                <small class="margin-none">Topic information goes here</small>
                                            </div>

                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-sm-3 col-xs-4">
                                <div class="text-center">
                                    <p class="lead strong margin-bottom-none">101</p>
                                    <span class="text-muted">POSTS</span>
                                </div>
                            </div>
                            <div class="col-sm-3 col-xs-hidden">
                                <div class="innerAll half">
                                    <div class="media">
                                        <a href="" class="pull-left">
                                            <img src="MelisDesign/images/people/35/2.jpg" class="media-object" />
                                        </a>
                                        <div class="media-body">
                                            <a href="" class="text-small">mosaicpro</a>
                                            <div class="clearfix"></div>
                                            <small>last replied</small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row innerAll  half border-bottom row-hover">
                            <div class="col-sm-6 col-xs-8">
                                <ul class="media-list margin-none">
                                    <li class="media">
                                        <a class="pull-left innerAll half " href="#">
                                            <span class="empty-photo"><i class="fa fa-folder fa-2x text-muted"></i></span>
                                        </a>
                                        <div class="media-body">
                                            <div class="innerAll half">
                                                <h4 class="margin-none"><a href="" class="media-heading strong text-primary">Requirements</a></h4>
                                                <div class="clearfix"></div>
                                                <small class="margin-none">Topic information goes here</small>
                                            </div>

                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-sm-3 col-xs-4">
                                <div class="text-center">
                                    <p class="lead strong margin-bottom-none">212</p>
                                    <span class="text-muted">POSTS</span>
                                </div>
                            </div>
                            <div class="col-sm-3 col-xs-hidden">
                                <div class="innerAll half">
                                    <div class="media">
                                        <a href="" class="pull-left">
                                            <img src="MelisDesign/images/people/35/3.jpg" class="media-object" />
                                        </a>
                                        <div class="media-body">
                                            <a href="" class="text-small">mosaicpro</a>
                                            <div class="clearfix"></div>
                                            <small>last replied</small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row innerAll  half border-bottom row-hover">
                            <div class="col-sm-6 col-xs-8">
                                <ul class="media-list margin-none">
                                    <li class="media">
                                        <a class="pull-left innerAll half " href="#">
                                            <span class="empty-photo"><i class="fa fa-folder fa-2x text-muted"></i></span>
                                        </a>
                                        <div class="media-body">
                                            <div class="innerAll half">
                                                <h4 class="margin-none"><a href="" class="media-heading strong text-primary">Common Questions</a></h4>
                                                <div class="clearfix"></div>
                                                <small class="margin-none">Topic information goes here</small>
                                            </div>

                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-sm-3 col-xs-4">
                                <div class="text-center">
                                    <p class="lead strong margin-bottom-none">323</p>
                                    <span class="text-muted">POSTS</span>
                                </div>
                            </div>
                            <div class="col-sm-3 col-xs-hidden">
                                <div class="innerAll half">
                                    <div class="media">
                                        <a href="" class="pull-left">
                                            <img src="MelisDesign/images/people/35/4.jpg" class="media-object" />
                                        </a>
                                        <div class="media-body">
                                            <a href="" class="text-small">mosaicpro</a>
                                            <div class="clearfix"></div>
                                            <small>last replied</small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- // END Category Listing -->


                    </div>
                    <div class="widget no-bg">

                        <!-- Category Heading -->
                        <div class="innerAll half bg-gray border-bottom">
                            <a href="#" class="btn btn-xs btn-inverse pull-right"><i class="fa fa-plus fa-fw"></i> New Topic</a>
                            <h4 class=" margin-bottom-none">Customization</h4>
                            <div class="clearfix"></div>
                        </div>
                        <!-- End Category Heading -->
                        <!-- Category Listing -->
                        <div class="row innerAll half border-bottom row-hover">
                            <div class="col-sm-6 col-xs-8">
                                <ul class="media-list margin-none">
                                    <li class="media">
                                        <a class="pull-left innerAll half" href="#">
                                            <span class="empty-photo"><i class="fa fa-folder fa-2x text-muted"></i></span>
                                        </a>
                                        <div class="media-body">
                                            <div class="innerAll half">
                                                <h4 class="margin-none"><a href="" class="media-heading strong text-primary">Changing Skin of Coral</a></h4>
                                                <div class="clearfix"></div>
                                                <small class="margin-none">Topic information goes here</small>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-sm-3 col-xs-4">
                                <div class="text-center">
                                    <p class="lead strong margin-bottom-none">101</p>
                                    <span class="text-muted">POSTS</span>
                                </div>
                            </div>
                            <div class="col-sm-3 col-xs-hidden">
                                <div class="innerAll half">
                                    <div class="media">
                                        <a href="" class="pull-left">
                                            <img src="MelisDesign/images/people/35/2.jpg" class="media-object" />
                                        </a>
                                        <div class="media-body">
                                            <a href="" class="text-small">mosaicpro</a>
                                            <div class="clearfix"></div>
                                            <small>last replied</small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row innerAll half border-bottom row-hover">
                            <div class="col-sm-6 col-xs-8">
                                <ul class="media-list margin-none">
                                    <li class="media">
                                        <a class="pull-left innerAll half" href="#">
                                            <span class="empty-photo"><i class="fa fa-folder fa-2x text-muted"></i></span>
                                        </a>
                                        <div class="media-body">
                                            <div class="innerAll half">
                                                <h4 class="margin-none"><a href="" class="media-heading strong text-primary">Sidebar Type</a></h4>
                                                <div class="clearfix"></div>
                                                <small class="margin-none">Topic information goes here</small>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-sm-3 col-xs-4">
                                <div class="text-center">
                                    <p class="lead strong margin-bottom-none">212</p>
                                    <span class="text-muted">POSTS</span>
                                </div>
                            </div>
                            <div class="col-sm-3 col-xs-hidden">
                                <div class="innerAll half">
                                    <div class="media">
                                        <a href="" class="pull-left">
                                            <img src="MelisDesign/images/people/35/3.jpg" class="media-object" />
                                        </a>
                                        <div class="media-body">
                                            <a href="" class="text-small">mosaicpro</a>
                                            <div class="clearfix"></div>
                                            <small>last replied</small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row innerAll half border-bottom row-hover">
                            <div class="col-sm-6 col-xs-8">
                                <ul class="media-list margin-none">
                                    <li class="media">
                                        <a class="pull-left innerAll half" href="#">
                                            <span class="empty-photo"><i class="fa fa-folder fa-2x text-muted"></i></span>
                                        </a>
                                        <div class="media-body">
                                            <div class="innerAll half">
                                                <h4 class="margin-none"><a href="" class="media-heading strong text-primary">Common</a></h4>
                                                <div class="clearfix"></div>
                                                <small class="margin-none">Topic information goes here</small>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-sm-3 col-xs-4">
                                <div class="text-center">
                                    <p class="lead strong margin-bottom-none">323</p>
                                    <span class="text-muted">POSTS</span>
                                </div>
                            </div>
                            <div class="col-sm-3 col-xs-hidden">
                                <div class="innerAll half">
                                    <div class="media">
                                        <a href="" class="pull-left">
                                            <img src="MelisDesign/images/people/35/4.jpg" class="media-object" />
                                        </a>
                                        <div class="media-body">
                                            <a href="" class="text-small">mosaicpro</a>
                                            <div class="clearfix"></div>
                                            <small>last replied</small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row innerAll half border-bottom row-hover">
                            <div class="col-sm-6 col-xs-8">
                                <ul class="media-list margin-none">
                                    <li class="media">
                                        <a class="pull-left innerAll half" href="#">
                                            <span class="empty-photo"><i class="fa fa-folder fa-2x text-muted"></i></span>
                                        </a>
                                        <div class="media-body">
                                            <div class="innerAll half">
                                                <h4 class="margin-none"><a href="" class="media-heading strong text-primary">Including New Elements </a></h4>
                                                <div class="clearfix"></div>
                                                <small class="margin-none">Topic information goes here</small>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-sm-3 col-xs-4">
                                <div class="text-center">
                                    <p class="lead strong margin-bottom-none">434</p>
                                    <span class="text-muted">POSTS</span>
                                </div>
                            </div>
                            <div class="col-sm-3 col-xs-hidden">
                                <div class="innerAll half">
                                    <div class="media">
                                        <a href="" class="pull-left">
                                            <img src="MelisDesign/images/people/35/5.jpg" class="media-object" />
                                        </a>
                                        <div class="media-body">
                                            <a href="" class="text-small">mosaicpro</a>
                                            <div class="clearfix"></div>
                                            <small>last replied</small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- // END Category Listing -->

                    </div>
                    <!-- // END col-separator -->
                </div>
                <!-- // END col -->

                <!-- col -->
                <div class="col-md-3">

                    <!-- col-separator -->
                    <div class="widget no-bg">

                        <!-- Heading -->
                        <h5 class="innerAll half margin-bottom-none bg-primary"><i class="fa fa-user"></i> Recent Members</h5>

                        <!-- Listing -->
                        <div class="row row-hover innerAll half border-bottom">
                            <div class="media">
                                <a href="" class="pull-left innerAll half">
                                    <i class="fa fa-user fa-2x text-muted innerL"></i>
                                </a>
                                <div class="media-body">
                                    <a href="" class="text-small strong text-primary">mosaicpro</a>
                                    <small class="clearfix">on 16 Jan 2014</small>
                                </div>
                            </div>
                        </div>
                        <div class="row row-hover innerAll half border-bottom">
                            <div class="media">
                                <a href="" class="pull-left innerAll half">
                                    <i class="fa fa-user fa-2x text-muted innerL"></i>
                                </a>
                                <div class="media-body">
                                    <a href="" class="text-small strong text-primary">mosaicpro</a>
                                    <small class="clearfix">on 16 Jan 2014</small>
                                </div>
                            </div>
                        </div>
                        <div class="row row-hover innerAll half border-bottom">
                            <div class="media">
                                <a href="" class="pull-left innerAll half">
                                    <i class="fa fa-user fa-2x text-muted innerL"></i>
                                </a>
                                <div class="media-body">
                                    <a href="" class="text-small strong text-primary">mosaicpro</a>
                                    <small class="clearfix">on 16 Jan 2014</small>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="widget">

                        <!-- Heading -->
                        <h5 class="innerAll half margin-bottom-none bg-primary"><i class="fa fa-refresh"></i> Latest Posts</h5>

                        <!-- Listing -->

                        <div class="row-hover innerAll half border-bottom">
                            <h5 class=" margin-none"><a href="#" class="text-inverse">How do you guys change navbar into white?</a></h5>
                            <small class="text-center text-inverse text-muted"><i class="fa fa-fw fa-user "></i> by Adrian | <i class="fa fa-fw fa-calendar "></i> 17/01/2014</small>
                        </div>


                        <div class="row-hover innerAll half border-bottom">
                            <h5 class=" margin-none"><a href="#" class="text-inverse">How do you guys change navbar into white?</a></h5>
                            <small class="text-center text-inverse text-muted"><i class="fa fa-fw fa-user "></i> by Adrian | <i class="fa fa-fw fa-calendar "></i> 17/01/2014</small>
                        </div>


                        <div class="row-hover innerAll half border-bottom">
                            <h5 class=" margin-none"><a href="#" class="text-inverse">How do you guys change navbar into white?</a></h5>
                            <small class="text-center text-inverse text-muted"><i class="fa fa-fw fa-user "></i> by Adrian | <i class="fa fa-fw fa-calendar "></i> 17/01/2014</small>
                        </div>


                        <div class="row-hover innerAll half border-bottom">
                            <h5 class=" margin-none"><a href="#" class="text-inverse">How do you guys change navbar into white?</a></h5>
                            <small class="text-center text-inverse text-muted"><i class="fa fa-fw fa-user "></i> by Adrian | <i class="fa fa-fw fa-calendar "></i> 17/01/2014</small>
                        </div>

                        <!-- // END Listing -->


                    </div>
                </div>
                <!-- // END col -->



            </div>
            <!-- // END row -->
        </div>




    </div>
    <!-- // Content END -->

    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->
</div>
<!-- // Tab END -->