<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;
?>
<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    <div id="content" class="render-charts">
        <h1 class="content-heading bg-white border-bottom">Charts</h1>
        <div class="innerAll spacing-x2">

            <div class="row">
                <div class="col-md-6">

                    <!-- Widget -->
                    <div class="widget widget-inverse">
                        <!-- Widget heading -->
                        <div class="widget-head">
                            <h4 class="heading">Simple chart</h4>
                        </div>
                        <!-- // Widget heading END -->
                        <div class="widget-body">
                            <!-- Simple Chart -->
                            <div id="chart_simple_02" class="flotchart-holder"></div>
                        </div>
                    </div>
                    <!-- // Widget END -->

                </div>
                <div class="col-md-6">

                    <!-- Widget -->
                    <div class="widget widget-inverse">

                        <!-- Widget heading -->
                        <div class="widget-head">
                            <h4 class="heading">Lines chart with fill & without points</h4>
                        </div>
                        <!-- // Widget heading END -->

                        <div class="widget-body">
                            <!-- Chart with lines and fill with no points -->
                            <div id="chart_lines_fill_nopoints" class="flotchart-holder"></div>
                        </div>
                    </div>
                    <!-- // Widget END -->

                </div>
            </div>

            <div class="row">
                <div class="col-md-6">

                    <!-- Widget -->
                    <div class="widget widget-inverse">

                        <!-- Widget heading -->
                        <div class="widget-head">
                            <h4 class="heading">Ordered bars chart</h4>
                        </div>
                        <!-- // Widget heading END -->

                        <div class="widget-body">
                            <!-- Ordered bars Chart -->
                            <div id="chart_ordered_bars" class="flotchart-holder"></div>
                        </div>
                    </div>
                    <!-- // Widget END -->

                </div>
                <div class="col-md-6">

                    <!-- Widget -->
                    <div class="widget widget-inverse">

                        <!-- Widget heading -->
                        <div class="widget-head">
                            <h4 class="heading">Stacked bars chart</h4>
                        </div>
                        <!-- // Widget heading END -->

                        <div class="widget-body">
                            <!-- Stacked bars Chart -->
                            <div id="chart_stacked_bars" class="flotchart-holder"></div>
                        </div>
                    </div>
                    <!-- // Widget END -->

                </div>
            </div>

            <!-- Widget -->
            <div class="widget widget-inverse">

                <!-- Widget heading -->
                <div class="widget-head">
                    <h4 class="heading">Donut chart</h4>
                </div>
                <!-- // Widget heading END -->

                <div class="widget-body">
                    <!-- Donut Chart -->
                    <div id="chart_donut" class="flotchart-holder flotchart-fullwidth"></div>
                </div>
            </div>
            <!-- // Widget END -->

            <!-- Widget -->
            <div class="widget widget-inverse">

                <!-- Widget heading -->
                <div class="widget-head">
                    <h4 class="heading">Pie chart</h4>
                </div>
                <!-- // Widget heading END -->

                <div class="widget-body">
                    <!-- Pie Chart -->
                    <div id="chart_pie" class="flotchart-holder flotchart-fullwidth"></div>
                </div>
            </div>
            <!-- // Widget END -->

            <!-- Widget -->
            <div class="widget widget-inverse">

                <!-- Widget heading -->
                <div class="widget-head">
                    <h4 class="heading">Horizontal bars chart</h4>
                </div>
                <!-- // Widget heading END -->

                <div class="widget-body">
                    <!-- Horizontal Bars Chart -->
                    <div id="chart_horizontal_bars" class="flotchart-holder flotchart-fullwidth"></div>
                </div>
            </div>
            <!-- // Widget END -->

            <!-- Widget -->
            <div class="widget widget-inverse">

                <!-- Widget heading -->
                <div class="widget-head">
                    <h4 class="heading">Auto updating chart</h4>
                </div>
                <!-- // Widget heading END -->

                <div class="widget-body">
                    <!-- Live Chart -->
                    <div id="chart_live" class="flotchart-holder flotchart-fullwidth"></div>
                </div>
            </div>
            <!-- // Widget END -->
        </div>
    </div>
    <!-- // Content END -->
    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->
</div>
<!-- // Tab END -->