<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">

	<div id="content" class="tabs">
	    <h1 class="content-heading bg-white border-bottom">Tabs <span>7 awesome styles</span></h1>

	    <div class="innerAll spacing-x2">

	        <!-- Tabs -->
	        <div class="relativeWrap">
	            <div class="widget widget-tabs widget-tabs-double-2 widget-tabs-responsive">

	                <!-- Tabs Heading -->
	                <div class="widget-head">
	                    <ul class="nav nav-tabs">
	                        <li class="nav-item active">
								<a class="nav-link glyphicons list" href="#tabAll" data-toggle="tab"><i></i><span>All topics</span></a>
	                        </li>
	                        <li class="nav-item">
								<a class="nav-link glyphicons user" href="#tabAccount" data-toggle="tab"><i></i><span>Account</span></a>
	                        </li>
	                        <li class="nav-item">
								<a class="nav-link glyphicons credit_card" href="#tabPayments" data-toggle="tab"><i></i><span>Payments</span></a>
	                        </li>
	                        <li class="nav-item">
								<a class="nav-link glyphicons cogwheel" href="#tabSupport" data-toggle="tab"><i></i><span>Technical Support</span></a>
	                        </li>
	                        <li class="nav-item">
								<a class="nav-link glyphicons snowflake" href="#tabFeatures" data-toggle="tab"><i></i><span>Features</span></a>
	                        </li>
	                    </ul>
	                </div>
	                <!-- // Tabs Heading END -->

	                <div class="widget-body">
	                    <div class="tab-content">

	                        <!-- Tab content -->
	                        <div id="tabAll" class="tab-pane active widget-body-regular">
	                            <h5>All topics tab content</h5>

	                            <p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec id eros a orci adipiscing accumsan id eget sem. Etiam sit amet neque ligula, ac hendrerit metus. Phasellus convallis nulla nec leo dapibus sed feugiat felis feugiat. Nulla facilisi. Mauris quis tortor eu eros posuere tristique. In turpis leo, iaculis eget tincidunt in, gravida sit amet diam. Vivamus viverra, nisl vitae consectetur volutpat, ipsum risus tempor augue, in convallis leo massa in sem. Maecenas in urna quis purus pulvinar posuere. Fusce blandit viverra placerat. Fusce elementum turpis sed velit blandit elementum.</p>
	                        </div>
	                        <!-- // Tab content END -->

	                        <!-- Tab content -->
	                        <div id="tabAccount" class="tab-pane widget-body-regular">
	                            <h5>Account tab content</h5>

	                            <p>Donec at nunc dui. Integer eget sem sit amet arcu bibendum elementum vel sit amet risus. Fusce libero lorem, fermentum vitae lacinia dapibus, vestibulum ac enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum accumsan risus sed lorem tincidunt eget faucibus sapien tempor. Proin ac feugiat dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.</p>
	                        </div>
	                        <!-- // Tab content END -->

	                        <!-- Tab content -->
	                        <div id="tabPayments" class="tab-pane widget-body-regular">
	                            <h5>Payments tab content</h5>

	                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ante est, tempor ut posuere nec, venenatis sed arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis in purus ut mauris sodales sollicitudin. Mauris cursus imperdiet dignissim. Phasellus risus felis, rutrum in laoreet vel, posuere vel dolor. Sed venenatis vehicula tempus. Nam at rutrum enim. Sed massa quam, mattis in viverra ut, ullamcorper et massa. Phasellus sapien diam, faucibus ac tempor a, condimentum quis est. Donec nec velit ante, vel mattis metus. Ut nec libero diam, id auctor sapien. Suspendisse eget lorem ante, in fringilla dui. In hac habitasse platea dictumst.
	                            </p>
	                        </div>
	                        <!-- // Tab content END -->

	                        <!-- Tab content -->
	                        <div id="tabSupport" class="tab-pane widget-body-regular">
	                            <h5>Support tab content</h5>

	                            <p>Integer porttitor, enim eu egestas ullamcorper, odio mauris semper quam, in facilisis dui ligula eget ligula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas dolor leo, consectetur nec tristique pretium, ornare quis purus. Nullam pulvinar, enim eu molestie venenatis, turpis nisl vehicula eros, et ultricies risus urna sed diam. Suspendisse potenti. Nullam tincidunt tellus nisi. Aenean felis eros, congue vitae hendrerit id, mattis quis mi.</p>
	                        </div>
	                        <!-- // Tab content END -->

	                        <!-- Tab content -->
	                        <div id="tabFeatures" class="tab-pane widget-body-regular">
	                            <h5>Features tab content</h5>

	                            <p>Nunc aliquet lacus laoreet odio consectetur tempus. In id nisl diam, congue vehicula sapien. Nulla facilisi. Donec sagittis cursus sollicitudin. Aenean leo tellus, eleifend quis facilisis vel, tempus ac elit. Nam eget turpis nec erat vestibulum fringilla. Donec et felis ipsum. Fusce feugiat ultricies lacus a ultrices. Nunc ultrices, orci ut convallis pulvinar, diam nunc tincidunt augue, sit amet lacinia ante mi a augue. Sed feugiat, neque eget porttitor varius, tellus nisi sollicitudin libero, nec aliquam ante dui gravida ipsum. Fusce cursus rhoncus lectus, quis malesuada sapien facilisis eu. Aenean vitae massa sed urna condimentum porttitor ac at risus.</p>
	                        </div>
	                        <!-- // Tab content END -->

	                    </div>
	                </div>
	            </div>
	        </div>
	        <!-- // Tabs END -->


	        <!-- Tabs -->
	        <div class="relativeWrap">
	            <div class="box-generic">

	                <!-- Tabs Heading -->
	                <div class="tabsbar">
	                    <ul class="nav nav-tabs">
	                        <li class="nav-item glyphicons camera active">
								<a class="nav-link" href="#tab1-3" data-toggle="tab"><i></i> View all photos
	                            <strong>(43)</strong></a>
	                        </li>
	                        <li class="nav-item glyphicons folder_open">
								<a class="nav-link" href="#tab2-3" data-toggle="tab"><i></i> Albums <strong>(3)</strong></a>
	                        </li>
	                        <li class="nav-item glyphicons circle_plus tab-stacked">
								<a class="nav-link" href="#tab3-3" data-toggle="tab"><i></i>
	                            <span>Add Photos</span></a>
	                        </li>
	                        <li class="nav-item glyphicons folder_plus tab-stacked">
								<a class="nav-link" href="#tab4-3" data-toggle="tab"><i></i>
	                            <span>Create Album</span></a>
	                        </li>
	                    </ul>
	                </div>
	                <!-- // Tabs Heading END -->

	                <div class="tab-content">

	                    <!-- Tab content -->
	                    <div class="tab-pane active" id="tab1-3">
	                        <h4>First tab</h4>

	                        <p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.</p>
	                    </div>
	                    <!-- // Tab content END -->

	                    <!-- Tab content -->
	                    <div class="tab-pane" id="tab2-3">
	                        <h4>Second tab</h4>

	                        <p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.</p>
	                    </div>
	                    <!-- // Tab content END -->

	                    <!-- Tab content -->
	                    <div class="tab-pane" id="tab3-3">
	                        <h4>Third tab</h4>

	                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
	                    </div>
	                    <!-- // Tab content END -->

	                    <!-- Tab content -->
	                    <div class="tab-pane" id="tab4-3">
	                        <h4>Fourth tab</h4>

	                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
	                    </div>
	                    <!-- // Tab content END -->

	                </div>
	            </div>
	        </div>
	        <!-- // Tabs END -->


	        <!-- Tabs -->
	        <div class="relativeWrap">
	            <div class="box-generic">

	                <!-- Tabs Heading -->
	                <div class="tabsbar tabsbar-2 tabsbar-design">
	                    <ul class="nav nav-tabs row row-merge">
	                        <li class="nav-item col-md-3 glyphicons cargo active">
								<a class="nav-link" href="#tab1-4" data-toggle="tab"><i></i> Product Listing</a>
	                        </li>
	                        <li class="nav-item col-md-3 glyphicons circle_info">
								<a class="nav-link" href="#tab2-4" data-toggle="tab"><i></i> <span>Product Details</span></a>
	                        </li>
	                        <li class="nav-item col-md-3 glyphicons cart_in">
								<a class="nav-link" href="#tab3-4" data-toggle="tab"><i></i> <span>Shopping Cart</span></a>
	                        </li>
	                        <li class="nav-item col-md-3 glyphicons pencil">
								<a class="nav-link" href="#tab4-4" data-toggle="tab"><i></i> <span>Shop Management</span></a>
	                        </li>
	                    </ul>
	                </div>
	                <!-- // Tabs Heading END -->

	                <div class="tab-content">

	                    <!-- Tab content -->
	                    <div class="tab-pane active" id="tab1-4">
	                        <h4>First tab</h4>

	                        <p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.</p>
	                    </div>
	                    <!-- // Tab content END -->

	                    <!-- Tab content -->
	                    <div class="tab-pane" id="tab2-4">
	                        <h4>Second tab</h4>

	                        <p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.</p>
	                    </div>
	                    <!-- // Tab content END -->

	                    <!-- Tab content -->
	                    <div class="tab-pane" id="tab3-4">
	                        <h4>Third tab</h4>

	                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
	                    </div>
	                    <!-- // Tab content END -->

	                    <!-- Tab content -->
	                    <div class="tab-pane" id="tab4-4">
	                        <h4>Fourth tab</h4>

	                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
	                    </div>
	                    <!-- // Tab content END -->

	                </div>
	            </div>
	        </div>
	        <!-- // Tabs END -->


	        <!-- Tabs -->
	        <div class="relativeWrap">
	            <div class="widget widget-tabs widget-tabs-responsive">

	                <!-- Tabs Heading -->
	                <div class="widget-head">
	                    <ul class="nav nav-tabs">
	                        <li class="nav-item active">
								<a class="nav-link glyphicons coffe_cup" href="#tab-1" data-toggle="tab"><i></i>Active
	                            tab</a>
	                        </li>
	                        <li class="nav-item">
								<a class="nav-link glyphicons share_alt" href="#tab-2" data-toggle="tab"><i></i>Other tab</a>
	                        </li>
	                    </ul>
	                </div>
	                <!-- // Tabs Heading END -->

	                <div class="widget-body">
	                    <div class="tab-content">

	                        <!-- Tab content -->
	                        <div class="tab-pane active" id="tab-1">
	                            <p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.</p>
	                        </div>
	                        <!-- // Tab content END -->

	                        <!-- Tab content -->
	                        <div class="tab-pane" id="tab-2">
	                            <p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.</p>
	                        </div>
	                        <!-- // Tab content END -->

	                    </div>
	                </div>
	            </div>
	        </div>
	        <!-- // Tabs END -->


	        <!-- Tabs -->
	        <div class="relativeWrap">
	            <div class="widget widget-tabs widget-tabs-double widget-regular widget-tabs-vertical row row-merge">

	                <!-- Tabs Heading -->
	                <div class="widget-head col-md-3">
	                    <ul class="nav nav-tabs">
	                        <li class="nav-item active">
								<a href="#tab1-1" class="nav-link glyphicons user" data-toggle="tab"><i></i><span
	                                class="strong">Step 1</span><span>Personal details</span></a>
	                        </li>
	                        <li class="nav-item">
								<a href="#tab2-1" class="nav-link glyphicons calculator" data-toggle="tab"><i></i><span
	                                class="strong">Step 2</span><span>Billing details</span></a>
	                        </li>
	                        <li class="nav-item">
								<a href="#tab3-1" class="nav-link glyphicons credit_card" data-toggle="tab"><i></i><span
	                                class="strong">Step 3</span><span>Payment</span></a>
	                        </li>
	                        <li class="nav-item">
								<a href="#tab4-1" class="nav-link glyphicons circle_ok" data-toggle="tab"><i></i><span
	                                class="strong">Step 4</span><span>Confirmation</span></a>
	                        </li>
	                    </ul>
	                </div>
	                <!-- // Tabs Heading END -->

	                <div class="widget-body col-md-9">
	                    <div class="tab-content">

	                        <!-- Tab content -->
	                        <div class="tab-pane active" id="tab1-1">
	                            <h4>First tab</h4>

	                            <p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.</p>
	                        </div>
	                        <!-- // Tab content END -->

	                        <!-- Tab content -->
	                        <div class="tab-pane" id="tab2-1">
	                            <h4>Second tab</h4>

	                            <p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.</p>
	                        </div>
	                        <!-- // Tab content END -->

	                        <!-- Tab content -->
	                        <div class="tab-pane" id="tab3-1">
	                            <h4>Third tab</h4>

	                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
	                        </div>
	                        <!-- // Tab content END -->

	                        <!-- Tab content -->
	                        <div class="tab-pane" id="tab4-1">
	                            <h4>Fourth tab</h4>

	                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
	                        </div>
	                        <!-- // Tab content END -->

	                    </div>

	                </div>
	            </div>
	        </div>
	        <!-- // Tabs END -->


	        <!-- Tabs -->
	        <div class="relativeWrap">
	            <div class="widget widget-tabs widget-tabs-double widget-regular widget-tabs-responsive">

	                <!-- Tabs Heading -->
	                <div class="widget-head">
	                    <ul class="nav nav-tabs">
	                        <li class="nav-item active">
								<a href="#tab1-2" class="nav-link glyphicons user" data-toggle="tab"><i></i><span
	                                class="strong">Step 1</span><span>Personal details</span></a>
	                        </li>
	                        <li class="nav-item">
								<a href="#tab2-2" class="nav-link glyphicons calculator" data-toggle="tab"><i></i><span
	                                class="strong">Step 2</span><span>Billing details</span></a>
	                        </li>
	                        <li class="nav-item">
								<a href="#tab3-2" class="nav-link glyphicons credit_card" data-toggle="tab"><i></i><span
	                                class="strong">Step 3</span><span>Payment</span></a>
	                        </li>
	                        <li class="nav-item">
								<a href="#tab4-2" class="nav-link glyphicons circle_ok" data-toggle="tab"><i></i><span
	                                class="strong">Step 4</span><span>Confirmation</span></a>
	                        </li>
	                    </ul>
	                </div>
	                <!-- // Tabs Heading END -->

	                <div class="widget-body">
	                    <div class="tab-content">

	                        <!-- Tab content -->
	                        <div class="tab-pane active" id="tab1-2">
	                            <h4>First tab</h4>

	                            <p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.</p>
	                        </div>
	                        <!-- // Tab content END -->

	                        <!-- Tab content -->
	                        <div class="tab-pane" id="tab2-2">
	                            <h4>Second tab</h4>

	                            <p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.</p>
	                        </div>
	                        <!-- // Tab content END -->

	                        <!-- Tab content -->
	                        <div class="tab-pane" id="tab3-2">
	                            <h4>Third tab</h4>

	                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
	                        </div>
	                        <!-- // Tab content END -->

	                        <!-- Tab content -->
	                        <div class="tab-pane" id="tab4-2">
	                            <h4>Fourth tab</h4>

	                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
	                        </div>
	                        <!-- // Tab content END -->

	                    </div>

	                </div>
	            </div>
	        </div>
	        <!-- // Tabs END -->


	        <!-- Icon only Tabs -->
	        <div class="relativeWrap">
	            <div class="widget widget-4 widget-tabs-icons-only margin-bottom-none icons-only">
	                <!-- Widget Heading -->
	                <div class="widget-head">
	                    <h4 class="heading">Tabs from Icons <span>400+ Premium Icons to choose from</span></h4>
	                    <!-- Tabs -->
	                    <ul class="nav nav-tabs float-right">
	                        <li>Filter by</li>
	                        <li class="nav-item glyphicons user_add active">
								<a class="nav-link" data-toggle="tab" href="#tab1-5"><i></i></a>
	                        </li>
	                        <li class="nav-item glyphicons shopping_cart">
								<a class="nav-link" data-toggle="tab" href="#tab2-5"><i></i></a>
	                        </li>
	                        <li class="nav-item glyphicons envelope">
								<a class="nav-link" data-toggle="tab" href="#tab3-5"><i></i></a>
	                        </li>
	                        <li class="nav-item glyphicons link">
								<a class="nav-link" data-toggle="tab" href="#tab4-5"><i></i></a>
	                        </li>
	                        <li class="nav-item glyphicons camera">
								<a class="nav-link" data-toggle="tab" href="#tab5-5"><i></i></a>
	                        </li>
	                    </ul>
	                    <div class="clearfix"></div>
	                    <!-- // Tabs END -->

	                </div>
	                <!-- Widget Heading END -->

	                <div class="widget-body">
	                    <div class="tab-content">

	                        <!-- Tab content -->
	                        <div id="tab1-5" class="tab-pane active box-generic">
	                            <h4>Tab #1 content heading</h4>

	                            <p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec id eros a orci adipiscing accumsan id eget sem. Etiam sit amet neque ligula, ac hendrerit metus. Phasellus convallis nulla nec leo dapibus sed feugiat felis feugiat. Nulla facilisi. Mauris quis tortor eu eros posuere tristique. In turpis leo, iaculis eget tincidunt in, gravida sit amet diam. Vivamus viverra, nisl vitae consectetur volutpat, ipsum risus tempor augue, in convallis leo massa in sem. Maecenas in urna quis purus pulvinar posuere. Fusce blandit viverra placerat. Fusce elementum turpis sed velit blandit elementum.</p>
	                        </div>
	                        <!-- // Tab content END -->

	                        <!-- Tab content -->
	                        <div id="tab2-5" class="tab-pane box-generic">
	                            <h4>Tab #2 content heading</h4>

	                            <p>Donec at nunc dui. Integer eget sem sit amet arcu bibendum elementum vel sit amet risus. Fusce libero lorem, fermentum vitae lacinia dapibus, vestibulum ac enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum accumsan risus sed lorem tincidunt eget faucibus sapien tempor. Proin ac feugiat dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.</p>
	                        </div>
	                        <!-- // Tab content END -->

	                        <!-- Tab content -->
	                        <div id="tab3-5" class="tab-pane box-generic">
	                            <h4>Tab #3 content heading</h4>

	                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ante est, tempor ut posuere nec, venenatis sed arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis in purus ut mauris sodales sollicitudin. Mauris cursus imperdiet dignissim. Phasellus risus felis, rutrum in laoreet vel, posuere vel dolor. Sed venenatis vehicula tempus. Nam at rutrum enim. Sed massa quam, mattis in viverra ut, ullamcorper et massa. Phasellus sapien diam, faucibus ac tempor a, condimentum quis est. Donec nec velit ante, vel mattis metus. Ut nec libero diam, id auctor sapien. Suspendisse eget lorem ante, in fringilla dui. In hac habitasse platea dictumst.
	                            </p>
	                        </div>
	                        <!-- // Tab content END -->

	                        <!-- Tab content -->
	                        <div id="tab4-5" class="tab-pane box-generic">
	                            <h4>Tab #4 content heading</h4>

	                            <p>Integer porttitor, enim eu egestas ullamcorper, odio mauris semper quam, in facilisis dui ligula eget ligula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas dolor leo, consectetur nec tristique pretium, ornare quis purus. Nullam pulvinar, enim eu molestie venenatis, turpis nisl vehicula eros, et ultricies risus urna sed diam. Suspendisse potenti. Nullam tincidunt tellus nisi. Aenean felis eros, congue vitae hendrerit id, mattis quis mi.</p>
	                        </div>
	                        <!-- // Tab content END -->

	                        <!-- Tab content -->
	                        <div id="tab5-5" class="tab-pane box-generic">
	                            <h4>Tab #5 content heading</h4>

	                            <p>Nunc aliquet lacus laoreet odio consectetur tempus. In id nisl diam, congue vehicula sapien. Nulla facilisi. Donec sagittis cursus sollicitudin. Aenean leo tellus, eleifend quis facilisis vel, tempus ac elit. Nam eget turpis nec erat vestibulum fringilla. Donec et felis ipsum. Fusce feugiat ultricies lacus a ultrices. Nunc ultrices, orci ut convallis pulvinar, diam nunc tincidunt augue, sit amet lacinia ante mi a augue. Sed feugiat, neque eget porttitor varius, tellus nisi sollicitudin libero, nec aliquam ante dui gravida ipsum. Fusce cursus rhoncus lectus, quis malesuada sapien facilisis eu. Aenean vitae massa sed urna condimentum porttitor ac at risus.</p>
	                        </div>
	                        <!-- // Tab content END -->

	                    </div>
	                </div>
	            </div>
	        </div>
	        <!-- // Icon only Tabs END -->


	    </div>


	</div>
	<!-- // Content END -->


    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->
    <!-- // Footer END -->

</div>
<!-- // Tab END -->