<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
	<div id="content">
	    <div class="heading-buttons bg-white border-bottom innerAll">
	        <h1 class="content-heading padding-none float-left">Questions &amp; Answers</h1>
	        <div class="clearfix"></div>
	    </div>

	    <div class="innerAll spacing-x2">

	        <!-- row -->
	        <div class="row">

	            <!-- col -->
	            <div class="col-md-3">

	                <div class="widget">

	                    <a href="" class="display-block innerAll inner-2x bg-primary">
	                        <span class="display-block text-center">
	                        <i class="fa fa-fw fa-3x icon-compose text-white"></i>
	                        <p class="strong innerT text-condensed text-medium text-white margin-none">Join Today!</p>
	                        <p class="text-normal margin-none strong text-white">Save &euro;250</p>
	                        
	                    </span>
	                    </a>
	                </div>
	                <div class="widget">
	                    <h4 class="innerAll half bg-inverse margin-none">Categories</h4>
	                    <ul class="list-group list-group-1 margin-none borders-none">
	                        <li class="list-group-item animated fadeInUp"><a href="#"><span class="badge float-right badge-default hidden-md">15</span> Category #1</a>
	                        </li>
	                        <li class="list-group-item animated fadeInUp"><a href="#"><span class="badge float-right badge-default hidden-md">10</span> Second Category</a>
	                        </li>
	                        <li class="list-group-item animated fadeInUp"><a href="#"><span class="badge float-right badge-default hidden-md">10</span> Third Category</a>
	                        </li>
	                        <li class="list-group-item border-bottom-none animated fadeInUp"><a href="#"><span class="badge float-right badge-default hidden-md">10</span> Forth Category</a>
	                        </li>
	                    </ul>
	                </div>
	                <div class="widget">

	                    <h5 class="innerAll half bg-gray border-bottom margin-bottom-none">Filter by</h5>
	                    <form role="form">
	                        <div class="innerAll inner-2x">
	                            <div class="form-group">
	                                <div class="input-group">
	                                    <span class="input-group-addon bg-gray"><i class="fa fa-question-circle text-faded"></i></span>
	                                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Search for a topic">
	                                </div>
	                            </div>
								<div class="form-group margin-none">
									<div class="checkbox">
								  		<label class="checkbox-custom">
								  			<i class="fa fa-fw fa-square-o"></i>
											<input type="checkbox" id="inlineCheckbox1" class="checkbox" value="option1" checked="checked"> Unanswered
										</label>
									</div>
									<div class="checkbox margin-none">
										<label class="checkbox-custom">
											<i class="fa fa-fw fa-square-o"></i>
											<input type="checkbox" id="inlineCheckbox2" value="option2" class="checkbox"> Answered
										</label>
									</div>
								</div>
	                        </div>
	                        <div class="text-center border-top innerTB"><a href="support_questions.html?lang=en" class="btn btn-primary"><i class="fa fa-fw fa-search"></i> Search</a>
	                        </div>
	                    </form>
	                </div>


	            </div>
	            <!-- // END col -->

	            <!-- col -->
	            <div class="col-md-9">

	                <!-- widget -->
	                <div class="widget widget-inverse no-bg">

	                    <div class="widget-head">

	                        <h4 class="margin-none innerAll half">Questions and Answers</h4>

	                    </div>

	                    <div class="widget-body padding-none">

	                        <div class="innerAll half border-bottom tickets">
	                            <div class="row">

	                                <div class="col-sm-10">
	                                    <ul class="media-list margin-none">
	                                        <li class="media">

	                                            <a class="float-left" href="support_answers.html?lang=en">
	                                                <img class="media-object" src="MelisDesign/images/people/50/1.jpg" alt="...">
	                                            </a>
	                                            <div class="media-body  half">
	                                                <a href="support_answers.html?lang=en" class="media-heading">Finding the right team?</a>

	                                                <label class="label label-default"><a href="" class="user-ticket-action">Unread</a>
	                                                </label>
	                                                <div class="clearfix"></div>
	                                                <small>posted by <a href="">Suzanne Marie</a> <i class="fa fa-fw icon-time-clock"></i> 12:51 AM</small>
	                                            </div>
	                                        </li>
	                                    </ul>

	                                </div>
	                                <div class="col-sm-2">
	                                    <div class="innerT half float-right">
	                                        <a href="" class="btn btn-info btn-xs strong"><i class=" icon-comment-fill-1"></i> 3</a>
	                                    </div>
	                                </div>
	                            </div>
	                        </div>
	                        <div class="innerAll half border-bottom tickets">
	                            <div class="row">

	                                <div class="col-sm-10">
	                                    <ul class="media-list margin-none">
	                                        <li class="media">

	                                            <a class="float-left" href="support_answers.html?lang=en">
	                                                <img class="media-object" src="MelisDesign/images/people/50/2.jpg" alt="...">
	                                            </a>
	                                            <div class="media-body  half">
	                                                <a href="support_answers.html?lang=en" class="media-heading">What makes Coral such an outstanding Template?</a>
	                                                <label class="label label-success"><i class="icon-checkmark-thick fa fa-fw"></i> Answered</label>
	                                                <div class="clearfix"></div>
	                                                <small>posted by <a href="">John Doe</a> <i class="fa fa-fw icon-time-clock"></i> 12:51 AM</small>
	                                            </div>
	                                        </li>
	                                    </ul>

	                                </div>
	                                <div class="col-sm-2">
	                                    <div class="innerT half float-right">
	                                        <a href="" class="btn btn-info btn-xs strong"><i class=" icon-comment-fill-1"></i> 3</a>
	                                    </div>
	                                </div>
	                            </div>
	                        </div>
	                        <div class="innerAll half border-bottom tickets">
	                            <div class="row">

	                                <div class="col-sm-10">
	                                    <ul class="media-list margin-none">
	                                        <li class="media">

	                                            <a class="float-left" href="support_answers.html?lang=en">
	                                                <span class="empty-photo">
	                                                            <i class="icon-blood-sample fa-2x"></i>
	                                                        </span>
	                                            </a>
	                                            <div class="media-body  half">
	                                                <a href="support_answers.html?lang=en" class="media-heading">What else will you guys come up with?</a>

	                                                <label class="label label-default"><a href="" class="user-ticket-action">Unread</a>
	                                                </label>
	                                                <div class="clearfix"></div>
	                                                <small>posted by <a href="">Mary Dawson</a> <i class="fa fa-fw icon-time-clock"></i> 12:51 AM</small>
	                                            </div>
	                                        </li>
	                                    </ul>

	                                </div>
	                                <div class="col-sm-2">
	                                    <div class="innerT half float-right">
	                                        <a href="" class="btn btn-info btn-xs strong"><i class=" icon-comment-fill-1"></i> 3</a>
	                                    </div>
	                                </div>
	                            </div>
	                        </div>
	                        <div class="innerAll half border-bottom tickets">
	                            <div class="row">

	                                <div class="col-sm-10">
	                                    <ul class="media-list margin-none">
	                                        <li class="media">

	                                            <a class="float-left" href="support_answers.html?lang=en">
	                                                <img class="media-object" src="MelisDesign/images/people/50/4.jpg" alt="...">
	                                            </a>
	                                            <div class="media-body  half">
	                                                <a href="support_answers.html?lang=en" class="media-heading">How many pages does this have?</a>
	                                                <label class="label label-success"><i class="icon-checkmark-thick fa fa-fw"></i> Answered</label>
	                                                <div class="clearfix"></div>
	                                                <small>posted by <a href="">John Carsten</a> <i class="fa fa-fw icon-time-clock"></i> 12:51 AM</small>
	                                            </div>
	                                        </li>
	                                    </ul>

	                                </div>
	                                <div class="col-sm-2">
	                                    <div class="innerT half float-right">
	                                        <a href="" class="btn btn-info btn-xs strong"><i class=" icon-comment-fill-1"></i> 3</a>
	                                    </div>
	                                </div>
	                            </div>
	                        </div>
	                        <div class="innerAll half border-bottom tickets">
	                            <div class="row">

	                                <div class="col-sm-10">
	                                    <ul class="media-list margin-none">
	                                        <li class="media">

	                                            <a class="float-left" href="support_answers.html?lang=en">
	                                                <span class="empty-photo">
	                                                            <i class="icon-blood-sample fa-2x"></i>
	                                                        </span>
	                                            </a>
	                                            <div class="media-body  half">
	                                                <a href="support_answers.html?lang=en" class="media-heading">Getting to know Coral</a>

	                                                <label class="label label-default"><a href="" class="user-ticket-action">Unread</a>
	                                                </label>
	                                                <div class="clearfix"></div>
	                                                <small>posted by <a href="">Suzanne Marie</a> <i class="fa fa-fw icon-time-clock"></i> 12:51 AM</small>
	                                            </div>
	                                        </li>
	                                    </ul>

	                                </div>
	                                <div class="col-sm-2">
	                                    <div class="innerT half float-right">
	                                        <a href="" class="btn btn-info btn-xs strong"><i class=" icon-comment-fill-1"></i> 3</a>
	                                    </div>
	                                </div>
	                            </div>
	                        </div>
	                        <div class="innerAll half border-bottom tickets">
	                            <div class="row">

	                                <div class="col-sm-10">
	                                    <ul class="media-list margin-none">
	                                        <li class="media">

	                                            <a class="float-left" href="support_answers.html?lang=en">
	                                                <span class="empty-photo">
	                                                            <i class="icon-blood-sample fa-2x"></i>
	                                                        </span>
	                                            </a>
	                                            <div class="media-body  half">
	                                                <a href="support_answers.html?lang=en" class="media-heading">Is it right for my project?</a>
	                                                <label class="label label-success"><i class="icon-checkmark-thick fa fa-fw"></i> Answered</label>
	                                                <div class="clearfix"></div>
	                                                <small>posted by <a href="">Bogdan Laza</a> <i class="fa fa-fw icon-time-clock"></i> 12:51 AM</small>
	                                            </div>
	                                        </li>
	                                    </ul>

	                                </div>
	                                <div class="col-sm-2">
	                                    <div class="innerT half float-right">
	                                        <a href="" class="btn btn-info btn-xs strong"><i class=" icon-comment-fill-1"></i> 3</a>
	                                    </div>
	                                </div>
	                            </div>
	                        </div>
	                        <div class="innerAll half border-bottom tickets">
	                            <div class="row">

	                                <div class="col-sm-10">
	                                    <ul class="media-list margin-none">
	                                        <li class="media">

	                                            <a class="float-left" href="support_answers.html?lang=en">
	                                                <img class="media-object" src="MelisDesign/images/people/50/7.jpg" alt="...">
	                                            </a>
	                                            <div class="media-body  half">
	                                                <a href="support_answers.html?lang=en" class="media-heading">About the new Email page</a>

	                                                <label class="label label-default"><a href="" class="user-ticket-action">Unread</a>
	                                                </label>
	                                                <div class="clearfix"></div>
	                                                <small>posted by <a href="">Stephanie</a> <i class="fa fa-fw icon-time-clock"></i> 12:51 AM</small>
	                                            </div>
	                                        </li>
	                                    </ul>

	                                </div>
	                                <div class="col-sm-2">
	                                    <div class="innerT half float-right">
	                                        <a href="" class="btn btn-info btn-xs strong"><i class=" icon-comment-fill-1"></i> 3</a>
	                                    </div>
	                                </div>
	                            </div>
	                        </div>
	                        <div class="innerAll half border-bottom tickets">
	                            <div class="row">

	                                <div class="col-sm-10">
	                                    <ul class="media-list margin-none">
	                                        <li class="media">

	                                            <a class="float-left" href="support_answers.html?lang=en">
	                                                <img class="media-object" src="MelisDesign/images/people/50/8.jpg" alt="...">
	                                            </a>
	                                            <div class="media-body  half">
	                                                <a href="support_answers.html?lang=en" class="media-heading">Social Page customization</a>
	                                                <label class="label label-success"><i class="icon-checkmark-thick fa fa-fw"></i> Answered</label>
	                                                <div class="clearfix"></div>
	                                                <small>posted by <a href="">John Carsten</a> <i class="fa fa-fw icon-time-clock"></i> 12:51 AM</small>
	                                            </div>
	                                        </li>
	                                    </ul>

	                                </div>
	                                <div class="col-sm-2">
	                                    <div class="innerT half float-right">
	                                        <a href="" class="btn btn-info btn-xs strong"><i class=" icon-comment-fill-1"></i> 3</a>
	                                    </div>
	                                </div>
	                            </div>
	                        </div>
	                        <div class="innerAll half border-bottom tickets">
	                            <div class="row">

	                                <div class="col-sm-10">
	                                    <ul class="media-list margin-none">
	                                        <li class="media">

	                                            <a class="float-left" href="support_answers.html?lang=en">
	                                                <span class="empty-photo">
	                                                            <i class="icon-blood-sample fa-2x"></i>
	                                                        </span>
	                                            </a>
	                                            <div class="media-body  half">
	                                                <a href="support_answers.html?lang=en" class="media-heading">Personal Assistant</a>

	                                                <label class="label label-default"><a href="" class="user-ticket-action">Unread</a>
	                                                </label>
	                                                <div class="clearfix"></div>
	                                                <small>posted by <a href="">girl381</a> <i class="fa fa-fw icon-time-clock"></i> 12:51 AM</small>
	                                            </div>
	                                        </li>
	                                    </ul>

	                                </div>
	                                <div class="col-sm-2">
	                                    <div class="innerT half float-right">
	                                        <a href="" class="btn btn-info btn-xs strong"><i class=" icon-comment-fill-1"></i> 3</a>
	                                    </div>
	                                </div>
	                            </div>
	                        </div>
	                        <div class="innerAll half border-bottom tickets">
	                            <div class="row">

	                                <div class="col-sm-10">
	                                    <ul class="media-list margin-none">
	                                        <li class="media">

	                                            <a class="float-left" href="support_answers.html?lang=en">
	                                                <img class="media-object" src="MelisDesign/images/people/50/10.jpg" alt="...">
	                                            </a>
	                                            <div class="media-body  half">
	                                                <a href="support_answers.html?lang=en" class="media-heading">Developer</a>
	                                                <label class="label label-success"><i class="icon-checkmark-thick fa fa-fw"></i> Answered</label>
	                                                <div class="clearfix"></div>
	                                                <small>posted by <a href="">Bogdan Laza</a> <i class="fa fa-fw icon-time-clock"></i> 12:51 AM</small>
	                                            </div>
	                                        </li>
	                                    </ul>

	                                </div>
	                                <div class="col-sm-2">
	                                    <div class="innerT half float-right">
	                                        <a href="" class="btn btn-info btn-xs strong"><i class=" icon-comment-fill-1"></i> 3</a>
	                                    </div>
	                                </div>
	                            </div>
	                        </div>
	                        <div class="innerAll half border-bottom tickets">
	                            <div class="row">

	                                <div class="col-sm-10">
	                                    <ul class="media-list margin-none">
	                                        <li class="media">

	                                            <a class="float-left" href="support_answers.html?lang=en">
	                                                <img class="media-object" src="MelisDesign/images/people/50/11.jpg" alt="...">
	                                            </a>
	                                            <div class="media-body  half">
	                                                <a href="support_answers.html?lang=en" class="media-heading">Project Manager</a>

	                                                <label class="label label-default"><a href="" class="user-ticket-action">Unread</a>
	                                                </label>
	                                                <div class="clearfix"></div>
	                                                <small>posted by <a href="">Suzanne Marie</a> <i class="fa fa-fw icon-time-clock"></i> 12:51 AM</small>
	                                            </div>
	                                        </li>
	                                    </ul>

	                                </div>
	                                <div class="col-sm-2">
	                                    <div class="innerT half float-right">
	                                        <a href="" class="btn btn-info btn-xs strong"><i class=" icon-comment-fill-1"></i> 3</a>
	                                    </div>
	                                </div>
	                            </div>
	                        </div>

	                    </div>

	                </div>

	            </div>
	            <!-- // END col-separator -->

	        </div>
	        <!-- // END row -->

	    </div>
	    <!-- End Inner -->

	</div>
	<!-- // Content END -->


    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->