<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    <div id="content" class="photo-gallery">
        <h1 class="content-heading bg-white border-bottom">Photo Gallery <span>Layouts</span></h1>
        <div class="innerAll bg-white border-bottom">
            <ul class="menubar">
                <li class="active"><a>Photo Gallery</a>
                </li>
            </ul>
        </div>

        <div class="innerAll spacing-x2">

            <div class="row">
                <div data-toggle="gridalicious" data-gridalicious-width="280" class="hide2">
                    <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                        <div class="widget-body padding-none">
                            <a href="/MelisDesign/images/gallery/1.jpg" class="thumb no-ajaxify" data-gallery>
                                <img src="/MelisDesign/images/gallery/1.jpg" alt="photo" />
                            </a>
                            <div class="description">
                                <h5 class="text-uppercase">Photo title</h5>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                            </div>
                        </div>
                    </div>
                    <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                        <div class="widget-body padding-none">
                            <a href="/MelisDesign/images/gallery/2.jpg" class="thumb no-ajaxify" data-gallery>
                                <img src="/MelisDesign/images/gallery/2.jpg" alt="photo" />
                            </a>
                            <div class="description">
                                <h5 class="text-uppercase">Photo title</h5>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                            </div>
                        </div>
                    </div>
                    <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                        <div class="widget-body padding-none">
                            <a href="/MelisDesign/images/gallery/3.jpg" class="thumb no-ajaxify" data-gallery>
                                <img src="/MelisDesign/images/gallery/3.jpg" alt="photo" />
                            </a>
                            <div class="description">
                                <h5 class="text-uppercase">Photo title</h5>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                            </div>
                        </div>
                    </div>
                    <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                        <div class="widget-body padding-none">
                            <a href="/MelisDesign/images/gallery/4.jpg" class="thumb no-ajaxify" data-gallery>
                                <img src="/MelisDesign/images/gallery/4.jpg" alt="photo" />
                            </a>
                            <div class="description">
                                <h5 class="text-uppercase">Photo title</h5>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                            </div>
                        </div>
                    </div>
                    <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                        <div class="widget-body padding-none">
                            <a href="/MelisDesign/images/gallery/5.jpg" class="thumb no-ajaxify" data-gallery>
                                <img src="/MelisDesign/images/gallery/5.jpg" alt="photo" />
                            </a>
                            <div class="description">
                                <h5 class="text-uppercase">Photo title</h5>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                            </div>
                        </div>
                    </div>
                    <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                        <div class="widget-body padding-none">
                            <a href="/MelisDesign/images/gallery/6.jpg" class="thumb no-ajaxify" data-gallery>
                                <img src="/MelisDesign/images/gallery/6.jpg" alt="photo" />
                            </a>
                            <div class="description">
                                <h5 class="text-uppercase">Photo title</h5>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                            </div>
                        </div>
                    </div>
                    <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                        <div class="widget-body padding-none">
                            <a href="/MelisDesign/images/gallery/7.jpg" class="thumb no-ajaxify" data-gallery>
                                <img src="/MelisDesign/images/gallery/7.jpg" alt="photo" />
                            </a>
                            <div class="description">
                                <h5 class="text-uppercase">Photo title</h5>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                            </div>
                        </div>
                    </div>
                    <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                        <div class="widget-body padding-none">
                            <a href="/MelisDesign/images/gallery/8.jpg" class="thumb no-ajaxify" data-gallery>
                                <img src="/MelisDesign/images/gallery/8.jpg" alt="photo" />
                            </a>
                            <div class="description">
                                <h5 class="text-uppercase">Photo title</h5>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                            </div>
                        </div>
                    </div>
                    <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                        <div class="widget-body padding-none">
                            <a href="/MelisDesign/images/gallery/9.jpg" class="thumb no-ajaxify" data-gallery>
                                <img src="/MelisDesign/images/gallery/9.jpg" alt="photo" />
                            </a>
                            <div class="description">
                                <h5 class="text-uppercase">Photo title</h5>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                            </div>
                        </div>
                    </div>
                    <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                        <div class="widget-body padding-none">
                            <a href="/MelisDesign/images/gallery/10.jpg" class="thumb no-ajaxify" data-gallery>
                                <img src="/MelisDesign/images/gallery/10.jpg" alt="photo" />
                            </a>
                            <div class="description">
                                <h5 class="text-uppercase">Photo title</h5>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                            </div>
                        </div>
                    </div>
                    <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                        <div class="widget-body padding-none">
                            <a href="/MelisDesign/images/gallery/11.jpg" class="thumb no-ajaxify" data-gallery>
                                <img src="/MelisDesign/images/gallery/11.jpg" alt="photo" />
                            </a>
                            <div class="description">
                                <h5 class="text-uppercase">Photo title</h5>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                            </div>
                        </div>
                    </div>
                    <div class="widget widget-heading-simple widget-body-white widget-pinterest">
                        <div class="widget-body padding-none">
                            <a href="/MelisDesign/images/gallery/12.jpg" class="thumb no-ajaxify" data-gallery>
                                <img src="/MelisDesign/images/gallery/12.jpg" alt="photo" />
                            </a>
                            <div class="description">
                                <h5 class="text-uppercase">Photo title</h5>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                            </div>
                        </div>
                    </div>
                </div>





                <!-- Blueimp Gallery -->
                <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
                    <div class="slides"></div>
                    <h3 class="title"></h3>
                    <a class="prev no-ajaxify">‹</a>
                    <a class="next no-ajaxify">›</a>
                    <a class="close no-ajaxify">×</a>
                    <a class="play-pause no-ajaxify"></a>
                    <ol class="indicator"></ol>
                </div>
                <!-- // Blueimp Gallery END -->
            </div>

            <div class="widget widget-inverse widget-gallery" data-toggle="collapse-widget">
                <div class="widget-head">
                    <h4 class="heading">Photo Gallery</h4>
                </div>
                <div class="widget-body">

                    <!-- Gallery Layout -->
                    <div class="gallery gallery-2">
                        <ul class="row list-unstyled" data-toggle="modal-gallery" data-target="#modal-gallery" id="gallery-4" data-delegate="#gallery-4">
                            <li class="col-md-3 hidden-phone">
                                <a class="thumb" href="MelisDesign/images/gallery-2/8.jpg" data-gallery="gallery"><img src="MelisDesign/images/gallery-2/8.jpg" alt="photo" data-toggle="prettyPhoto" class="img-fluid" />
                                </a>
                            </li>
                            <li class="col-md-3 hidden-phone">
                                <a class="thumb" href="MelisDesign/images/gallery-2/7.jpg" data-gallery="gallery"><img src="MelisDesign/images/gallery-2/7.jpg" alt="photo" data-toggle="prettyPhoto" class="img-fluid" />
                                </a>
                            </li>
                            <li class="col-md-3 hidden-phone">
                                <a class="thumb" href="MelisDesign/images/gallery-2/6.jpg" data-gallery="gallery"><img src="MelisDesign/images/gallery-2/6.jpg" alt="photo" data-toggle="prettyPhoto" class="img-fluid" />
                                </a>
                            </li>
                            <li class="col-md-3 hidden-phone">
                                <a class="thumb" href="MelisDesign/images/gallery-2/5.jpg" data-gallery="gallery"><img src="MelisDesign/images/gallery-2/5.jpg" alt="photo" data-toggle="prettyPhoto" class="img-fluid" />
                                </a>
                            </li>
                            <li class="col-md-3 hidden-phone">
                                <a class="thumb" href="MelisDesign/images/gallery-2/4.jpg" data-gallery="gallery"><img src="MelisDesign/images/gallery-2/4.jpg" alt="photo" data-toggle="prettyPhoto" class="img-fluid" />
                                </a>
                            </li>
                            <li class="col-md-3">
                                <a class="thumb" href="MelisDesign/images/gallery-2/3.jpg" data-gallery="gallery"><img src="MelisDesign/images/gallery-2/3.jpg" alt="photo" data-toggle="prettyPhoto" class="img-fluid" />
                                </a>
                            </li>
                            <li class="col-md-3">
                                <a class="thumb" href="MelisDesign/images/gallery-2/2.jpg" data-gallery="gallery"><img src="MelisDesign/images/gallery-2/2.jpg" alt="photo" data-toggle="prettyPhoto" class="img-fluid" />
                                </a>
                            </li>
                            <li class="col-md-3">
                                <a class="thumb" href="MelisDesign/images/gallery-2/1.jpg" data-gallery="gallery"><img src="MelisDesign/images/gallery-2/1.jpg" alt="photo" data-toggle="prettyPhoto" class="img-fluid" />
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!-- // Gallery Layout END -->

                </div>
            </div>

            <div class="widget widget-inverse widget-gallery" data-toggle="collapse-widget">
                <div class="widget-head">
                    <h4 class="heading">Photo Gallery</h4>
                </div>
                <div class="widget-body">

                    <!-- Tabs -->
                    <div class="tabsbar">
                        <ul>
                            <li class="glyphicons camera active"><a href=""><i></i> View all photos <strong>(43)</strong></a>
                            </li>
                            <li class="glyphicons folder_open"><a href=""><i></i> Albums <strong>(3)</strong></a>
                            </li>
                            <li class="glyphicons circle_plus tab-stacked"><a href=""><i></i> <span>Add Photos</span></a>
                            </li>
                            <li class="glyphicons folder_plus tab-stacked"><a href=""><i></i> <span>Create Album</span></a>
                            </li>
                        </ul>
                    </div>
                    <!-- // Tabs END -->

                    <!-- Gallery -->
                    <div class="gallery innerB">
                        <ul class="row list-unstyled" data-toggle="modal-gallery" data-target="#modal-gallery" id="gallery-3" data-delegate="#gallery-3">

                            <!-- Gallery item -->
                            <li class="col-md-2">
                                <a class="thumb" href="MelisDesign/images/gallery-2/1.jpg" data-gallery="gallery">
                                    <img src="MelisDesign/images/gallery-2/1.jpg" alt="photo" data-toggle="prettyPhoto" class="img-fluid" />
                                </a>
                            </li>
                            <!-- // Gallery item END -->
                            <!-- Gallery item -->
                            <li class="col-md-2">
                                <a class="thumb" href="MelisDesign/images/gallery-2/2.jpg" data-gallery="gallery">
                                    <img src="MelisDesign/images/gallery-2/2.jpg" alt="photo" data-toggle="prettyPhoto" class="img-fluid" />
                                </a>
                            </li>
                            <!-- // Gallery item END -->
                            <!-- Gallery item -->
                            <li class="col-md-2">
                                <a class="thumb" href="MelisDesign/images/gallery-2/3.jpg" data-gallery="gallery">
                                    <img src="MelisDesign/images/gallery-2/3.jpg" alt="photo" data-toggle="prettyPhoto" class="img-fluid" />
                                </a>
                            </li>
                            <!-- // Gallery item END -->
                            <!-- Gallery item -->
                            <li class="col-md-2">
                                <a class="thumb" href="MelisDesign/images/gallery-2/4.jpg" data-gallery="gallery">
                                    <img src="MelisDesign/images/gallery-2/4.jpg" alt="photo" data-toggle="prettyPhoto" class="img-fluid" />
                                </a>
                            </li>
                            <!-- // Gallery item END -->
                            <!-- Gallery item -->
                            <li class="col-md-2">
                                <a class="thumb" href="MelisDesign/images/gallery-2/5.jpg" data-gallery="gallery">
                                    <img src="MelisDesign/images/gallery-2/5.jpg" alt="photo" data-toggle="prettyPhoto" class="img-fluid" />
                                </a>
                            </li>
                            <!-- // Gallery item END -->
                            <!-- Gallery item -->
                            <li class="col-md-2">
                                <a class="thumb" href="MelisDesign/images/gallery-2/6.jpg" data-gallery="gallery">
                                    <img src="MelisDesign/images/gallery-2/6.jpg" alt="photo" data-toggle="prettyPhoto" class="img-fluid" />
                                </a>
                            </li>
                            <!-- // Gallery item END -->
                            <!-- Gallery item -->
                            <li class="col-md-2">
                                <a class="thumb" href="MelisDesign/images/gallery-2/7.jpg" data-gallery="gallery">
                                    <img src="MelisDesign/images/gallery-2/7.jpg" alt="photo" data-toggle="prettyPhoto" class="img-fluid" />
                                </a>
                            </li>
                            <!-- // Gallery item END -->
                            <!-- Gallery item -->
                            <li class="col-md-2">
                                <a class="thumb" href="MelisDesign/images/gallery-2/8.jpg" data-gallery="gallery">
                                    <img src="MelisDesign/images/gallery-2/8.jpg" alt="photo" data-toggle="prettyPhoto" class="img-fluid" />
                                </a>
                            </li>
                            <!-- // Gallery item END -->
                            <!-- Gallery item -->
                            <li class="col-md-2">
                                <a class="thumb" href="MelisDesign/images/gallery-2/9.jpg" data-gallery="gallery">
                                    <img src="MelisDesign/images/gallery-2/9.jpg" alt="photo" data-toggle="prettyPhoto" class="img-fluid" />
                                </a>
                            </li>
                            <!-- // Gallery item END -->
                            <!-- Gallery item -->
                            <li class="col-md-2">
                                <a class="thumb" href="MelisDesign/images/gallery-2/10.jpg" data-gallery="gallery">
                                    <img src="MelisDesign/images/gallery-2/10.jpg" alt="photo" data-toggle="prettyPhoto" class="img-fluid" />
                                </a>
                            </li>
                            <!-- // Gallery item END -->
                            <!-- Gallery item -->
                            <li class="col-md-2">
                                <a class="thumb" href="MelisDesign/images/gallery-2/11.jpg" data-gallery="gallery">
                                    <img src="MelisDesign/images/gallery-2/11.jpg" alt="photo" data-toggle="prettyPhoto" class="img-fluid" />
                                </a>
                            </li>
                            <!-- // Gallery item END -->
                            <!-- Gallery item -->
                            <li class="col-md-2">
                                <a class="thumb" href="MelisDesign/images/gallery-2/12.jpg" data-gallery="gallery">
                                    <img src="MelisDesign/images/gallery-2/12.jpg" alt="photo" data-toggle="prettyPhoto" class="img-fluid" />
                                </a>
                            </li>
                            <!-- // Gallery item END -->

                        </ul>
                    </div>
                    <!-- // Gallery END -->

                    <!-- Pagination -->
                    <div class="btn-group btn-group-sm">
                        <a class="btn disabled btn-default"><i class="fa fa-chevron-left"></i></a>
                        <a class="btn btn-default"><i class="fa fa-chevron-right"></i></a>
                    </div>
                    <span class="innerLR">1-6 out of 43</span>
                    <!-- // Pagination END -->

                </div>
            </div>

        </div>

    </div>
    <!-- // Content END -->


    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->
