<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;
        
?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    <div id="content">
        <h1 class="content-heading bg-white border-bottom">Medical patients</h1>
        <div class="bg-white innerAll border-bottom">
            <ul class="menubar">
                <li><a href="index.html?lang=en">Dashboard</a>
                </li>
                <li><a href="#"><span class="badge badge-primary pull-right">30</span> Button</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Dropdown Link #1</a>
                        </li>
                        <li><a href="#">Dropdown Link #2</a>
                        </li>
                        <li><a href="#">Dropdown Link #3</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="innerAll spacing-x2">

            <!-- row-app -->
            <div class="row row-app">

                <!-- col -->
                <div class="col-lg-8">

                    <div class="box-generic padding-none">
                        <div class="media innerAll">
                            <button class="pull-right btn btn-default btn-sm"><i class="fa fa-fw fa-edit"></i> Edit</button>
                            <img src="MelisDesign/images/people/250/2.jpg" class="thumb pull-left" alt="" width="100">
                            <div class="media-body innerLR innerT half">
                                <h4 class="media-heading">Adrian Demian</h4>
                                <p>Male, 27 years old
                                    <br/>Living in Dublin, Ireland
                                    <br/>Patient 1234567890</p>
                            </div>
                        </div>
                    </div>

                    <div class="box-generic padding-none">
                        <div class="row row-merge margin-none">
                            <div class="col-md-4">
                                <div class="innerAll half text-center">
                                    <span class="text-large strong">75.2</span>
                                    <br/> Weight (kg)
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="innerAll half text-center">
                                    <span class="text-large strong">27</span>
                                    <br/> Age (years)
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="innerAll half text-center">
                                    <span class="text-large strong">180</span>
                                    <br/> Height (cm)
                                </div>
                            </div>
                        </div>
                        <div class="row row-merge margin-none">
                            <div class="col-md-6">
                                <div class="innerAll half text-center">
                                    <div class="media innerAll half">
                                        <div class="pull-left">
                                            Blood presure
                                            <div class="strong">110/90 mmHh</div>
                                        </div>
                                        <div class="media-body innerAll">
                                            <div class="progress progress-small margin-none">
                                                <div class="progress-bar progress-bar-primary" style="width: 80%"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="innerAll half text-center">
                                    <div class="media innerAll half">
                                        <div class="pull-left">
                                            Exercise
                                            <div class="strong">2 hours, 30 mins</div>
                                        </div>
                                        <div class="media-body innerAll">
                                            <div class="progress progress-small margin-none">
                                                <div class="progress-bar progress-bar-primary" style="width: 35%"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="box-generic padding-none">

                        <h4 class="innerAll half margin-none border-bottom"><i class="fa fa-fw fa-clock-o pull-right text-muted"></i> Patient History</h4>

                        <ul class="timeline-activity list-unstyled">
                            <li>
                                <i class="list-icon fa fa-scissors"></i>
                                <div class="block">
                                    <div class="caret"></div>
                                    <div class="box-generic bg-primary-light">
                                        <div class="timeline-top-info border-bottom">
                                            <a href="" class="text-regular">Upcoming procedure</a> <span class="text-muted2">(consectetur adipisicing elit)</span> with <i class="fa fa-stethoscope text-primary"></i> <a href="">Dr. Dignissimos</a>
                                        </div>
                                        <div class="innerAll half inline-block bg-trans">
                                            <i class="fa fa-clock-o text-primary"></i> 17:00 &nbsp;
                                            <i class="fa fa-calendar text-primary"></i> 3 October 2013
                                        </div>
                                    </div>
                                    <div class="separator bottom"></div>
                                </div>
                            </li>
                            <li>
                                <i class="list-icon fa fa-stethoscope"></i>
                                <div class="block">
                                    <div class="caret"></div>
                                    <div class="box-generic">
                                        <div class="timeline-top-info border-bottom">
                                            <a href="" class="text-regular">Consultation</a> with <i class="fa fa-stethoscope"></i> <a href="">Dr. Dignissimos</a>
                                        </div>
                                        <div class="innerAll half inline-block">
                                            <i class="fa fa-clock-o"></i> 10:00 &nbsp;
                                            <i class="fa fa-calendar"></i> 2 October 2013
                                        </div>
                                    </div>
                                    <div class="separator bottom"></div>
                                </div>
                                <div class="block block-inline">
                                    <div class="box-generic">
                                        <div class="innerT innerR">
                                            <button class="btn btn-primary btn-xs pull-right"><i class="fa fa-download"></i>
                                            </button>
                                            <div class="media inline-block margin-none">
                                                <div class="innerLR">
                                                    <i class="fa fa-stethoscope pull-left text-primary fa-2x"></i>
                                                    <div class="media-body t-row">
                                                        <div><a href="" class="strong text-regular">Lab Test Results</a>
                                                        </div>
                                                        <span>1 MB</span>
                                                    </div>
                                                    <div class="clearfix"></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="block block-inline">
                                    <div class="box-generic">
                                        <div class="innerT innerR">
                                            <button class="btn btn-primary btn-xs pull-right"><i class="fa fa-eye"></i>
                                            </button>
                                            <div class="media inline-block margin-none">
                                                <div class="innerLR">
                                                    <i class="fa fa-file-text-o pull-left text-primary fa-2x"></i>
                                                    <div class="media-body t-row">
                                                        <div><a href="" class="strong text-regular">Notes</a>
                                                        </div>
                                                        <span>24 KB</span>
                                                    </div>
                                                    <div class="clearfix"></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>



                    </div>
                    <!-- // END col-separator.box -->

                </div>
                <!-- // END col -->

                <!-- col -->
                <div class="col-lg-4">

                    <div class="box-generic margin-none heading-buttons innerAll half">
                        <h4 class="margin-none padding-none pull-left">Patients</h4>
                        <button class="btn btn-xs btn-default pull-right"><i class="fa fa-plus"></i> Add patient <i class="fa fa-user fa-fw"></i>
                        </button>
                        <div class="clearfix"></div>
                    </div>

                    <div class="box-generic padding-none border-top-none">
                        <div class="input-group input-group-sm">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-inverse dropdown-toggle" data-toggle="dropdown">Name <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Name</a>
                                    </li>
                                    <li><a href="#">Phone Number</a>
                                    </li>
                                    <li><a href="#">Group</a>
                                    </li>
                                </ul>
                            </div>
                            <input type="text" class="form-control border-none" placeholder="Find a patient ...">
                        </div>
                    </div>

                    <ul class="list-group list-group-1 margin-none">
                        <li class="list-group-item active">
                            <div class="media innerAll half bg-trans">
                                <button class="pull-right btn btn-primary btn-stroke btn-xs"><i class="fa fa-arrow-right"></i>
                                </button>
                                <img src="MelisDesign/images/people/35/2.jpg" alt="" class="pull-left thumb">
                                <div class="media-body">
                                    <h5 class="media-heading strong">Adrian Demian</h5>
                                    <ul class="list-unstyled">
                                        <li><i class="fa fa-phone"></i> 0353 8473102009</li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="media innerAll half bg-trans">
                                <button class="pull-right btn btn-primary btn-stroke btn-xs"><i class="fa fa-arrow-right"></i>
                                </button>
                                <img src="MelisDesign/images/people/35/3.jpg" alt="" class="pull-left thumb">
                                <div class="media-body">
                                    <h5 class="media-heading strong">Adrian Demian</h5>
                                    <ul class="list-unstyled">
                                        <li><i class="fa fa-phone"></i> 0353 8473102009</li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="media innerAll half bg-trans">
                                <button class="pull-right btn btn-primary btn-stroke btn-xs"><i class="fa fa-arrow-right"></i>
                                </button>
                                <img src="MelisDesign/images/people/35/4.jpg" alt="" class="pull-left thumb">
                                <div class="media-body">
                                    <h5 class="media-heading strong">Adrian Demian</h5>
                                    <ul class="list-unstyled">
                                        <li><i class="fa fa-phone"></i> 0353 8473102009</li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="media innerAll half bg-trans">
                                <button class="pull-right btn btn-primary btn-stroke btn-xs"><i class="fa fa-arrow-right"></i>
                                </button>
                                <img src="MelisDesign/images/people/35/5.jpg" alt="" class="pull-left thumb">
                                <div class="media-body">
                                    <h5 class="media-heading strong">Adrian Demian</h5>
                                    <ul class="list-unstyled">
                                        <li><i class="fa fa-phone"></i> 0353 8473102009</li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="media innerAll half bg-trans">
                                <button class="pull-right btn btn-primary btn-stroke btn-xs"><i class="fa fa-arrow-right"></i>
                                </button>
                                <img src="MelisDesign/images/people/35/6.jpg" alt="" class="pull-left thumb">
                                <div class="media-body">
                                    <h5 class="media-heading strong">Adrian Demian</h5>
                                    <ul class="list-unstyled">
                                        <li><i class="fa fa-phone"></i> 0353 8473102009</li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>

                </div>
                <!-- // END col -->

            </div>
            <!-- // END row-app -->

        </div>





    </div>
    <!-- // Content END -->

        
<div class="clearfix"></div>
<!-- // Sidebar menu & content wrapper END -->


</div>
<!-- // Tab END -->