<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    <div id="content" class="inbox-app">
        <div class="layout-app app-div">
            <div class="col-table">

                <h1 class="bg-white content-heading border-bottom">Inbox</h1>
                <div class="bg-white innerAll border-bottom">
                    <ul class="menubar">
                        <li><a href="index.html?lang=en">Dashboard</a>
                        </li>
                        <li><a href="#"><span class="badge badge-primary float-right">30</span> Button</a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Dropdown Link #1</a>
                                </li>
                                <li><a href="#">Dropdown Link #2</a>
                                </li>
                                <li><a href="#">Dropdown Link #3</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="col-separator-h"></div>

                <div class="col-table-row">

                    <div class="col-app col-unscrollable">

                        <div class="col-app">
                            <div class="row row-app email">
                                <div class="col-md-3">

                                    <div class="col-separator col-separator-first box inbox-scrollable">

                                        <h4 class="innerAll border-bottom margin-none">Inbox</h4>

                                        <div class="innerAll text-center bg-primary border-bottom">
                                            <a class="inline-block" href=""><img src="MelisDesign/images/people/250/16.jpg" alt="" class="thumb img-fluid rounded-circle" width="100" />
                                            </a>
                                        </div>

                                        <ul class="list-group list-group-1 margin-none borders-none">
                                            <li class="list-group-item active"><a href="#"><span class="badge float-right badge-primary hidden-md">30</span><i class="fa fa-inbox"></i> Inbox</a>
                                            </li>
                                            <li class="list-group-item"><a href="#"><span class="badge float-right badge-primary hidden-md">2</span><i class="fa fa-book"></i> Drafts</a>
                                            </li>
                                            <li class="list-group-item"><a href="#"><i class="fa fa-envelope"></i> Sent</a>
                                            </li>
                                            <li class="list-group-item border-bottom-none"><a href="#"><i class="fa fa-cogs"></i> Settings</a>
                                            </li>
                                        </ul>

                                        <div class="col-separator-h box"></div>
                                        <div class="text-center innerAll">
                                            <button class="btn btn-inverse animated flipInY"><i class="fa fa-edit"></i> Compose</button>
                                        </div>
                                        <div class="innerAll bg-gray animated fadeInLeftBig">
                                            Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                        </div>

                                    </div>
                                </div>
                                <div class="col-md-9">
                                    <div class="col-separator">

                                        <div class="row row-app">
                                            <div class="col-md-4">
                                                <div class="col-separator col-unscrollable box inbox-scrollable">
                                                    <div class="col-table">

                                                        <div class="innerAll border-bottom">
                                                            <span class="float-right">You have <strong class="text-primary">5 new</strong> emails</span>
                                                            <span class="label label-primary">INBOX</span>
                                                            <div class="clearfix"></div>
                                                        </div>

                                                        <div class="col-table-row">
                                                            <div class="col-app col-unscrollable">
                                                                <div class="col-app">
                                                                    <div class="list-group email-item-list">


                                                                        <a href="#" class="list-group-item active">
                                                                            <span class="media">
                                                                        <img src="MelisDesign/images/people/80/1.jpg" alt="" width="35" class="thumb img-fluid rounded-circle float-left" />
                                                                        <span class="media-body media-body-inline">
                                                                            <span class="label label-inverse label-stroke float-right">29 Oct</span>
                                                                            <h4 class="">Molestias Architecto <i class="icon-flag text-primary icon-2x"></i></h4>
                                                                            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, libero <span class="strong text-regular"><i class="fa fa-paperclip"></i> 2</span>
                                                                            </p>
                                                                            </span>
                                                                            </span>
                                                                        </a>
                                                                        <a href="#" class="list-group-item">
                                                                            <span class="media">
                                                                        <img src="MelisDesign/images/people/80/2.jpg" alt="" width="35" class="thumb img-fluid rounded-circle float-left" />
                                                                        <span class="media-body media-body-inline">
                                                                            <span class="label label-inverse float-right">28 Oct</span>
                                                                            <h4 class=" strong">Corrupti Officiis <i class="icon-flag text-primary icon-2x"></i></h4>
                                                                            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, libero </p>
                                                                            </span>
                                                                            </span>
                                                                        </a>
                                                                        <a href="#" class="list-group-item">
                                                                            <span class="media">
                                                                        <img src="MelisDesign/images/people/80/3.jpg" alt="" width="35" class="thumb img-fluid rounded-circle float-left" />
                                                                        <span class="media-body media-body-inline">
                                                                            <span class="label label-inverse float-right">27 Oct</span>
                                                                            <h4 class=" strong">Velit Nostrum <i class="icon-flag text-primary icon-2x"></i></h4>
                                                                            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, libero </p>
                                                                            </span>
                                                                            </span>
                                                                        </a>
                                                                        <a href="#" class="list-group-item">
                                                                            <span class="media">
                                                                        <img src="MelisDesign/images/people/80/4.jpg" alt="" width="35" class="thumb img-fluid rounded-circle float-left" />
                                                                        <span class="media-body media-body-inline">
                                                                            <span class="label label-inverse float-right">26 Oct</span>
                                                                            <h4 class=" strong">Tempora Unde <i class="icon-flag text-primary icon-2x"></i></h4>
                                                                            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, libero </p>
                                                                            </span>
                                                                            </span>
                                                                        </a>
                                                                        <a href="#" class="list-group-item">
                                                                            <span class="media">
                                                                        <img src="MelisDesign/images/people/80/5.jpg" alt="" width="35" class="thumb img-fluid rounded-circle float-left" />
                                                                        <span class="media-body media-body-inline">
                                                                            <span class="label label-inverse label-stroke float-right">25 Oct</span>
                                                                            <h4 class="">Voluptas Quasi <i class="icon-flag text-primary icon-2x"></i></h4>
                                                                            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, libero </p>
                                                                            </span>
                                                                            </span>
                                                                        </a>
                                                                        <a href="#" class="list-group-item">
                                                                            <span class="media">
                                                                        <img src="MelisDesign/images/people/80/6.jpg" alt="" width="35" class="thumb img-fluid rounded-circle float-left" />
                                                                        <span class="media-body media-body-inline">
                                                                            <span class="label label-inverse float-right">24 Oct</span>
                                                                            <h4 class=" strong">Minima Debitis <i class="icon-flag text-primary icon-2x"></i></h4>
                                                                            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, libero </p>
                                                                            </span>
                                                                            </span>
                                                                        </a>
                                                                        <a href="#" class="list-group-item">
                                                                            <span class="media">
                                                                        <img src="MelisDesign/images/people/80/7.jpg" alt="" width="35" class="thumb img-fluid rounded-circle float-left" />
                                                                        <span class="media-body media-body-inline">
                                                                            <span class="label label-inverse float-right">23 Oct</span>
                                                                            <h4 class=" strong">Fugit Labore <i class="icon-flag text-primary icon-2x"></i></h4>
                                                                            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, libero </p>
                                                                            </span>
                                                                            </span>
                                                                        </a>
                                                                        <a href="#" class="list-group-item">
                                                                            <span class="media">
                                                                        <img src="MelisDesign/images/people/80/8.jpg" alt="" width="35" class="thumb img-fluid rounded-circle float-left" />
                                                                        <span class="media-body media-body-inline">
                                                                            <span class="label label-inverse label-stroke float-right">22 Oct</span>
                                                                            <h4 class="">Eaque Adipisci <i class="icon-flag text-primary icon-2x"></i></h4>
                                                                            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, libero </p>
                                                                            </span>
                                                                            </span>
                                                                        </a>
                                                                        <a href="#" class="list-group-item">
                                                                            <span class="media">
                                                                        <img src="MelisDesign/images/people/80/9.jpg" alt="" width="35" class="thumb img-fluid rounded-circle float-left" />
                                                                        <span class="media-body media-body-inline">
                                                                            <span class="label label-inverse label-stroke float-right">21 Oct</span>
                                                                            <h4 class="">Rem Excepturi <i class="icon-flag text-primary icon-2x"></i></h4>
                                                                            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, libero </p>
                                                                            </span>
                                                                            </span>
                                                                        </a>
                                                                        <a href="#" class="list-group-item">
                                                                            <span class="media">
                                                                        <img src="MelisDesign/images/people/80/10.jpg" alt="" width="35" class="thumb img-fluid rounded-circle float-left" />
                                                                        <span class="media-body media-body-inline">
                                                                            <span class="label label-inverse label-stroke float-right">20 Oct</span>
                                                                            <h4 class="">Beatae Sint <i class="icon-flag text-primary icon-2x"></i></h4>
                                                                            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, libero </p>
                                                                            </span>
                                                                            </span>
                                                                        </a>
                                                                        <a href="#" class="list-group-item">
                                                                            <span class="media">
                                                                        <img src="MelisDesign/images/people/80/11.jpg" alt="" width="35" class="thumb img-fluid rounded-circle float-left" />
                                                                        <span class="media-body media-body-inline">
                                                                            <span class="label label-inverse label-stroke float-right">19 Oct</span>
                                                                            <h4 class="">Temporibus Saepe <i class="icon-flag text-primary icon-2x"></i></h4>
                                                                            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, libero </p>
                                                                            </span>
                                                                            </span>
                                                                        </a>
                                                                        <a href="#" class="list-group-item">
                                                                            <span class="media">
                                                                        <img src="MelisDesign/images/people/80/12.jpg" alt="" width="35" class="thumb img-fluid rounded-circle float-left" />
                                                                        <span class="media-body media-body-inline">
                                                                            <span class="label label-inverse label-stroke float-right">18 Oct</span>
                                                                            <h4 class="">Neque Distinctio <i class="icon-flag text-primary icon-2x"></i></h4>
                                                                            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, libero </p>
                                                                            </span>
                                                                            </span>
                                                                        </a>
                                                                        <a href="#" class="list-group-item">
                                                                            <span class="media">
                                                                        <img src="MelisDesign/images/people/80/13.jpg" alt="" width="35" class="thumb img-fluid rounded-circle float-left" />
                                                                        <span class="media-body media-body-inline">
                                                                            <span class="label label-inverse label-stroke float-right">17 Oct</span>
                                                                            <h4 class="">Aperiam Dolorem <i class="icon-flag text-primary icon-2x"></i></h4>
                                                                            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, libero </p>
                                                                            </span>
                                                                            </span>
                                                                        </a>
                                                                        <a href="#" class="list-group-item">
                                                                            <span class="media">
                                                                        <img src="MelisDesign/images/people/80/14.jpg" alt="" width="35" class="thumb img-fluid rounded-circle float-left" />
                                                                        <span class="media-body media-body-inline">
                                                                            <span class="label label-inverse label-stroke float-right">16 Oct</span>
                                                                            <h4 class="">Reprehenderit Quam <i class="icon-flag text-primary icon-2x"></i></h4>
                                                                            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, libero </p>
                                                                            </span>
                                                                            </span>
                                                                        </a>
                                                                        <a href="#" class="list-group-item">
                                                                            <span class="media">
                                                                        <img src="MelisDesign/images/people/80/15.jpg" alt="" width="35" class="thumb img-fluid rounded-circle float-left" />
                                                                        <span class="media-body media-body-inline">
                                                                            <span class="label label-inverse label-stroke float-right">15 Oct</span>
                                                                            <h4 class="">Laboriosam Maxime <i class="icon-flag text-primary icon-2x"></i></h4>
                                                                            <p class="list-group-item-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, libero </p>
                                                                            </span>
                                                                            </span>
                                                                        </a>

                                                                    </div>
                                                                    <!-- // END list-group -->
                                                                </div>
                                                                <!-- // END col-app -->
                                                            </div>
                                                            <!-- // END col-app -->
                                                        </div>
                                                        <!-- // END col-table-row -->
                                                    </div>
                                                    <!-- // END col-table -->
                                                </div>
                                                <!-- // END col-separator -->
                                            </div>
                                            <!-- // END col -->

                                            <div class="col-md-8 box inbox-scrollable">
                                                <div class="col-separator col-separator-last">
                                                    <div class="innerAll border-bottom">
                                                        <div class="email-content">
                                                            <div class="float-right btn-group btn-group-sm">
                                                                <a href="#" class="btn btn-default"><i class="fa fa-reply"></i></a><a href="#" class="btn btn-default"><i class="fa fa-forward"></i></a><a href="#" class="btn btn-primary"><i class="fa fa-trash-o"></i></a>
                                                            </div>
                                                            <div class="from">
                                                                <a href="#">John Doe</a> <span>(contact@mycompany.biz)</span>
                                                                <div class="clearfix"></div>
                                                                <span>To: your@email.com</span>
                                                            </div>
                                                            <strong>RE: Web Development Quotation</strong>
                                                        </div>
                                                    </div>
                                                    <div class="innerAll">
                                                        <div class="innerAll">
                                                            <p>Hi John,</p>
                                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, libero corporis ipsam voluptatibus suscipit eos expedita sapiente omnis voluptatum ea! Culpa, vitae eaque quis modi voluptatum quisquam ullam. Modi, tempora!</p>
                                                            <p class="text-muted margin-none">Regards,
                                                                <br/>mycompany </br>Director @ mycompany.biz</br>www.mycompany.biz</p>
                                                        </div>
                                                    </div>
                                                    <div class="innerAll border-top">
                                                        <p class="margin-none innerAll text-faded"><i class="fa fa-quote-left fa-4x float-left"></i> Aliquam rutrum, sem at scelerisque tempor, nulla diam pulvinar tortor, id pulvinar massa velit eu purus. Curabitur eu fringilla diam, sed suscipit lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras iaculis enim vel odio imperdiet faucibus. Aliquam erat volutpat.</p>
                                                    </div>
                                                    <div class="innerAll bg-gray border-top">
                                                        <div class="media inline-block margin-none">
                                                            <div class="innerLR">
                                                                <i class="fa fa-paperclip float-left fa-2x"></i>
                                                                <div class="media-body">
                                                                    <div><a href="" class="strong text-regular">Project.zip</a>
                                                                    </div>
                                                                    <span>15 MB</span>
                                                                </div>
                                                                <div class="clearfix"></div>
                                                            </div>
                                                        </div>
                                                        <div class="media inline-block margin-none">
                                                            <div class="innerLR border-left">
                                                                <i class="fa fa-file float-left fa-2x"></i>
                                                                <div class="media-body">
                                                                    <div><a href="" class="strong text-regular">Contract.pdf</a>
                                                                    </div>
                                                                    <span>244 KB</span>
                                                                </div>
                                                                <div class="clearfix"></div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-separator-h box"></div>

                                                    <div class="innerAll border-bottom">
                                                        <div class="email-content">
                                                            <div class="float-right btn-group btn-group-sm">
                                                                <a href="#" class="btn btn-default"><i class="fa fa-reply"></i></a><a href="#" class="btn btn-default"><i class="fa fa-forward"></i></a><a href="#" class="btn btn-primary"><i class="fa fa-trash-o"></i></a>
                                                            </div>
                                                            <div class="from">
                                                                <a href="#">John Doe</a> <span>(contact@mycompany.biz)</span>
                                                                <div class="clearfix"></div>
                                                                <span>To: your@email.com</span>
                                                            </div>
                                                            <strong>Subject Line Goes Here</strong>
                                                        </div>
                                                    </div>
                                                    <div class="innerAll">
                                                        <div class="innerAll">
                                                            <p>Hi John,</p>
                                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, libero corporis ipsam voluptatibus suscipit eos expedita sapiente omnis voluptatum ea! Culpa, vitae eaque quis modi voluptatum quisquam ullam. Modi, tempora!</p>
                                                            <p class="text-muted margin-none">Regards,
                                                                <br/>mycompany </br>Director @ mycompany.biz</br>www.mycompany.biz</p>
                                                        </div>
                                                    </div>
                                                    <div class="col-separator-h box"></div>

                                                    <div class="innerAll border-bottom">
                                                        <div class="email-content">
                                                            <div class="float-right btn-group btn-group-sm">
                                                                <a href="#" class="btn btn-default"><i class="fa fa-reply"></i></a><a href="#" class="btn btn-default"><i class="fa fa-forward"></i></a><a href="#" class="btn btn-primary"><i class="fa fa-trash-o"></i></a>
                                                            </div>
                                                            <div class="from">
                                                                <a href="#">John Doe</a> <span>(contact@mycompany.biz)</span>
                                                                <div class="clearfix"></div>
                                                                <span>To: your@email.com</span>
                                                            </div>
                                                            <strong>Subject Line Goes Here</strong>
                                                        </div>
                                                    </div>
                                                    <div class="innerAll">
                                                        <div class="innerAll">
                                                            <p>Hi John,</p>
                                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, libero corporis ipsam voluptatibus suscipit eos expedita sapiente omnis voluptatum ea! Culpa, vitae eaque quis modi voluptatum quisquam ullam. Modi, tempora!</p>
                                                            <p class="text-muted margin-none">Regards,
                                                                <br/>mycompany </br>Director @ mycompany.biz</br>www.mycompany.biz</p>
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                            <!-- end col 2 -->

                                        </div>

                                    </div>

                                </div>
                            </div>

                        </div>

                    </div>

                </div>
            </div>
        </div>





    </div>
    <!-- // Content END -->

    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->