<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;
        
?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    
    <div id="content">

        <h1 class="bg-white content-heading border-bottom">PRICING TABLES</h1>
        <div class="innerAll">


            <div class="table-pricing-3">
                <ul class="list-unstyled row">
                    <li class="col-md-4">
                        <div class="innerAll">
                            <h3>Starter</h3>
                            <div class="body">
                                <div class="price">
                                    Free
                                </div>
                            </div>
                            <div class="features">
                                <ul>
                                    <li>Basic Support</li>
                                    <li>Unlimited Email Alerts</li>
                                    <li>Free Weekly Digests</li>
                                    <li><strong>5 Email</strong> Templates</li>
                                    <li>Customizable Profile Page</li>
                                    <li><strong>2 months</strong> listing</li>
                                </ul>
                            </div>
                            <div class="footer">
                                <a href="#" class="btn btn-success">Get Started</a>
                            </div>
                        </div>
                    </li>
                    <li class="col-md-4 active">
                        <div class="innerAll">
                            <h3>Silver</h3>
                            <div class="body">
                                <div class="price">
                                    <span class="figure">&euro;19.99</span>
                                    <span class="term">per month</span>
                                </div>
                            </div>
                            <div class="features">
                                <ul>
                                    <li>Dedicated Support</li>
                                    <li>Unlimited Email Alerts</li>
                                    <li>Free Weekly Digests</li>
                                    <li><strong>20 Email</strong> Templates</li>
                                    <li>Customizable Profile Page</li>
                                    <li><strong>6 months</strong> listing</li>
                                </ul>
                            </div>
                            <div class="footer">
                                <a href="#" class="btn btn-success">Get Started</a>
                            </div>
                        </div>
                    </li>
                    <li class="col-md-4">
                        <div class="innerAll">
                            <h3>Gold</h3>
                            <div class="body">
                                <div class="price">
                                    <span class="figure">&euro;49</span>
                                    <span class="term">per month</span>
                                </div>
                            </div>
                            <div class="features">
                                <ul>
                                    <li>Premium Support</li>
                                    <li>Unlimited Email Alerts</li>
                                    <li>Free Weekly Digests</li>
                                    <li><strong>50 Email</strong> Templates</li>
                                    <li>Customizable Profile Page</li>
                                    <li><strong>Lifetime</strong> listing</li>
                                </ul>
                            </div>
                            <div class="footer">
                                <a href="#" class="btn btn-success">Get Started</a>
                            </div>
                        </div>
                    </li>
                    <div class="clearfix"></div>
                </ul>
            </div>


            <div class="widget">
                <!-- Pricing table -->
                <table class="table table-white table-vertical-center table-pricing">

                    <!-- Table heading -->
                    <thead>
                        <tr>
                            <th class="center heading">Choose your plan</th>
                            <th class="center" style="width: 15%">
                                <span class="plan">Free</span>
                                <span class="price">&dollar;0.00</span>
                                <div class="separator bottom"></div>
                                <button class="btn btn-primary btn-block">Sign up</button>
                            </th>
                            <th class="center" style="width: 15%">
                                <span class="plan">Bronze</span>
                                <span class="price">&dollar;9.99</span>
                                <div class="separator bottom"></div>
                                <button class="btn btn-primary btn-block">Sign up</button>
                            </th>
                            <th class="center" style="width: 15%">
                                <span class="plan">Silver</span>
                                <span class="price">&dollar;19.99</span>
                                <div class="separator bottom"></div>
                                <button class="btn btn-primary btn-block">Sign up</button>
                            </th>
                            <th class="center" style="width: 15%">
                                <span class="plan">Gold</span>
                                <span class="price">&dollar;49.99</span>
                                <div class="separator bottom"></div>
                                <button class="btn btn-primary btn-block">Sign up</button>
                            </th>
                        </tr>
                    </thead>
                    <!-- // Table heading END -->

                    <!-- Table body -->
                    <tbody>

                        <!-- Table row -->
                        <tr>
                            <td>Setup &amp; Installation</td>
                            <td class="center"><span class="glyphicons standard circle_ok"><i></i></span>
                            </td>
                            <td class="center"><span class="glyphicons standard circle_ok"><i></i></span>
                            </td>
                            <td class="center"><span class="glyphicons standard circle_ok"><i></i></span>
                            </td>
                            <td class="center"><span class="glyphicons standard circle_ok"><i></i></span>
                            </td>
                        </tr>
                        <!-- // Table row END -->

                        <!-- Table row -->
                        <tr>
                            <td>HTML Templates</td>
                            <td class="center"><span class="glyphicons standard remove_2"><i></i></span>
                            </td>
                            <td class="center"><span class="glyphicons standard remove_2"><i></i></span>
                            </td>
                            <td class="center"><span class="glyphicons standard circle_ok"><i></i></span>
                            </td>
                            <td class="center"><span class="glyphicons standard circle_ok"><i></i></span>
                            </td>
                        </tr>
                        <!-- // Table row END -->

                        <!-- Table row -->
                        <tr>
                            <td>SMS Templates</td>
                            <td class="center"><span class="glyphicons standard circle_ok"><i></i></span>
                            </td>
                            <td class="center"><span class="glyphicons standard circle_ok"><i></i></span>
                            </td>
                            <td class="center"><span class="glyphicons standard circle_ok"><i></i></span>
                            </td>
                            <td class="center"><span class="glyphicons standard circle_ok"><i></i></span>
                            </td>
                        </tr>
                        <!-- // Table row END -->

                        <!-- Table row -->
                        <tr>
                            <td>API Included</td>
                            <td class="center"><span class="glyphicons standard remove_2"><i></i></span>
                            </td>
                            <td class="center"><span class="glyphicons standard circle_ok"><i></i></span>
                            </td>
                            <td class="center"><span class="glyphicons standard circle_ok"><i></i></span>
                            </td>
                            <td class="center"><span class="glyphicons standard circle_ok"><i></i></span>
                            </td>
                        </tr>
                        <!-- // Table row END -->

                        <!-- Table row -->
                        <tr>
                            <td>Tracking System</td>
                            <td class="center">Basic Tracking</td>
                            <td class="center"><span class="glyphicons standard circle_ok"><i></i></span>
                            </td>
                            <td class="center"><span class="glyphicons standard circle_ok"><i></i></span>
                            </td>
                            <td class="center"><span class="glyphicons standard circle_ok"><i></i></span>
                            </td>
                        </tr>
                        <!-- // Table row END -->

                    </tbody>
                    <!-- // Table body END -->

                </table>
                <!-- // Pricing table END -->


            </div>
            <div class="widget">
                <!-- Pricing table -->
                <table class="table table-vertical-center table-pricing table-pricing-2">

                    <!-- Table heading -->
                    <thead>
                        <tr>
                            <th class="center">Free Plan</th>
                            <th class="center">Bronze Plan</th>
                            <th class="center">Silver Plan</th>
                            <th class="center">Gold Plan</th>
                        </tr>
                    </thead>
                    <!-- // Table heading END -->

                    <!-- Table body -->
                    <tbody>

                        <!-- Table pricing row -->
                        <tr class="pricing">
                            <td class="center">
                                <span class="price">&dollar;0.00</span>
                                <span>per month</span>
                            </td>
                            <td class="center">
                                <span class="price">&dollar;9.99</span>
                                <span>per month</span>
                            </td>
                            <td class="center">
                                <span class="price">&dollar;19.99</span>
                                <span>per month</span>
                            </td>
                            <td class="center">
                                <span class="price">&dollar;49.99</span>
                                <span>per month</span>
                            </td>
                        </tr>
                        <!-- // Table pricing row END -->

                        <!-- Table row -->
                        <tr>
                            <td class="center">
                                Setup &amp; Installation
                                <br/> HTML Templates
                                <br/> SMS Templates
                                <br/> API Included
                                <br/> Tracking system
                                <div class="separator bottom"></div>
                                <button class="btn btn-primary">Sign up</button>
                            </td>
                            <td class="center">
                                Setup &amp; Installation
                                <br/> HTML Templates
                                <br/> SMS Templates
                                <br/> API Included
                                <br/> Tracking system
                                <div class="separator bottom"></div>
                                <button class="btn btn-primary">Sign up</button>
                            </td>
                            <td class="center">
                                Setup &amp; Installation
                                <br/> HTML Templates
                                <br/> SMS Templates
                                <br/> API Included
                                <br/> Tracking system
                                <div class="separator bottom"></div>
                                <button class="btn btn-primary">Sign up</button>
                            </td>
                            <td class="center">
                                Setup &amp; Installation
                                <br/> HTML Templates
                                <br/> SMS Templates
                                <br/> API Included
                                <br/> Tracking system
                                <div class="separator bottom"></div>
                                <button class="btn btn-primary">Sign up</button>
                            </td>
                        </tr>
                        <!-- // Table row END -->

                    </tbody>
                    <!-- // Table body END -->

                </table>
                <!-- // Pricing table END -->


            </div>

            <div class="row">
                <div class="col-md-4 col-md-offset-2">
                    <div class="innerAll">
                        <div class="pricing-table default">
                            <ul class="list-group">
                                <li class="list-group-item innerAll inner-2x">
                                    <h2>Regular licence</h2>
                                    <span class="innerT text-primary text-xlarge">&euro;35</span>
                                </li>
                                <li class="list-group-item innerAll inner-2x">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam, sequi, veniam, quasi adipisci sint explicabo exercitationem vel magnam doloribus error odio quibusdam est impedit ut obcaecati minus fugit nesciunt deserunt.</li>
                                <li class="list-group-item innerAll inner-2x"><a class="btn btn-primary btn-lg"><i class="fa fa-fw fa-download"></i> Purchase</a>
                                </li>
                            </ul>
                        </div>

                    </div>
                </div>
                <div class="col-md-4">
                    <div class="innerAll">
                        <div class="pricing-table primary">
                            <ul class="list-group">
                                <li class="list-group-item innerAll inner-2x">
                                    <h2>Extended licence</h2>
                                    <span class="innerT text-xlarge">&euro;1050</span>
                                </li>
                                <li class="list-group-item innerAll inner-2x">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam, sequi, veniam, quasi adipisci sint explicabo exercitationem vel magnam doloribus error odio quibusdam est impedit ut obcaecati minus fugit nesciunt deserunt.</li>
                                <li class="list-group-item innerAll inner-2x"><a class="btn btn-default btn-lg"><i class="fa fa-fw fa-download"></i> Purchase</a>
                                </li>
                            </ul>
                            <div class="caret"></div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- // END row-app -->
    </div>
    <!-- // Content END -->
        
    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->
