<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
	<div id="content" class="render-modals modals">
	    <h1 class="bg-white content-heading border-bottom">Modals</h1>
	    <div class="innerAll spacing-2x">

	        <div class="widget widget-inverse">
	            <div class="widget-head">
	                <h4 class="heading">Account <span>Modal Examples</span></h4>
	            </div>
	            <div class="widget-body">
	                <!-- Form Modal 1 -->
	                <a href="#modal-login" data-toggle="modal" class="btn btn-primary"><i class="fa fa-fw fa-user"></i> Modal Login Form</a>

	                <!-- Modal -->
	                <div class="modal fade" id="modal-login">

	                    <div class="modal-dialog">
	                        <div class="modal-content">

	                            <!-- Modal heading -->
	                            <div class="modal-header">
	                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	                                <h3 class="modal-title">Login</h3>
	                            </div>
	                            <!-- // Modal heading END -->

	                            <!-- Modal body -->
	                            <div class="modal-body">
	                                <div class="innerAll">
	                                    <div class="innerLR">
	                                        <form class="form-horizontal" role="form">
	                                            <div class="form-group d-flex">
	                                                <label class="col-sm-2 control-label">User</label>
	                                                <div class="col-sm-10">
	                                                    <p class="form-control-static">mycompany</p>
	                                                </div>
	                                            </div>
	                                            <div class="form-group d-flex">
	                                                <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
	                                                <div class="col-sm-10">
	                                                    <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
	                                                </div>
	                                            </div>
	                                            <div class="form-group d-flex">
	                                                <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
	                                                <div class="col-sm-10">
	                                                    <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
	                                                </div>
	                                            </div>
	                                            <div class="form-group d-flex">
	                                                <div class="offset-sm-2 col-sm-10">
	                                                    <div class="checkbox">
	                                                        <label class="checkbox-custom">
	                                                            <i class="fa fa-fw fa-square-o"></i>
	                                                            <input type="checkbox" checked="checked"> Remember me
	                                                        </label>
	                                                    </div>
	                                                </div>
	                                            </div>
	                                            <div class="form-group d-flex">
	                                                <div class="offset-sm-2 col-sm-10">
	                                                    <button type="submit" class="btn btn-primary">Sign in</button>
	                                                </div>
	                                            </div>
	                                        </form>
	                                    </div>
	                                </div>
	                            </div>
	                            <!-- // Modal body END -->

	                        </div>
	                    </div>

	                </div>
	                <!-- // Modal END -->




	            </div>
	        </div>

	        <div class="widget widget-inverse">
	            <div class="widget-head">
	                <h4 class="heading">Email <span>Modal Examples</span></h4>
	            </div>
	            <div class="widget-body">
	                <!-- Form Modal 1 -->
	                <a href="#modal-compose" data-toggle="modal" class="btn btn-success btn-regular"><i class="fa fa-fw fa-envelope"></i> Compose Email Modal</a>

	                <!-- Modal -->
	                <div class="modal fade" id="modal-compose">

	                    <div class="modal-dialog">
	                        <div class="modal-content">

	                            <!-- Modal heading -->
	                            <!-- <div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h3 class="modal-title">Login</h3>
				</div> -->
	                            <!-- // Modal heading END -->

	                            <div class="innerAll border-bottom">
	                                <div class="float-left">
	                                    <a href="" class=" btn btn-default btn-sm"><i class="fa fa-fw fa-arrow-left"></i> back</a>
	                                </div>
	                                <div class="float-left innerL">
	                                    <a href="" class=" btn btn-success btn-sm strong btn-regular"><i class="fa fa-fw icon-paperclip"></i> Save Draft</a>
	                                </div>
	                                <a href="" class="float-right btn btn-primary btn-sm strong"><i class="fa fa-fw icon-outbox-fill"></i> Send Email</a>
	                                <div class="clearfix"></div>
	                            </div>

	                            <!-- Modal body -->
	                            <div class="modal-body padding-none">

	                                <form class="form-horizontal" role="form">
	                                    <div class="bg-gray innerAll border-bottom">
	                                        <div class="innerLR">
	                                            <div class="form-group d-flex">
	                                                <label for="to" class="col-sm-2 control-label control-label-to">To:</label>
	                                                <div class="col-sm-10">
	                                                    <div class="input-group">
	                                                        <input type="text" class="form-control" id="to">
	                                                        <div class="input-group-btn">
	                                                            <button type="button" data-toggle="collapse" data-target="#cc" class="btn btn-default">CC/BCC <span class="caret"></span>
	                                                            </button>
	                                                        </div>
	                                                    </div>
	                                                </div>
	                                            </div>
	                                            <div id="cc" class="collapse">
	                                                <div class="form-group d-flex">
	                                                    <label for="Cc" class="col-sm-2 control-label">Cc:</label>
	                                                    <div class="col-sm-10">
	                                                        <input type="text" class="form-control" id="Cc">
	                                                    </div>
	                                                </div>
	                                                <div class="form-group d-flex">
	                                                    <label for="Bcc" class="col-sm-2 control-label">Bcc:</label>
	                                                    <div class="col-sm-10">
	                                                        <input type="text" class="form-control" id="Bcc">
	                                                    </div>
	                                                </div>
	                                            </div>
	                                            <div class="form-group d-flex">
	                                                <label for="Bcc" class="col-sm-2 control-label">From:</label>
	                                                <div class="col-sm-6">
	                                                    <select class="selectpicker">
	                                                        <option>contact@mycompany.biz</option>
	                                                    </select>
	                                                </div>

	                                            </div>

	                                            <div class="form-group d-flex">
	                                                <label for="Bcc" class="col-sm-2 control-label">Signature:</label>
	                                                <div class="col-sm-6">
	                                                    <select class="selectpicker">
	                                                        <option>Select Signature</option>
	                                                    </select>
	                                                </div>
	                                            </div>
	                                            <div class="clearfix"></div>
	                                        </div>
	                                    </div>

	                                    <div class="innerAll inner-2x">
	                                        <textarea class="notebook border-none form-control padding-none" rows="4" placeholder="Write your content here..."></textarea>
	                                        <div class="clearfix"></div>
	                                    </div>
	                                </form>

	                            </div>
	                            <!-- // Modal body END -->

	                            <div class="innerAll text-center border-top">
	                                <a href="" class="btn btn-default"><i class="fa fa-fw icon-crossing"></i> Cancel</a>
	                                <a href="" class="btn btn-primary"><i class="fa fa-fw icon-outbox-fill"></i> Send email</a>
	                            </div>

	                        </div>
	                    </div>

	                </div>
	                <!-- // Modal END -->


	            </div>
	        </div>


	        <div class="widget widget-inverse">
	            <div class="widget-head">
	                <h4 class="heading">Form Wizards <span>Modal Examples</span></h4>
	            </div>
	            <div class="widget-body">
	                <!-- Form Modal 2 -->
	                <a href="#modal-2" data-toggle="modal" class="btn btn-info btn-regular"><i class="fa fa-fw fa-magic"></i> Modal Wizard Example 1</a>

	                <!-- Modal -->
	                <div class="modal fade" id="modal-2">

	                    <div class="modal-dialog">
	                        <div class="modal-content">

	                            <!-- Modal body -->
	                            <div class="modal-body padding-none">

	                                <!-- Form Wizard / Widget Tabs / Double Style -->
	                                <div class="wizard wizard-design">
	                                    <div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">

	                                        <!-- Widget heading -->
	                                        <div class="widget-head bg-gray">
	                                            <ul class="nav nav-tabs">
	                                                <li class="nav-item active">
														<a href="#tab1-2" class="nav-link glyphicons user" data-toggle="tab"><i></i><span class="strong">Step 1</span><span>Personal details</span></a>
	                                                </li>
	                                                <li class="nav-item">
														<a href="#tab2-2" class="nav-link glyphicons calculator" data-toggle="tab"><i></i><span class="strong">Step 2</span><span>Billing details</span></a>
	                                                </li>
	                                                <li class="nav-item">
														<a href="#tab3-2" class="nav-link glyphicons credit_card" data-toggle="tab"><i></i><span class="strong">Step 3</span><span>Payment</span></a>
	                                                </li>
	                                                <li class="nav-item">
														<a href="#tab4-2" class="nav-link glyphicons circle_ok" data-toggle="tab"><i></i><span class="strong">Step 4</span><span>Confirmation</span></a>
	                                                </li>
	                                            </ul>
	                                        </div>
	                                        <!-- // Widget heading END -->

	                                        <div class="widget-body innerAll inner-2x">
	                                            <div class="tab-content">

	                                                <!-- Step 1 -->
	                                                <div class="tab-pane active" id="tab1-2">
	                                                    <div class="row">
	                                                        <div class="col-md-3">
	                                                            <strong>Product title</strong>
	                                                            <p class="muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
	                                                        </div>
	                                                        <div class="col-md-9">
	                                                            <label for="inputTitle">Title</label>
	                                                            <input type="text" id="inputTitle" class="col-md-6 form-control" value="" placeholder="Enter product title ..." />
	                                                            <div class="separator"></div>
	                                                        </div>
	                                                    </div>
	                                                </div>
	                                                <!-- // Step 1 END -->

	                                                <!-- Step 2 -->
	                                                <div class="tab-pane" id="tab2-2">
	                                                    <div class="row">
	                                                        <div class="col-md-3">
	                                                            <strong>Description</strong>
	                                                            <p class="muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
	                                                        </div>
	                                                        <div class="col-md-9">
	                                                            <label for="textDescription">Description</label>
	                                                            <textarea id="textDescription" class="wysihtml5 form-control" style="width: 96%;" rows="5">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.</textarea>
	                                                        </div>
	                                                    </div>
	                                                </div>
	                                                <!-- // Step 2 END -->

	                                                <!-- Step 3 -->
	                                                <div class="tab-pane" id="tab3-2">
	                                                    <h4>Third tab</h4>
	                                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
	                                                </div>
	                                                <!-- // Step 3 END -->

	                                                <!-- Step 4 -->
	                                                <div class="tab-pane" id="tab4-2">
	                                                    <h4>Fourth tab</h4>
	                                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
	                                                </div>
	                                                <!-- // Step 4 END -->

	                                            </div>

	                                            <!-- Wizard pagination controls -->
	                                            <ul class="pagination margin-bottom-none">
	                                                <li class="page-item primary previous first">
														<a href="#" class="page-link no-ajaxify">First</a>
	                                                </li>
	                                                <li class="page-item primary previous">
														<a href="#" class="page-link no-ajaxify">Previous</a>
	                                                </li>
	                                                <li class="page-item last primary">
														<a href="#" class="page-link no-ajaxify">Last</a>
	                                                </li>
	                                                <li class="page-item next primary">
														<a href="#" class="page-link no-ajaxify">Next</a>
	                                                </li>
													<li class="page-item next finish primary" style="display:none;">
														<a href="#" class="page-link no-ajaxify">Finish</a>
	                                                </li>
	                                            </ul>
	                                            <!-- // Wizard pagination controls END -->

	                                        </div>
	                                    </div>
	                                </div>
	                                <!-- // Form Wizard / Widget Tabs / Double Style END -->

	                            </div>
	                            <!-- // Modal body END -->
	                            <div class="modal-footer center margin-none">
	                                <a href="#" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</a>
	                            </div>
	                        </div>
	                    </div>

	                </div>
	                <!-- // Modal END -->





	                <!-- Form Modal 3 -->
	                <a href="#modal-3" data-toggle="modal" class="btn btn-inverse"><i class="fa fa-fw fa-magic"></i> Modal Wizard Example 2</a>

	                <!-- Modal -->
	                <div class="modal fade" id="modal-3">

	                    <div class="modal-dialog">
	                        <div class="modal-content">

	                            <!-- Modal body -->
	                            <div class="modal-body padding-none">

	                                <!-- Form Wizard / Widget Pills -->
	                                <div class="wizard wizard-design">
	                                    <div class="widget margin-none border-none widget-tabs widget-wizard-pills widget-tabs-responsive">

	                                        <!-- Widget heading -->
	                                        <div class="widget-head bg-gray widget-steps-head">
	                                            <ul class="nav nav-tabs">
	                                                <li class="nav-item status">
														<span class="r">Step <span class="step-current">2</span> of <span class="steps-total">5</span></span><span class="r text-primary">Completed: <span class="steps-complete">1</span></span>
	                                                </li>
	                                                <li class="nav-item active no-padding">
														<a class="nav-link" href="#tab1-3" data-toggle="tab">1</a>
	                                                </li>
	                                                <li class="nav-item">
														<a class="nav-link" href="#tab2-3" data-toggle="tab">2</a>
	                                                </li>
	                                                <li class="nav-item">
														<a class="nav-link" href="#tab3-3" data-toggle="tab">3</a>
	                                                </li>
	                                                <li class="nav-item">
														<a class="nav-link" href="#tab4-3" data-toggle="tab">4</a>
	                                                </li>
	                                            </ul>
	                                        </div>
	                                        <!-- // Widget heading END -->

	                                        <div class="widget-body innerAll inner-2x">
	                                            <div class="tab-content">

	                                                <!-- Step 1 -->
	                                                <div class="tab-pane active" id="tab1-3">
	                                                    <div class="row">
	                                                        <div class="col-md-3">
	                                                            <strong>Product title</strong>
	                                                            <p class="muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
	                                                        </div>
	                                                        <div class="col-md-9">
	                                                            <label for="inputTitle">Title</label>
	                                                            <input type="text" id="inputTitle" class="col-md-6 form-control" value="" placeholder="Enter product title ..." />
	                                                            <div class="separator"></div>
	                                                        </div>
	                                                    </div>
	                                                </div>
	                                                <!-- // Step 1 END -->

	                                                <!-- Step 2 -->
	                                                <div class="tab-pane" id="tab2-3">
	                                                    <div class="row">
	                                                        <div class="col-md-3">
	                                                            <strong>Description</strong>
	                                                            <p class="muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
	                                                        </div>
	                                                        <div class="col-md-9">
	                                                            <label for="textDescription">Description</label>
	                                                            <textarea id="textDescription" class="wysihtml5 form-control" style="width: 96%;" rows="5">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.</textarea>
	                                                        </div>
	                                                    </div>
	                                                </div>
	                                                <!-- // Step 2 END -->

	                                                <!-- Step 3 -->
	                                                <div class="tab-pane" id="tab3-3">
	                                                    <h4>Third tab</h4>
	                                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
	                                                </div>
	                                                <!-- // Step 3 END -->

	                                                <!-- Step 4 -->
	                                                <div class="tab-pane" id="tab4-3">
	                                                    <h4>Fourth tab</h4>
	                                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices libero vel massa egestas facilisis. Mauris convallis augue nec dolor dignissim vestibulum. Praesent imperdiet elit posuere arcu posuere consectetur. Morbi dignissim eleifend nibh, eget tincidunt nibh dignissim hendrerit. Cras iaculis congue lorem, eget gravida augue vehicula sed. Nam lorem sem, consectetur ac tempus quis, consectetur ut lectus. In bibendum luctus pharetra. Morbi lacinia sem sem. Phasellus quis tellus magna.</p>
	                                                </div>
	                                                <!-- // Step 4 END -->

	                                            </div>

	                                            <!-- Wizard pagination controls -->
	                                            <ul class="pagination margin-bottom-none float-left">
	                                                <li class="page-item primary previous first">
														<a href="#" class="page-link no-ajaxify">First</a>
	                                                </li>
	                                                <li class="page-item last primary">
														<a href="#" class="page-link no-ajaxify">Last</a>
	                                                </li>
	                                            </ul>
	                                            <ul class="pagination margin-bottom-none float-right">
	                                                <li class="page-item primary previous">
														<a href="#" class="page-link no-ajaxify">Previous</a>
	                                                </li>
	                                                <li class="page-item next primary">
														<a href="#" class="page-link no-ajaxify">Next</a>
	                                                </li>
													<li class="page-item next finish primary" style="display:none;">
														<a href="#" class="page-link no-ajaxify">Finish</a>
	                                                </li>
	                                            </ul>
	                                            <div class="clearfix"></div>
	                                            <!-- // Wizard pagination controls END -->

	                                        </div>
	                                    </div>
	                                </div>
	                                <!-- // Form Wizard / Widget Pills END -->

	                            </div>
	                            <!-- // Modal body END -->

	                        </div>
	                    </div>

	                </div>
	                <!-- // Modal END -->
	            </div>
	        </div>

	        <div class="widget widget-inverse">
	            <div class="widget-head">
	                <h4 class="heading">Other <span>Modal Examples</span></h4>
	            </div>
	            <div class="widget-body">
	                <!-- Form Modal 1 -->
	                <a href="#modal-credit-card" data-toggle="modal" class="btn btn-success btn-regular"> <i class="fa fa-fw fa-credit-card"></i> Modal Credit Card</a>

	                <!-- Modal -->
	                <div class="modal fade" id="modal-credit-card">

	                    <div class="modal-dialog">
	                        <div class="modal-content">

	                            <!-- Modal heading -->
	                            <div class="modal-header">
	                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	                                <h3 class="modal-title">Payment</h3>
	                            </div>
	                            <!-- // Modal heading END -->

	                            <!-- Modal body -->
	                            <div class="modal-body">

	                                <div class="innerAll">
	                                    <form class="margin-none innerLR inner-2x">
	                                        <div class="form-group">
	                                            <label for="exampleInputEmail1">Cardholder Name</label>
	                                            <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Name on Card">
	                                        </div>
	                                        <div class="form-group">
	                                            <label for="exampleInputEmail1">Card Number</label>
	                                            <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter Card Number">
	                                        </div>
	                                        <div class="form-group">
	                                            <label for="exampleInputPassword1">Expiry Date</label>
	                                            <div class="row">
	                                                <div class="col-md-3">
	                                                    <select class="form-control selectpicker">
	                                                        <option>1</option>
	                                                        <option>2</option>
	                                                        <option>3</option>
	                                                        <option>4</option>
	                                                        <option>5</option>
	                                                        <option>6</option>
	                                                        <option>7</option>
	                                                        <option>8</option>
	                                                        <option>9</option>
	                                                        <option>10</option>
	                                                        <option>11</option>
	                                                    </select>
	                                                </div>
	                                                <div class="col-md-3">
	                                                    <select class="form-control selectpicker">
	                                                        <option>2013</option>
	                                                        <option>2014</option>
	                                                        <option>2015</option>
	                                                        <option>2016</option>
	                                                        <option>2017</option>
	                                                        <option>2018</option>
	                                                    </select>
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <div class="form-group">
	                                            <label for="exampleInputPassword1">Security Code <i class="fa fa-question-circle"></i>
	                                            </label>
	                                            <div class="row">
	                                                <div class="col-md-6">
	                                                    <input type="password" class="form-control" placeholder="CVV / CVV2">
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <div class="text-center innerAll">
	                                            <a href="" class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Make Payment</a>
	                                        </div>
	                                    </form>
	                                </div>

	                            </div>
	                            <!-- // Modal body END -->

	                        </div>
	                    </div>

	                </div>
	                <!-- // Modal END -->




	            </div>
	        </div>

	        <div class="widget">
	            <div class="widget-head">
	                <h4 class="heading">Bootbox <span>Manage modals with JavaScript API</span></h4>
	            </div>
	            <div class="widget-body">
	                <button id="modals-bootbox-alert" class="btn btn-primary">Alert</button>
	                <button id="modals-bootbox-confirm" class="btn btn-primary">Confirm</button>
	                <button id="modals-bootbox-prompt" class="btn btn-primary">Prompt</button>
	                <button id="modals-bootbox-custom" class="btn btn-primary">Custom Dialog</button>
	            </div>
	        </div>




	        <!-- Modal inline -->
	        <div class="modal modal-inline">
	            <div class="modal-dialog">
	                <div class="modal-content">

	                    <!-- Modal heading -->
	                    <div class="modal-header">
	                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	                        <h4 class="modal-title">Modal header</h4>
	                    </div>
	                    <!-- // Modal heading END -->

	                    <!-- Modal body -->
	                    <div class="modal-body">
	                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
	                    </div>
	                    <!-- // Modal body END -->

	                    <!-- Modal footer -->
	                    <div class="modal-footer">
	                        <a href="#" class="btn btn-default btn-regular">Just a button</a>
	                        <a href="#modal-simple" data-toggle="modal" class="btn btn-primary">Open Live Modal</a>
	                    </div>
	                    <!-- // Modal footer END -->

	                </div>
	            </div>

	        </div>

	        <!-- Modal -->
	        <div class="modal fade" id="modal-simple">

	            <div class="modal-dialog">
	                <div class="modal-content">

	                    <!-- Modal heading -->
	                    <div class="modal-header">
	                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	                        <h3 class="modal-title">Modal header</h3>
	                    </div>
	                    <!-- // Modal heading END -->

	                    <!-- Modal body -->
	                    <div class="modal-body">
	                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
	                    </div>
	                    <!-- // Modal body END -->

	                    <!-- Modal footer -->
	                    <div class="modal-footer">
	                        <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
	                        <a href="#" data-dismiss="modal" class="btn btn-primary">Save changes</a>
	                    </div>
	                    <!-- // Modal footer END -->

	                </div>
	            </div>

	        </div>
	        <!-- // Modal END -->




	    </div>


	</div>
	<!-- // Content END -->

    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->