<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    <div id="content" class="render-events">
        <div class="heading-buttons bg-white border-bottom innerAll">
            <h1 class="content-heading padding-none float-left">Events</h1>
            <div class="clearfix"></div>
        </div>

        <div class="innerAll spacing-x2">

            <!-- Widget -->
            <div class="row">
                <div class="col-md-6">
                    <div class="widget">
                        <h4 class="innerAll half margin-none border-bottom">Cognitive Science and Design</h4>
                        <div id="events-carousel" class="events-tns">
                            <div class="slide-item">
                                <div class="widget widget-pinterest">
                                    <div class="mark text-center">
                                        <span class="caret caret-primary"></span>
                                        <span class="text">Free</span>
                                    </div>
                                    <div class="widget-body padding-none">
                                        <a href="product.html?lang=en" class="thumb">
                                            <img src="/MelisDesign/images/photodune-5765965-idea-concept-xs.jpg" alt="photo" class="img-fluid" />
                                        </a>
                                        <div class="description">
                                            <h5 class="text-uppercase">Beatae, pariatur, deleniti dolores nobis sint voluptatibus</h5>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea, aliquid, facere provident neque maiores modi quos suscipit maxime quod asperiores porro a iusto laboriosam consectetur perspiciatis corporis recusandae dicta alias.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="slide-item">
                                <div class="widget widget-pinterest">
                                    <div class="mark text-center">
                                        <span class="caret caret-default"></span>
                                        <span class="text">Free</span>
                                    </div>
                                    <div class="widget-body padding-none">
                                        <a href="product.html?lang=en" class="thumb"><img src="/MelisDesign/images/photodune-5557150-creative-head-xs.jpg" alt="photo" class="img-fluid" />
                                        </a>
                                        <div class="description">
                                            <h5 class="text-uppercase">Beatae, pariatur, deleniti dolores nobis sint voluptatibus</h5>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea, aliquid, facere provident neque maiores modi quos suscipit maxime quod asperiores porro a iusto laboriosam consectetur perspiciatis corporis recusandae dicta alias.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr class="margin-none" />
                        <div class="media margin-none innerAll half">
                            <div class="row">
                                <div class="col-md-2">
                                    <div class="float-left">
                                        <!-- data-src="holder.js/50x50" -->
                                        <img src="/MelisDesign/images/thumbnails/company_logo.png" alt="" class="holder-image img-fluid rounded-circle" width="50" height="50" />
                                    </div>
                                </div>
                                <div class="col-md-10">
                                    <div class="media-body ms-0">
                                        <div class="row">
                                            <div class="col-md-10">
                                                <div class="innerAll half media margin-none">
                                                    <div class="row">
                                                        <div class="col-md-4">
                                                            <div class="float-left innerLR half">
                                                                <p class="strong margin-none">Company, Inc</p>
                                                                <p class="margin-none">Official Organizer</p>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-8">
                                                            <div class="media-body border-left innerLR">
                                                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, dicta, odio id cumque voluptates debitis asperiores. Dolorum, quod, cupiditate.
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-2">
                                                <div class="float-right innerAll half">
                                                    <div class="btn-group-vertical btn-group-sm">
                                                        <button class="btn btn-inverse">Follow</button>
                                                        <button class="btn btn-default">Contact</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="widget">
                        <h4 class="bg-primary innerAll half border-bottom margin-none">Event</h4>
                        <div class="innerAll half bg-primary border-bottom">
                            <div class="media innerAll half margin-none">
                                <div class="float-left">
                                    <i class="fa fa-fw fa-calendar fa-3x"></i>
                                </div>
                                <div class="media-body">
                                    <p class="strong lead margin-none">22 DEC 2013</p>
                                    <p class="strong margin-none">1:00 - 5:00 pm</p>
                                </div>
                            </div>
                        </div>
                        <div class="innerAll half bg-gray border-bottom">
                            <div class="media innerAll half margin-none">
                                <div class="float-left">
                                    <i class="fa fa-fw fa-map-marker fa-3x"></i>
                                </div>
                                <div class="media-body">
                                    <p class="strong lead margin-none">San Francisco</p>
                                    <p class="strong margin-none">California, USA</p>
                                </div>
                            </div>
                        </div>
                        <div class="innerAll text-center half">
                            <div class="btn-group">
                                <button class="btn btn-success"><i class="fa fa-fw fa-check"></i> Attend</button>
                                <button class="btn btn-default">I might go</button>
                            </div>
                        </div>
                    </div>
                    <div class="widget">
                        <h4 class="border-bottom margin-none innerAll half">Friends</h4>
                        <div class="border-bottom">
                            <div class="innerAll half">
                                <span class="badge badge-primary float-right">215</span> Attending
                            </div>
                        </div>
                        <div class="border-bottom">
                            <div class="innerAll half">
                                <span class="badge badge-primary badge-stroke float-right">585</span> Might Go
                            </div>
                        </div>
                        <div class="innerAll half text-center">
                            <a href="#" class="border-none">
                                <img src="/MelisDesign/images/people/80/1.jpg" alt="photo" width="35" class="innerB half">
                            </a>
                            <a href="#" class="border-none">
                                <img src="/MelisDesign/images/people/80/2.jpg" alt="photo" width="35" class="innerB half">
                            </a>
                            <a href="#" class="border-none">
                                <img src="/MelisDesign/images/people/80/3.jpg" alt="photo" width="35" class="innerB half">
                            </a>
                            <a href="#" class="border-none">
                                <img src="/MelisDesign/images/people/80/4.jpg" alt="photo" width="35" class="innerB half">
                            </a>
                            <a href="#" class="border-none">
                                <img src="/MelisDesign/images/people/80/5.jpg" alt="photo" width="35" class="innerB half">
                            </a>
                            <a href="#" class="border-none">
                                <img src="/MelisDesign/images/people/80/6.jpg" alt="photo" width="35" class="innerB half">
                            </a>
                            <a href="#" class="border-none">
                                <img src="/MelisDesign/images/people/80/7.jpg" alt="photo" width="35" class="innerB half">
                            </a>
                            <a href="#" class="border-none">
                                <img src="/MelisDesign/images/people/80/8.jpg" alt="photo" width="35" class="innerB half">
                            </a>
                            <a href="#" class="border-none">
                                <img src="/MelisDesign/images/people/80/9.jpg" alt="photo" width="35" class="innerB half">
                            </a>
                            <a href="#" class="border-none">
                                <img src="/MelisDesign/images/people/80/10.jpg" alt="photo" width="35" class="innerB half">
                            </a>
                            <a href="#" class="border-none">
                                <img src="/MelisDesign/images/people/80/11.jpg" alt="photo" width="35" class="innerB half">
                            </a>
                            <a href="#" class="border-none">
                                <img src="/MelisDesign/images/people/80/12.jpg" alt="photo" width="35" class="innerB half">
                            </a>
                            <a href="#" class="border-none">
                                <img src="/MelisDesign/images/people/80/13.jpg" alt="photo" width="35" class="innerB half">
                            </a>
                            <a href="#" class="border-none">
                                <img src="/MelisDesign/images/people/80/14.jpg" alt="photo" width="35" class="innerB half">
                            </a>

                        </div>
                    </div>
                    <div class="widget">
                        <h4 class="bg-inverse margin-none innerAll half">Speakers</h4>
                        <div id="events-speakers" class="speakers-tns">
                            <div class="slide-item">
                                <div class="widget widget-pinterest">
                                    <div class="widget-body padding-none">
                                        <a href="" class="thumb col-md-12">
                                            <img src="/MelisDesign/images/photodune-1949987-male-portrait-s.jpg" alt="photo" class="img-fluid" />
                                        </a>
                                        <div class="description col-md-12">
                                            <h5 class="text-uppercase">Speaker name</h5>
                                            <p class="strong">CEO, Company Inc.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="slide-item">
                                <div class="widget widget-pinterest">
                                    <div class="widget-body padding-none">
                                        <a href="" class="thumb col-md-12">
                                            <img src="/MelisDesign/images/photodune-1555340-indian-male-s.jpg" alt="photo" class="img-fluid" />
                                        </a>
                                        <div class="description col-md-12">
                                            <h5 class="text-uppercase">Speaker name</h5>
                                            <p class="strong">CEO, Company Inc.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-12">
                    <div class="clearfix"></div>
                    <div class="widget">
                        <h4 class="innerAll half margin-none border-bottom">Schedule</h4>
                        <ul class="list-unstyled timeline-appointments margin-none bg-gray">
                            <li>
                                <div class="time">1:00 <span class="text-primary">pm</span>
                                </div>
                                <i class="fa fa-dot-circle-o text-primary dot"></i>
                                <div class="appointments">
                                    <ul class="list-unstyled">
                                        <li>
                                            <div class="apt">
                                                <a href="" class="text-regular strong">Chris Hughes</a>
                                                <br/>Co-founder of Facebook
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            <li>
                                <div class="time">3:00 <span class="text-primary">pm</span>
                                </div>
                                <i class="fa fa-dot-circle-o text-primary dot"></i>
                                <div class="appointments">
                                    <ul class="list-unstyled">
                                        <li>
                                            <div class="apt">
                                                <a href="" class="text-regular strong">Elon Musk</a>
                                                <br/>CEO &amp; CTO of SpaceX
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            <li>
                                <div class="time">5:00 <span class="text-primary">pm</span>
                                </div>
                                <i class="fa fa-dot-circle-o text-primary dot"></i>
                                <div class="appointments">
                                    <ul class="list-unstyled">
                                        <li class="text">
                                            <div class="strong text-regular">Just a note</div>
                                            Lorem ipsum dolor sit amet
                                            <br/>&nbsp;
                                        </li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="widget">
                        <div class="innerAll half border-bottom">
                            <a href="" class="btn btn-primary btn-xs float-right"><i class="fa fa-plus-circle"></i></a>
                            <h4 class="margin-none padding-none">Discussions</h4>
                        </div>

                        <div class="media innerAll half border-bottom margin-none">
                            <a href="" class="float-left"><img src="/MelisDesign/images/people/35/16.jpg" alt="people" class="img-fluid rounded-circle" />
                            </a>
                            <div class="media-body">
                                <small class="strong float-right">3 hours ago</small>
                                <h5>Reinald Lothair</h5>
                                <p class="label label-info">Event Organizer</p>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi, dolorem, ad, aut amet quis sapiente architecto ut corrupti molestiae.</p>
                            </div>
                        </div>
                        <div class="media innerAll half bg-gray border-bottom margin-none">
                            <a href="" class="float-left"><img src="/MelisDesign/images/people/35/15.jpg" alt="people" class="img-fluid rounded-circle" />
                            </a>
                            <div class="media-body">
                                <small class="strong float-right">5 hours ago</small>
                                <h5>Janele Sara</h5>
                                <p class="label label-success">Speaker</p>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi, dolorem, ad, aut amet quis sapiente architecto ut corrupti molestiae.</p>
                            </div>
                        </div>
                        <div class="media innerAll half margin-none">
                            <a href="" class="float-left"><img src="/MelisDesign/images/people/35/17.jpg" alt="people" class="img-fluid rounded-circle" />
                            </a>
                            <div class="media-body">
                                <small class="strong float-right">8 hours ago</small>
                                <h5>Tracie Fedelmid</h5>
                                <p class="label label-danger">Attendee</p>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi, dolorem, ad, aut amet quis sapiente architecto ut corrupti molestiae.</p>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <!--  End Row -->
        </div>
    </div>
    <!-- // Content END -->
    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->
</div>
<!-- // Tab END -->