<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">

	<div id="content">
	    <h1 class="content-heading bg-white border-bottom">Timelines <span>multiple styles</span></h1>

	    <div class="innerAll spacing-x2">
	        <div class="widget widget-inverse">
	            <div class="widget-head">
	                <h4 class="heading"><i class="fa fa-sitemap fa-fw"></i> Mirror Timeline</h4>
	            </div>
	            <div class="widget-body padding-none">

	                <div class="relativeWrap overflow-hidden">
	                    <div class="row row-merge layout-timeline layout-timeline-mirror">
	                        <div class="col-md-6"></div>
	                        <div class="col-md-6">
	                            <div class="innerAll">

	                                <ul class="timeline">
	                                    <li class="active">
	                                        <div class="separator bottom">
	                                            <span class="date box-generic">Now</span>
	                                            <span class="type glyphicons suitcase">Task <i></i><span class="time">08:00</span></span>
	                                            <button type="button" class="btn btn-primary"><i class="fa fa-fw fa-plus-circle"></i> Add event</button>
	                                        </div>
	                                        <div class="widget widget-heading-simple widget-body-white margin-none">
	                                            <div class="widget-body">
	                                                <div class="media">
	                                                    <div class="media-object pull-left thumb"><img src="MelisDesign/images/avatar-51x51.jpg" alt="Image" />
	                                                    </div>
	                                                    <div class="media-body">
	                                                        <a class="author">John Doe</a>
	                                                        <br/>
	                                                        <span class="muted">johndoe@ennovation.ie</span>
	                                                    </div>
	                                                </div>
	                                                <div class="alert alert-gray">
	                                                    <p class="glyphicons circle_info margin-none"><i></i> Added a new milestone named <a href="">MyCompany</a>
	                                                    </p>
	                                                </div>
	                                                <a class="glyphicons single pencil"><i></i></a>
	                                            </div>
	                                        </div>
	                                    </li>
	                                    <li class="active">
	                                        <span class="type glyphicons comments">Comment <i></i><span class="time">11:00</span></span>
	                                        <div class="widget widget-heading-simple widget-body-white margin-none">
	                                            <div class="widget-body">
	                                                <p class="glyphicons user margin-none"><i></i> <strong><a href="">MyCompany</a> said</strong>: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an ...</p>
	                                            </div>
	                                        </div>
	                                    </li>
	                                    <li>
	                                        <div class="separator">
	                                            <span class="date box-generic"><strong>27</strong>may</span>
	                                            <span class="type glyphicons picture">Photo <i></i><span class="time">08:00</span></span>
	                                        </div>
	                                        <div class="widget widget-heading-simple widget-body-white margin-none">
	                                            <div class="widget-body">
	                                                <div class="media">
	                                                    <div class="media-object pull-left thumb"><img src="MelisDesign/images/avatar-51x51.jpg" alt="Image" />
	                                                    </div>
	                                                    <div class="media-body">
	                                                        <a class="author">John Doe</a>
	                                                        <br/>
	                                                        <span class="muted">johndoe@ennovation.ie</span>
	                                                    </div>
	                                                </div>
	                                                <div class="alert alert-gray">
	                                                    <p class="glyphicons circle_info"><i></i> Added photos to the album <a href="">MyCompany</a>
	                                                    </p>

	                                                    <!-- Gallery Layout -->
	                                                    <div class="gallery gallery-2 separator top">
	                                                        <ul class="row" data-toggle="modal-gallery" data-target="#modal-gallery" id="gallery-4" data-delegate="#gallery-4">
	                                                            <li class="col-md-4 hidden-phone">
	                                                                <a class="thumb" href="MelisDesign/images/gallery-2/6.jpg" data-gallery="gallery"><img src="MelisDesign/images/gallery-2/6.jpg" alt="photo" class="img-responsive" />
	                                                                </a>
	                                                            </li>
	                                                            <li class="col-md-4 hidden-phone">
	                                                                <a class="thumb" href="MelisDesign/images/gallery-2/5.jpg" data-gallery="gallery"><img src="MelisDesign/images/gallery-2/5.jpg" alt="photo" class="img-responsive" />
	                                                                </a>
	                                                            </li>
	                                                            <li class="col-md-4 hidden-phone">
	                                                                <a class="thumb" href="MelisDesign/images/gallery-2/4.jpg" data-gallery="gallery"><img src="MelisDesign/images/gallery-2/4.jpg" alt="photo" class="img-responsive" />
	                                                                </a>
	                                                            </li>
	                                                            <li class="col-md-4">
	                                                                <a class="thumb" href="MelisDesign/images/gallery-2/3.jpg" data-gallery="gallery"><img src="MelisDesign/images/gallery-2/3.jpg" alt="photo" class="img-responsive" />
	                                                                </a>
	                                                            </li>
	                                                            <li class="col-md-4">
	                                                                <a class="thumb" href="MelisDesign/images/gallery-2/2.jpg" data-gallery="gallery"><img src="MelisDesign/images/gallery-2/2.jpg" alt="photo" class="img-responsive" />
	                                                                </a>
	                                                            </li>
	                                                            <li class="col-md-4">
	                                                                <a class="thumb" href="MelisDesign/images/gallery-2/1.jpg" data-gallery="gallery"><img src="MelisDesign/images/gallery-2/1.jpg" alt="photo" class="img-responsive" />
	                                                                </a>
	                                                            </li>
	                                                        </ul>
	                                                    </div>
	                                                    <!-- // Gallery Layout END -->

	                                                </div>
	                                                <a class="glyphicons single pencil"><i></i></a>
	                                            </div>
	                                        </div>
	                                    </li>
	                                </ul>

	                            </div>
	                        </div>
	                    </div>
	                </div>

	            </div>
	        </div>




	        <div class="widget widget-inverse">
	            <div class="widget-head">
	                <h4 class="heading"><i class="fa fa-list fa-fw"></i> Timeline with Navigation</h4>
	            </div>
	            <div class="widget-body padding-none">

	                <div class="row row-merge layout-timeline">
	                    <div class="col-md-4">
	                        <div class="innerAll">

	                            <div class="row margin-none innerT">
	                                <div class="col-md-7">
	                                    <ul class="nav nav-pills nav-stacked nav-timeline">
	                                        <li class="active"><a href="">Now</a>
	                                        </li>
	                                        <li><a href="">Yesterday</a>
	                                        </li>
	                                        <li><a href="">2 Weeks Ago</a>
	                                        </li>
	                                        <li><a href="" class="glyphicons calendar">Custom<i></i></a>
	                                        </li>
	                                    </ul>
	                                </div>
	                            </div>

	                        </div>
	                    </div>
	                    <div class="col-md-8">
	                        <div class="innerAll">

	                            <ul class="timeline">
	                                <li class="active">
	                                    <div class="separator bottom">
	                                        <span class="date box-generic">Now</span>
	                                        <span class="type glyphicons suitcase">Task <i></i><span class="time">08:00</span></span>
	                                        <button type="button" class="btn btn-primary"><i class="fa fa-fw fa-plus-circle"></i> Add event</button>
	                                    </div>
	                                    <div class="widget widget-heading-simple widget-body-white margin-none">
	                                        <div class="widget-body">
	                                            <div class="media">
	                                                <div class="media-object pull-left thumb"><img src="MelisDesign/images/avatar-51x51.jpg" alt="Image" />
	                                                </div>
	                                                <div class="media-body">
	                                                    <a class="author">John Doe</a>
	                                                    <br/>
	                                                    <span class="muted">johndoe@ennovation.ie</span>
	                                                </div>
	                                            </div>
	                                            <div class="alert alert-gray">
	                                                <p class="glyphicons circle_info margin-none"><i></i> Added a new milestone named <a href="">MyCompany</a>
	                                                </p>
	                                            </div>
	                                            <a class="glyphicons single pencil"><i></i></a>
	                                        </div>
	                                    </div>
	                                </li>
	                                <li class="active">
	                                    <span class="type glyphicons suitcase">Task <i></i><span class="time">09:00</span></span>
	                                    <div class="widget widget-heading-simple widget-body-white margin-none">
	                                        <div class="widget-body">
	                                            <div class="media">
	                                                <div class="media-object pull-left thumb"><img src="MelisDesign/images/avatar-51x51.jpg" alt="Image" />
	                                                </div>
	                                                <div class="media-body">
	                                                    <a class="author">John Doe</a>
	                                                    <br/>
	                                                    <span class="muted">johndoe@ennovation.ie</span>
	                                                </div>
	                                            </div>
	                                            <div class="alert alert-gray">
	                                                <p class="glyphicons circle_info margin-none"><i></i> Added a new milestone named <a href="">MyCompany</a>
	                                                </p>
	                                            </div>
	                                            <a class="glyphicons single pencil"><i></i></a>
	                                        </div>
	                                    </div>
	                                </li>
	                                <li class="active">
	                                    <span class="type glyphicons comments">Comment <i></i><span class="time">11:00</span></span>
	                                    <div class="widget widget-heading-simple widget-body-gray margin-none">
	                                        <div class="widget-body">
	                                            <p class="glyphicons user margin-none"><i></i> <strong><a href="">MyCompany</a> said</strong>: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an ...</p>
	                                        </div>
	                                    </div>
	                                </li>
	                                <li>
	                                    <div class="separator">
	                                        <span class="date box-generic"><strong>27</strong>may</span>
	                                        <span class="type glyphicons picture">Photo <i></i><span class="time">08:00</span></span>
	                                    </div>
	                                    <div class="widget widget-heading-simple widget-body-white margin-none">
	                                        <div class="widget-body">
	                                            <div class="media">
	                                                <div class="media-object pull-left thumb"><img src="MelisDesign/images/avatar-51x51.jpg" alt="Image" />
	                                                </div>
	                                                <div class="media-body">
	                                                    <a class="author">John Doe</a>
	                                                    <br/>
	                                                    <span class="muted">johndoe@ennovation.ie</span>
	                                                </div>
	                                            </div>
	                                            <div class="alert alert-gray">
	                                                <p class="glyphicons circle_info"><i></i> Added photos to the album <a href="">MyCompany</a>
	                                                </p>

	                                                <!-- Gallery Layout -->
	                                                <div class="gallery gallery-2 separator top">
	                                                    <ul class="row" data-toggle="modal-gallery" data-target="#modal-gallery" id="gallery-4" data-delegate="#gallery-4">
	                                                        <li class="col-md-3 hidden-phone">
	                                                            <a class="thumb" href="MelisDesign/images/gallery-2/6.jpg" data-gallery="gallery"><img src="MelisDesign/images/gallery-2/6.jpg" alt="photo" class="img-responsive" />
	                                                            </a>
	                                                        </li>
	                                                        <li class="col-md-3 hidden-phone">
	                                                            <a class="thumb" href="MelisDesign/images/gallery-2/5.jpg" data-gallery="gallery"><img src="MelisDesign/images/gallery-2/5.jpg" alt="photo" class="img-responsive" />
	                                                            </a>
	                                                        </li>
	                                                        <li class="col-md-3 hidden-phone">
	                                                            <a class="thumb" href="MelisDesign/images/gallery-2/4.jpg" data-gallery="gallery"><img src="MelisDesign/images/gallery-2/4.jpg" alt="photo" class="img-responsive" />
	                                                            </a>
	                                                        </li>
	                                                        <li class="col-md-3">
	                                                            <a class="thumb" href="MelisDesign/images/gallery-2/3.jpg" data-gallery="gallery"><img src="MelisDesign/images/gallery-2/3.jpg" alt="photo" class="img-responsive" />
	                                                            </a>
	                                                        </li>
	                                                        <li class="col-md-3">
	                                                            <a class="thumb" href="MelisDesign/images/gallery-2/2.jpg" data-gallery="gallery"><img src="MelisDesign/images/gallery-2/2.jpg" alt="photo" class="img-responsive" />
	                                                            </a>
	                                                        </li>
	                                                        <li class="col-md-3">
	                                                            <a class="thumb" href="MelisDesign/images/gallery-2/1.jpg" data-gallery="gallery"><img src="MelisDesign/images/gallery-2/1.jpg" alt="photo" class="img-responsive" />
	                                                            </a>
	                                                        </li>
	                                                    </ul>
	                                                </div>
	                                                <!-- // Gallery Layout END -->

	                                            </div>
	                                            <a class="glyphicons single pencil"><i></i></a>
	                                        </div>
	                                    </div>
	                                </li>
	                            </ul>

	                        </div>
	                    </div>
	                </div>

	            </div>
	        </div>



	    </div>


	</div>
	<!-- // Content END -->



    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->