<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;
        
?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    <div id="content">
        <h1 class="content-heading bg-white border-bottom">Medical memos</h1>
        <div class="bg-white innerAll border-bottom">
            <ul class="menubar">
                <li><a href="index.html?lang=en">Dashboard</a>
                </li>
                <li><a href="#"><span class="badge badge-primary float-right">30</span> Button</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Dropdown Link #1</a>
                        </li>
                        <li><a href="#">Dropdown Link #2</a>
                        </li>
                        <li><a href="#">Dropdown Link #3</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="innerAll spacing-x2">

            <!-- row-app -->
            <div class="row row-app">

                <!-- col -->
                <div class="col-lg-4">

                    <div class="heading-buttons border-bottom box-generic innerAll half margin-none border-bottom-none">
                        <h4 class="margin-none padding-none float-left">Memos</h4>
                        <button class="btn btn-xs btn-inverse float-right"><i class="fa fa-plus"></i> Add memo <i class="fa fa-file-text-o fa-fw"></i>
                        </button>
                        <div class="clearfix"></div>
                    </div>

                    <div class="box-generic innerAll half">
                        <div class="input-group input-group-sm">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-inverse dropdown-toggle" data-toggle="dropdown">Name <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Name</a>
                                    </li>
                                    <li><a href="#">Phone Number</a>
                                    </li>
                                    <li><a href="#">Group</a>
                                    </li>
                                </ul>
                            </div>
                            <input type="text" class="form-control" placeholder="What are you searching for?">
                        </div>
                    </div>

                    <div class="box-generic padding-none">
                        <a href=""><h5 class="strong margin-none innerAll half border-bottom">Dolor voluptates earum dignissimos</h5></a>
                        <div class="innerAll half border-bottom">
                            <i class="fa fa-calendar fa-fw text-primary"></i> 23 aug 2013 &nbsp;
                            <i class="fa fa-tag fa-fw text-primary"></i> <span class="label label-primary">tagged</span>
                        </div>
                        <div class="innerAll">
                            <p class="margin-none innerAll half"><i class="fa fa-quote-left fa-2x float-left"></i> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet, aut, blanditiis pariatur ad enim ex dolorem. Rerum, fuga, praesentium nulla sed at numquam cupiditate dolores quos provident deleniti ab eius.</p>
                        </div>
                        <div class="innerLR innerT half bg-primary-light border-top">
                            <button class="btn btn-primary float-right"><i class="fa fa-sign-in"></i>
                            </button>
                            <div class="media inline-block margin-none">
                                <div class="innerLR">
                                    <i class="fa fa-paperclip float-left text-primary fa-2x"></i>
                                    <div class="media-body t-row">
                                        <div><a href="" class="strong text-regular">Patients</a>
                                        </div>
                                        <span>15 MB</span>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                            <div class="media inline-block margin-none">
                                <div class="innerLR border-left">
                                    <i class="fa fa-bar-chart-o float-left text-primary fa-2x"></i>
                                    <div class="media-body t-row">
                                        <div><a href="" class="strong text-regular">Report</a>
                                        </div>
                                        <span>244 KB</span>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="box-generic padding-none">
                        <a href=""><h5 class="strong margin-none innerAll half border-bottom">Quibusdam expedita voluptates tenetur</h5></a>
                        <div class="innerAll half border-bottom">
                            <i class="fa fa-calendar fa-fw text-primary"></i> 21 aug 2013 &nbsp;
                            <i class="fa fa-tag fa-fw text-primary"></i> <span class="label label-primary">important</span>
                        </div>
                        <div class="innerAll">
                            <p class="margin-none innerAll half"><i class="fa fa-quote-left fa-2x float-left"></i> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum, voluptates itaque similique excepturi porro suscipit iste assumenda fugiat accusantium explicabo incidunt a ad odio blanditiis dolores consequatur sequi quisquam mollitia.</p>
                        </div>
                        <div class="innerLR innerT half bg-primary-light border-top">
                            <button class="btn btn-primary float-right"><i class="fa fa-sign-in"></i>
                            </button>
                            <div class="media inline-block margin-none">
                                <div class="innerLR">
                                    <i class="fa fa-stethoscope float-left text-primary fa-2x"></i>
                                    <div class="media-body t-row">
                                        <div><a href="" class="strong text-regular">Lab Results</a>
                                        </div>
                                        <span>1 MB</span>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- // END col -->

                <!-- col -->
                <div class="col-lg-4">

                    <div class="box-generic padding-none">
                        <h4 class="innerAll half margin-none"><i class="fa fa-star float-right text-primary"></i>Bookmarks</h4>
                    </div>

                    <div class="box-generic padding-none">
                        <div class="innerAll">
                            <p class="margin-none innerAll half"><i class="fa fa-quote-left fa-4x float-left"></i> Aliquam rutrum, sem at scelerisque tempor, nulla diam pulvinar tortor, id pulvinar massa velit eu purus. Curabitur eu fringilla diam, sed suscipit lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras iaculis enim vel odio imperdiet faucibus. Aliquam erat volutpat.</p>
                        </div>
                        <div class="innerLR innerT half bg-gray border-top">
                            <button class="btn btn-primary float-right"><i class="fa fa-sign-in"></i>
                            </button>
                            <div class="media inline-block margin-none">
                                <div class="innerLR">
                                    <i class="fa fa-hospital float-left fa-2x text-primary"></i>
                                    <div class="media-body t-row">
                                        <div><a href="" class="strong text-regular">Plans</a>
                                        </div>
                                        <span>120 KB</span>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                            <div class="media inline-block margin-none">
                                <div class="innerLR border-left">
                                    <i class="fa fa-euro float-left fa-2x text-primary"></i>
                                    <div class="media-body t-row">
                                        <div><a href="" class="strong text-regular">Income</a>
                                        </div>
                                        <span>24 KB</span>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="box-generic padding-none">
                        <div class="innerAll">
                            <p class="margin-none innerAll half"><i class="fa fa-quote-left fa-4x float-left"></i> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur, labore unde tempora natus. Repellat, voluptatibus, omnis accusantium eveniet recusandae maiores laboriosam beatae rerum perferendis nostrum enim iure esse sunt non.</p>
                        </div>
                        <div class="innerAll half bg-gray border-top">
                            <button class="btn btn-inverse btn-xs float-right"><i class="fa fa-sign-in"></i>
                            </button>
                            <span class="innerAll half inline-block">
                            <i class="fa fa-calendar text-primary fa-fw"></i> 22 nov 2013 &nbsp;
                            <i class="fa fa-tag text-primary fa-fw"></i> <span class="label label-primary">tagged</span> &nbsp;
                            </span>
                            <div class="clearfix"></div>
                        </div>
                    </div>

                </div>
                <!-- // END col -->

            </div>
            <!-- // END row-app -->

        </div>





    </div>
    <!-- // Content END -->
        
<div class="clearfix"></div>
<!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->