<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    <div id="content" class="render-finances">
        <div class="heading-buttons bg-white border-bottom innerAll">
            <div class="btn-group btn-group-xs float-right">
                <a href="" class="btn btn-primary">Add record</a>
                <a href="" class="btn btn-default">History</a>
            </div>
            <h1 class="content-heading padding-none float-left">Finances</h1>
            <div class="clearfix"></div>
        </div>
        <div class="bg-white innerAll border-bottom">
            <ul class="menubar">
                <li><a href="index.html?lang=en">Dashboard</a>
                </li>
                <li><a href="#"><span class="badge badge-primary float-right">30</span> Button</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Dropdown Link #1</a>
                        </li>
                        <li><a href="#">Dropdown Link #2</a>
                        </li>
                        <li><a href="#">Dropdown Link #3</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="innerAll spacing-x2">

            <!-- Widget -->
            <div class="widget finances_summary widget-inverse">

                <!-- Widget heading -->
                <div class="widget-head">
                    <h4 class="heading glyphicons alarm"><i></i> Summary</h4>
                </div>
                <!-- // Widget heading END -->

                <div class="widget-body">

                    <!-- Filters -->
                    <div class="filter-bar">
                        <form class="form-inline">

                            <!-- From -->
                            <div class="form-group col-md-2 padding-none">
                                <label>From:</label>
                                <div class="input-group input-table">
                                    <input type="text" name="from" id="dateRangeFrom" class="form-control" value="08/05/13" />
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                </div>
                            </div>
                            <!-- // From END -->

                            <!-- To -->
                            <div class="form-group col-md-2 padding-none">
                                <label>To:</label>
                                <div class="input-group input-table">
                                    <input type="text" name="to" id="dateRangeTo" class="form-control" value="08/18/13" />
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                </div>
                            </div>
                            <!-- // To END -->

                            <!-- Min -->
                            <div class="form-group col-md-2 padding-none">
                                <label>Min:</label>
                                <div class="input-group input-table">
                                    <input type="text" name="from" class="form-control" value="100" />
                                    <span class="input-group-addon"><i class="fa fa-euro"></i></span>
                                </div>
                            </div>
                            <!-- // Min END -->

                            <!-- Max -->
                            <div class="form-group col-md-2 padding-none">
                                <label>Max:</label>
                                <div class="input-group input-table">
                                    <input type="text" name="from" class="form-control" value="500" />
                                    <span class="input-group-addon"><i class="fa fa-euro"></i></span>
                                </div>
                            </div>
                            <!-- // Max END -->

                            <!-- Select -->
                            <div class="form-group col-md-3 padding-none">
                                <label class="label-control">Select:</label>
                                <div class="col-md-8 padding-none">
                                    <select name="from" class="form-control">
                                        <option>Some option</option>
                                        <option>Other option</option>
                                        <option>Some other option</option>
                                    </select>
                                </div>
                            </div>
                            <!-- // Select END -->

                            <div class="clearfix"></div>
                        </form>
                    </div>
                    <!-- // Filters END -->




                    <!-- Row -->
                    <div class="row">

                        <!-- Column -->
                        <div class="col-md-4">
                            <div class="box-generic margin-none text-center">
                                <p class="margin-none">Total expenses</p>
                                <strong class="text-large">&euro;32,156.00</strong>
                            </div>
                            <div class="separator text-center">
                                <span class="glyphicons flash standard"><i></i></span>
                            </div>
                            <div class="box-generic text-center">
                                <p class="margin-none">Total income</p>
                                <strong class="text-large">&euro;122,134.00</strong>
                            </div>
                        </div>
                        <!-- // Column END -->

                        <!-- Column -->
                        <div class="col-md-8">
                            <!-- Simple Chart -->
                            <div id="chart_finances_simple" class="flotchart-holder flotchart-fullwidth"></div>




                        </div>
                        <!-- // Column END -->

                    </div>
                    <!-- // Row END -->

                    <a href="" class="glyphicons list single"><i></i> View details</a>
                </div>
            </div>
            <!-- // Widget END -->

            <!-- Widget -->
            <div class="widget widget-inverse">

                <!-- Widget heading -->
                <div class="widget-head">
                    <h4 class="heading glyphicons fire"><i></i> Transactions</h4>
                </div>
                <!-- // Widget heading END -->

                <div class="widget-body">

                    <!-- Table -->
                    <table class="table table-condensed table-vertical-center table-thead-simple">
                        <thead>
                            <tr>
                                <th class="center" style="width: 1%">No.</th>
                                <th>Transaction</th>
                                <th class="center">Date</th>
                                <th class="center">Amount</th>
                                <th class="right">Actions</th>
                            </tr>
                        </thead>
                        <tbody>

                            <!-- Item -->
                            <tr class="selectable">
                                <td class="center">1</td>
                                <td class="important"><span class="btn btn-sm btn-success"><i class="fa fa-arrow-up"></i></span> &nbsp; Supplier Abc Xyz</td>
                                <td class="center"><span class="label label-primary">23 Jan 2013</span>
                                </td>
                                <td class="center strong">&euro;318.00</td>
                                <td class="right actions">
                                    <a href="#" class="btn btn-sm btn-default"><i class="fa fa-eye"></i></a>
                                    <a href="#" class="btn btn-sm btn-success"><i class="fa fa-pencil"></i></a>
                                    <a href="#" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a>
                                </td>
                            </tr>
                            <!-- // Item END -->
                            <!-- Item -->
                            <tr class="selectable">
                                <td class="center">2</td>
                                <td class="important"><span class="btn btn-sm btn-danger"><i class="fa fa-arrow-down"></i></span> &nbsp; Supplier Abc Xyz</td>
                                <td class="center"><span class="label label-primary">23 Jan 2013</span>
                                </td>
                                <td class="center strong">&euro;489.00</td>
                                <td class="right actions">
                                    <a href="#" class="btn btn-sm btn-default"><i class="fa fa-eye"></i></a>
                                    <a href="#" class="btn btn-sm btn-success"><i class="fa fa-pencil"></i></a>
                                    <a href="#" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a>
                                </td>
                            </tr>
                            <!-- // Item END -->
                            <!-- Item -->
                            <tr class="selectable">
                                <td class="center">3</td>
                                <td class="important"><span class="btn btn-sm btn-success"><i class="fa fa-arrow-up"></i></span> &nbsp; Bank of Ireland</td>
                                <td class="center"><span class="label label-primary">23 Jan 2013</span>
                                </td>
                                <td class="center strong">&euro;446.00</td>
                                <td class="right actions">
                                    <a href="#" class="btn btn-sm btn-default"><i class="fa fa-eye"></i></a>
                                    <a href="#" class="btn btn-sm btn-success"><i class="fa fa-pencil"></i></a>
                                    <a href="#" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a>
                                </td>
                            </tr>
                            <!-- // Item END -->
                            <!-- Item -->
                            <tr class="selectable">
                                <td class="center">4</td>
                                <td class="important"><span class="btn btn-sm btn-danger"><i class="fa fa-arrow-down"></i></span> &nbsp; Supplier Abc Xyz</td>
                                <td class="center"><span class="label label-primary">23 Jan 2013</span>
                                </td>
                                <td class="center strong">&euro;498.00</td>
                                <td class="right actions">
                                    <a href="#" class="btn btn-sm btn-default"><i class="fa fa-eye"></i></a>
                                    <a href="#" class="btn btn-sm btn-success"><i class="fa fa-pencil"></i></a>
                                    <a href="#" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a>
                                </td>
                            </tr>
                            <!-- // Item END -->
                            <!-- Item -->
                            <tr class="selectable">
                                <td class="center">5</td>
                                <td class="important"><span class="btn btn-sm btn-success"><i class="fa fa-arrow-up"></i></span> &nbsp; Amazon Web Services</td>
                                <td class="center"><span class="label label-primary">23 Jan 2013</span>
                                </td>
                                <td class="center strong">&euro;120.00</td>
                                <td class="right actions">
                                    <a href="#" class="btn btn-sm btn-default"><i class="fa fa-eye"></i></a>
                                    <a href="#" class="btn btn-sm btn-success"><i class="fa fa-pencil"></i></a>
                                    <a href="#" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a>
                                </td>
                            </tr>
                            <!-- // Item END -->
                            <!-- Item -->
                            <tr class="selectable">
                                <td class="center">6</td>
                                <td class="important"><span class="btn btn-sm btn-success"><i class="fa fa-arrow-up"></i></span> &nbsp; ThemeForest</td>
                                <td class="center"><span class="label label-primary">23 Jan 2013</span>
                                </td>
                                <td class="center strong">&euro;103.00</td>
                                <td class="right actions">
                                    <a href="#" class="btn btn-sm btn-default"><i class="fa fa-eye"></i></a>
                                    <a href="#" class="btn btn-sm btn-success"><i class="fa fa-pencil"></i></a>
                                    <a href="#" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a>
                                </td>
                            </tr>
                            <!-- // Item END -->

                        </tbody>
                    </table>
                    <!-- // Table END -->

                    <div class="separator top"><a href="" class="glyphicons list single"><i></i> Show all</a>
                    </div>
                </div>
            </div>
            <!-- // Widget END -->

        </div>





    </div>
    <!-- // Content END -->

    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->