<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
	<div id="content">
	    <div class="heading-buttons bg-white border-bottom innerAll">
	        <h1 class="content-heading padding-none float-left">Tickets</h1>
	        <div class="clearfix"></div>
	    </div>

	    <div class="innerAll spacing-x2">

	        <!-- Widget -->
	        <div class="widget finances_summary widget-inverse">

	            <div class="row row-merge">
	                <div class="col-md-3">

	                    <ul class="list-group list-group-1 margin-none borders-none">
	                        <li class="list-group-item active animated fadeInUp"><a href="#"><span class="badge float-right badge-primary hidden-md">30</span><i class="fa fa-exclamation-circle"></i> Unread Tickets</a>
	                        </li>
	                        <li class="list-group-item animated fadeInUp"><a href="#"><span class="badge float-right badge-primary hidden-md">2</span><i class="fa fa-ticket"></i> New Tickets</a>
	                        </li>
	                        <li class="list-group-item animated fadeInUp"><a href="#"><i class="fa fa-spinner"></i> Pending Tickets</a>
	                        </li>
	                        <li class="list-group-item border-bottom animated fadeInUp"><a href="#"><i class="fa fa-pencil"></i> Drafts</a>
	                        </li>

	                    </ul>

	                    <div class="col-separator-h"></div>


	                    <form role="form">
	                        <div class="innerAll">
	                            <div class="form-group">
	                                <div class="input-group">
	                                    <span class="input-group-addon"><i class="fa fa-user text-faded"></i></span>
	                                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Search by Name">
	                                </div>
	                            </div>
	                            <div class="form-group">
	                                <div class="input-group">
	                                    <span class="input-group-addon"><i class="icon-tag-fill-1 text-faded"></i></span>
	                                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="#ticket-id">
	                                </div>
	                            </div>
	                            <div class="form-group">
	                                <div class="input-group date" id="datepicker2">
	                                    <input class="form-control" type="text" value="14 February 2013" />
	                                    <span class="input-group-addon"><i class="fa fa-th"></i></span>
	                                </div>


	                            </div>

	                            <div class="form-group margin-none">
	                                <label class="checkbox-inline checkbox-custom">
	                                    <i class="fa fa-fw fa-square-o"></i>
	                                    <input type="checkbox" id="inlineCheckbox1" value="option1"> New
	                                </label>
	                                <label class="checkbox-inline checkbox-custom">
	                                    <i class="fa fa-fw fa-square-o"></i>
	                                    <input type="checkbox" id="inlineCheckbox2" value="option2" checked="checked"> Answered
	                                </label>
	                            </div>
	                        </div>

	                        <div class="text-center border-top innerTB">
	                            <a href="" class="btn btn-primary"><i class="fa fa-spinner"></i> Update</a>
	                        </div>
	                    </form>
	                    <div class="col-separator-h"></div>

	                </div>
	                <div class="col-md-9">

	                    <h4 class="innerAll border-bottom margin-bottom-none">Unread Tickets <div class="float-right display-block"><a href="" class="btn btn-default btn-xs ">Select All</a> <a href="" class="btn btn-default btn-xs ">Mark as Read</a></div></h4>
	                    <div class="innerAll border-bottom tickets">
	                        <div class="row">

	                            <div class="col-sm-10">
	                                <ul class="media-list">
	                                    <li class="media">
	                                        <div class="float-left">
	                                            <div class="center">
	                                                <div class="checkbox">
	                                                    <label class="checkbox-custom">
	                                                        <i class="fa fa-fw fa-square-o"></i>
	                                                        <input type="checkbox">
	                                                    </label>
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <a class="float-left" href="#">

	                                            <img class="media-object" src="MelisDesign/images/people/50/1.jpg" alt="...">
	                                        </a>
	                                        <div class="media-body">
	                                            <a href="" class="media-heading">Suzanne Marie</a>
	                                            <label class="label label-default">#2129</label>
	                                            <label class="label label-primary"><a href="" class="user-ticket-action "><i class="icon-reply-fill fw"></i></a> </label>
	                                            <label class="label label-info"><a href="" class="user-ticket-action "><i class=" icon-refresh-6 fw"></i> Pending</a> </label>
	                                            <div class="clearfix"></div>
	                                            <strong>[RE: Coral Question]</strong> Lorem ipsum dolor sit amet, consectetur repellendus amet distinctio inventore possimus cum dicta enim!..
	                                            <div class="clearfix"></div>
	                                            <small><i class="icon-time-clock fw"></i> on: 12:51 AM</small> <small><i class=" icon-life-raft innerL"></i> Agent: <a href="">Bogdan</a></small>
	                                        </div>
	                                    </li>
	                                </ul>


	                            </div>
	                            <div class="col-sm-2">
	                                <div class="innerT float-right">
	                                    <a href="" class="btn btn-success btn-xs btn-regular"><i class="fa fa-check"></i> Mark Solved</a>
	                                </div>
	                            </div>
	                        </div>

	                    </div>

	                    <div class="innerAll border-bottom tickets">
	                        <div class="row">

	                            <div class="col-sm-10">
	                                <ul class="media-list">
	                                    <li class="media">
	                                        <div class="float-left">
	                                            <div class="center">
	                                                <div class="checkbox">
	                                                    <label class="checkbox-custom">
	                                                        <i class="fa fa-fw fa-square-o"></i>
	                                                        <input type="checkbox" checked="checked">
	                                                    </label>
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <a class="float-left" href="#">

	                                            <img class="media-object" src="MelisDesign/images/people/50/2.jpg" alt="...">
	                                        </a>
	                                        <div class="media-body">
	                                            <a href="" class="media-heading">John Doe</a>
	                                            <label class="label label-default">#2129</label>
	                                            <label class="label label-primary"><a href="" class="user-ticket-action "><i class="icon-reply-fill fw"></i></a> </label>
	                                            <label class="label label-success"><i class=" icon-checkmark-thick fw"></i>
	                                            </label>
												<div class="clearfix"></div>
												<div class="content-text">
													<p><strong>[RE: Coral Question]</strong> Lorem ipsum dolor sit amet, consectetur <a href="">adipisicing elit</a>. Fugiat molestiae qui fuga ..</p>
												</div>
	                                            <div class="clearfix"></div>
	                                            <small><i class="icon-time-clock fw"></i> on: 12:51 AM</small> <small><i class=" icon-life-raft innerL"></i> Agent: <a href="">Bogdan</a></small>
	                                            <div class="media">
	                                                <a class="float-left" href="#">
	                                                    <span class="empty-photo agent">
												      			<i class="icon-life-raft"></i>
												      		</span>
	                                                </a>
	                                                <div class="media-body">
	                                                    <a href="" class="media-heading "> Bogdan</a> <small class="float-right">Today <i class="icon-time-clock "></i></small>
														<div class="clearfix"></div>
														<div class="content-text">
															<p>You need to open navbar.main.less and change the line 130 and change it to:</p>
														</div>
	                                                    <div class="innerT half">
	                                                        <pre class="prettyprint">&:hover {  background:#efefef;}</pre>
	                                                    </div>

	                                                </div>
	                                            </div>
	                                        </div>
	                                    </li>
	                                </ul>


	                            </div>
	                            <div class="col-sm-2">
	                                <div class="innerT float-right">
	                                    <a href="" class="btn btn-success btn-xs btn-regular"><i class="fa fa-check"></i> Mark Solved</a>
	                                </div>
	                            </div>
	                        </div>

	                    </div>

	                    <div class="innerAll border-bottom tickets">
	                        <div class="row">

	                            <div class="col-sm-10">
	                                <ul class="media-list">
	                                    <li class="media">
	                                        <div class="float-left">
	                                            <div class="center">
	                                                <div class="checkbox">
	                                                    <label class="checkbox-custom">
	                                                        <i class="fa fa-fw fa-square-o"></i>
	                                                        <input type="checkbox">
	                                                    </label>
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <a class="float-left" href="#">
	                                            <span class="empty-photo">
											      			<i class="fa fa-user"></i>
											      		</span>
	                                        </a>
	                                        <div class="media-body">
	                                            <a href="" class="media-heading">Mary Dawson</a>
	                                            <label class="label label-default">#2129</label>
	                                            <label class="label label-primary"><a href="" class="user-ticket-action "><i class="icon-reply-fill fw"></i></a> </label>
	                                            <label class="label label-info"><a href="" class="user-ticket-action "><i class=" icon-refresh-6 fw"></i> Pending</a> </label>
	                                            <div class="clearfix"></div>
	                                            <div class="content-text"><p><strong>[RE: Coral Question]</strong> Lorem ipsum dolor sit amet, consectetur repellendus amet distinctio inventore possimus cum dicta enim!..</p></div>
	                                            <div class="clearfix"></div>
	                                            <small><i class="icon-time-clock fw"></i> on: 12:51 AM</small> <small><i class=" icon-life-raft innerL"></i> Agent: <a href="">Bogdan</a></small>
	                                        </div>
	                                    </li>
	                                </ul>


	                            </div>
	                            <div class="col-sm-2">
	                                <div class="innerT float-right">
	                                    <a href="" class="btn btn-success btn-xs btn-regular"><i class="fa fa-check"></i> Mark Solved</a>
	                                </div>
	                            </div>
	                        </div>

	                    </div>

	                    <div class="innerAll border-bottom tickets">
	                        <div class="row">

	                            <div class="col-sm-10">
	                                <ul class="media-list">
	                                    <li class="media">
	                                        <div class="float-left">
	                                            <div class="center">
	                                                <div class="checkbox">
	                                                    <label class="checkbox-custom">
	                                                        <i class="fa fa-fw fa-square-o"></i>
	                                                        <input type="checkbox">
	                                                    </label>
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <a class="float-left" href="#">

	                                            <img class="media-object" src="MelisDesign/images/people/50/4.jpg" alt="...">
	                                        </a>
	                                        <div class="media-body">
	                                            <a href="" class="media-heading">John Carsten</a>
	                                            <label class="label label-default">#2129</label>
	                                            <label class="label label-primary"><a href="" class="user-ticket-action "><i class="icon-reply-fill fw"></i></a> </label>
	                                            <label class="label label-success"><i class=" icon-checkmark-thick fw"></i>
	                                            </label>
	                                            <div class="clearfix"></div>
	                                            <div class="content-text"><p><strong>[RE: Coral Question]</strong> Lorem ipsum dolor sit amet, consectetur <a href="">adipisicing elit</a>. Fugiat molestiae qui fuga ..</p></div>
	                                            <div class="clearfix"></div>
	                                            <small><i class="icon-time-clock fw"></i> on: 12:51 AM</small> <small><i class=" icon-life-raft innerL"></i> Agent: <a href="">Bogdan</a></small>
	                                        </div>
	                                    </li>
	                                </ul>


	                            </div>
	                            <div class="col-sm-2">
	                                <div class="innerT float-right">
	                                    <a href="" class="btn btn-success btn-xs btn-regular"><i class="fa fa-check"></i> Mark Solved</a>
	                                </div>
	                            </div>
	                        </div>

	                    </div>

	                    <div class="innerAll border-bottom tickets">
	                        <div class="row">

	                            <div class="col-sm-10">
	                                <ul class="media-list">
	                                    <li class="media">
	                                        <div class="float-left">
	                                            <div class="center">
	                                                <div class="checkbox">
	                                                    <label class="checkbox-custom">
	                                                        <i class="fa fa-fw fa-square-o"></i>
	                                                        <input type="checkbox">
	                                                    </label>
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <a class="float-left" href="#">

	                                            <img class="media-object" src="MelisDesign/images/people/50/5.jpg" alt="...">
	                                        </a>
	                                        <div class="media-body">
	                                            <a href="" class="media-heading">Suzanne Marie</a>
	                                            <label class="label label-default">#2129</label>
	                                            <label class="label label-primary"><a href="" class="user-ticket-action "><i class="icon-reply-fill fw"></i></a> </label>
	                                            <label class="label label-info"><a href="" class="user-ticket-action "><i class=" icon-refresh-6 fw"></i> Pending</a> </label>
	                                            <div class="clearfix"></div>
	                                            <div class="content-text"><p><strong>[RE: Coral Question]</strong> Lorem ipsum dolor sit amet, consectetur repellendus amet distinctio inventore possimus cum dicta enim!..</p></div>
	                                            <div class="clearfix"></div>
	                                            <small><i class="icon-time-clock fw"></i> on: 12:51 AM</small> <small><i class=" icon-life-raft innerL"></i> Agent: <a href="">Bogdan</a></small>
	                                        </div>
	                                    </li>
	                                </ul>


	                            </div>
	                            <div class="col-sm-2">
	                                <div class="innerT float-right">
	                                    <a href="" class="btn btn-success btn-xs btn-regular"><i class="fa fa-check"></i> Mark Solved</a>
	                                </div>
	                            </div>
	                        </div>

	                    </div>

	                    <div class="innerAll border-bottom tickets">
	                        <div class="row">

	                            <div class="col-sm-10">
	                                <ul class="media-list">
	                                    <li class="media">
	                                        <div class="float-left">
	                                            <div class="center">
	                                                <div class="checkbox">
	                                                    <label class="checkbox-custom">
	                                                        <i class="fa fa-fw fa-square-o"></i>
	                                                        <input type="checkbox">
	                                                    </label>
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <a class="float-left" href="#">

	                                            <img class="media-object" src="MelisDesign/images/people/50/6.jpg" alt="...">
	                                        </a>
	                                        <div class="media-body">
	                                            <a href="" class="media-heading">Bogdan Laza</a>
	                                            <label class="label label-default">#2129</label>
	                                            <label class="label label-primary"><a href="" class="user-ticket-action "><i class="icon-reply-fill fw"></i></a> </label>
	                                            <label class="label label-success"><i class=" icon-checkmark-thick fw"></i>
	                                            </label>
	                                            <div class="clearfix"></div>
	                                            <div class="content-text"><p><strong>[RE: Coral Question]</strong> Lorem ipsum dolor sit amet, consectetur <a href="">adipisicing elit</a>. Fugiat molestiae qui fuga ..</p></div>
	                                            <div class="clearfix"></div>
	                                            <small><i class="icon-time-clock fw"></i> on: 12:51 AM</small> <small><i class=" icon-life-raft innerL"></i> Agent: <a href="">Bogdan</a></small>
	                                        </div>
	                                    </li>
	                                </ul>


	                            </div>
	                            <div class="col-sm-2">
	                                <div class="innerT float-right">
	                                    <a href="" class="btn btn-success btn-xs btn-regular"><i class="fa fa-check"></i> Mark Solved</a>
	                                </div>
	                            </div>
	                        </div>

	                    </div>

	                    <div class="innerAll border-bottom tickets">
	                        <div class="row">

	                            <div class="col-sm-10">
	                                <ul class="media-list">
	                                    <li class="media">
	                                        <div class="float-left">
	                                            <div class="center">
	                                                <div class="checkbox">
	                                                    <label class="checkbox-custom">
	                                                        <i class="fa fa-fw fa-square-o"></i>
	                                                        <input type="checkbox">
	                                                    </label>
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <a class="float-left" href="#">

	                                            <img class="media-object" src="MelisDesign/images/people/50/7.jpg" alt="...">
	                                        </a>
	                                        <div class="media-body">
	                                            <a href="" class="media-heading">Stephanie</a>
	                                            <label class="label label-default">#2129</label>
	                                            <label class="label label-primary"><a href="" class="user-ticket-action "><i class="icon-reply-fill fw"></i></a> </label>
	                                            <label class="label label-info"><a href="" class="user-ticket-action "><i class=" icon-refresh-6 fw"></i> Pending</a> </label>
	                                            <div class="clearfix"></div>
	                                            <div class="content-text"><p><strong>[RE: Coral Question]</strong> Lorem ipsum dolor sit amet, consectetur repellendus amet distinctio inventore possimus cum dicta enim!..</p></div>
	                                            <div class="clearfix"></div>
	                                            <small><i class="icon-time-clock fw"></i> on: 12:51 AM</small> <small><i class=" icon-life-raft innerL"></i> Agent: <a href="">Bogdan</a></small>
	                                        </div>
	                                    </li>
	                                </ul>


	                            </div>
	                            <div class="col-sm-2">
	                                <div class="innerT float-right">
	                                    <a href="" class="btn btn-success btn-xs btn-regular"><i class="fa fa-check"></i> Mark Solved</a>
	                                </div>
	                            </div>
	                        </div>

	                    </div>

	                    <div class="innerAll border-bottom tickets">
	                        <div class="row">

	                            <div class="col-sm-10">
	                                <ul class="media-list">
	                                    <li class="media">
	                                        <div class="float-left">
	                                            <div class="center">
	                                                <div class="checkbox">
	                                                    <label class="checkbox-custom">
	                                                        <i class="fa fa-fw fa-square-o"></i>
	                                                        <input type="checkbox">
	                                                    </label>
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <a class="float-left" href="#">

	                                            <img class="media-object" src="MelisDesign/images/people/50/8.jpg" alt="...">
	                                        </a>
	                                        <div class="media-body">
	                                            <a href="" class="media-heading">John Carsten</a>
	                                            <label class="label label-default">#2129</label>
	                                            <label class="label label-primary"><a href="" class="user-ticket-action "><i class="icon-reply-fill fw"></i></a> </label>
	                                            <label class="label label-success"><i class=" icon-checkmark-thick fw"></i>
	                                            </label>
	                                            <div class="clearfix"></div>
	                                            <div class="content-text"><p><strong>[RE: Coral Question]</strong> Lorem ipsum dolor sit amet, consectetur <a href="">adipisicing elit</a>. Fugiat molestiae qui fuga ..</p></div>
	                                            <div class="clearfix"></div>
	                                            <small><i class="icon-time-clock fw"></i> on: 12:51 AM</small> <small><i class=" icon-life-raft innerL"></i> Agent: <a href="">Bogdan</a></small>
	                                        </div>
	                                    </li>
	                                </ul>


	                            </div>
	                            <div class="col-sm-2">
	                                <div class="innerT float-right">
	                                    <a href="" class="btn btn-success btn-xs btn-regular"><i class="fa fa-check"></i> Mark Solved</a>
	                                </div>
	                            </div>
	                        </div>

	                    </div>

	                    <div class="innerAll border-bottom tickets">
	                        <div class="row">

	                            <div class="col-sm-10">
	                                <ul class="media-list">
	                                    <li class="media">
	                                        <div class="float-left">
	                                            <div class="center">
	                                                <div class="checkbox">
	                                                    <label class="checkbox-custom">
	                                                        <i class="fa fa-fw fa-square-o"></i>
	                                                        <input type="checkbox">
	                                                    </label>
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <a class="float-left" href="#">

	                                            <img class="media-object" src="MelisDesign/images/people/50/9.jpg" alt="...">
	                                        </a>
	                                        <div class="media-body">
	                                            <a href="" class="media-heading">girl381</a>
	                                            <label class="label label-default">#2129</label>
	                                            <label class="label label-primary"><a href="" class="user-ticket-action "><i class="icon-reply-fill fw"></i></a> </label>
	                                            <label class="label label-info"><a href="" class="user-ticket-action "><i class=" icon-refresh-6 fw"></i> Pending</a> </label>
	                                            <div class="clearfix"></div>
	                                            <div class="content-text"><p><strong>[RE: Coral Question]</strong> Lorem ipsum dolor sit amet, consectetur repellendus amet distinctio inventore possimus cum dicta enim!..</p></div>
	                                            <div class="clearfix"></div>
	                                            <small><i class="icon-time-clock fw"></i> on: 12:51 AM</small> <small><i class=" icon-life-raft innerL"></i> Agent: <a href="">Bogdan</a></small>
	                                        </div>
	                                    </li>
	                                </ul>


	                            </div>
	                            <div class="col-sm-2">
	                                <div class="innerT float-right">
	                                    <a href="" class="btn btn-success btn-xs btn-regular"><i class="fa fa-check"></i> Mark Solved</a>
	                                </div>
	                            </div>
	                        </div>

	                    </div>

	                    <div class="innerAll border-bottom tickets">
	                        <div class="row">

	                            <div class="col-sm-10">
	                                <ul class="media-list">
	                                    <li class="media">
	                                        <div class="float-left">
	                                            <div class="center">
	                                                <div class="checkbox">
	                                                    <label class="checkbox-custom">
	                                                        <i class="fa fa-fw fa-square-o"></i>
	                                                        <input type="checkbox">
	                                                    </label>
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <a class="float-left" href="#">

	                                            <img class="media-object" src="MelisDesign/images/people/50/10.jpg" alt="...">
	                                        </a>
	                                        <div class="media-body">
	                                            <a href="" class="media-heading">Bogdan Laza</a>
	                                            <label class="label label-default">#2129</label>
	                                            <label class="label label-primary"><a href="" class="user-ticket-action "><i class="icon-reply-fill fw"></i></a> </label>
	                                            <label class="label label-success"><i class=" icon-checkmark-thick fw"></i>
	                                            </label>
	                                            <div class="clearfix"></div>
	                                            <div class="content-text"><p><strong>[RE: Coral Question]</strong> Lorem ipsum dolor sit amet, consectetur <a href="">adipisicing elit</a>. Fugiat molestiae qui fuga ..</p></div>
	                                            <div class="clearfix"></div>
	                                            <small><i class="icon-time-clock fw"></i> on: 12:51 AM</small> <small><i class=" icon-life-raft innerL"></i> Agent: <a href="">Bogdan</a></small>
	                                        </div>
	                                    </li>
	                                </ul>


	                            </div>
	                            <div class="col-sm-2">
	                                <div class="innerT float-right">
	                                    <a href="" class="btn btn-success btn-xs btn-regular"><i class="fa fa-check"></i> Mark Solved</a>
	                                </div>
	                            </div>
	                        </div>

	                    </div>

	                    <div class="innerAll border-bottom tickets">
	                        <div class="row">

	                            <div class="col-sm-10">
	                                <ul class="media-list">
	                                    <li class="media">
	                                        <div class="float-left">
	                                            <div class="center">
	                                                <div class="checkbox">
	                                                    <label class="checkbox-custom">
	                                                        <i class="fa fa-fw fa-square-o"></i>
	                                                        <input type="checkbox">
	                                                    </label>
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <a class="float-left" href="#">

	                                            <img class="media-object" src="MelisDesign/images/people/50/11.jpg" alt="...">
	                                        </a>
	                                        <div class="media-body">
	                                            <a href="" class="media-heading">Suzanne Marie</a>
	                                            <label class="label label-default">#2129</label>
	                                            <label class="label label-primary"><a href="" class="user-ticket-action "><i class="icon-reply-fill fw"></i></a> </label>
	                                            <label class="label label-info"><a href="" class="user-ticket-action "><i class=" icon-refresh-6 fw"></i> Pending</a> </label>
	                                            <div class="clearfix"></div>
	                                            <div class="content-text"><p><strong>[RE: Coral Question]</strong> Lorem ipsum dolor sit amet, consectetur repellendus amet distinctio inventore possimus cum dicta enim!..</p></div>
	                                            <div class="clearfix"></div>
	                                            <small><i class="icon-time-clock fw"></i> on: 12:51 AM</small> <small><i class=" icon-life-raft innerL"></i> Agent: <a href="">Bogdan</a></small>
	                                        </div>
	                                    </li>
	                                </ul>


	                            </div>
	                            <div class="col-sm-2">
	                                <div class="innerT float-right">
	                                    <a href="" class="btn btn-success btn-xs btn-regular"><i class="fa fa-check"></i> Mark Solved</a>
	                                </div>
	                            </div>
	                        </div>

	                    </div>

	                    <div class="innerAll border-bottom tickets">
	                        <div class="row">

	                            <div class="col-sm-10">
	                                <ul class="media-list">
	                                    <li class="media">
	                                        <div class="float-left">
	                                            <div class="center">
	                                                <div class="checkbox">
	                                                    <label class="checkbox-custom">
	                                                        <i class="fa fa-fw fa-square-o"></i>
	                                                        <input type="checkbox">
	                                                    </label>
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <a class="float-left" href="#">

	                                            <img class="media-object" src="MelisDesign/images/people/50/12.jpg" alt="...">
	                                        </a>
	                                        <div class="media-body">
	                                            <a href="" class="media-heading">Suzanne Marie</a>
	                                            <label class="label label-default">#2129</label>
	                                            <label class="label label-primary"><a href="" class="user-ticket-action "><i class="icon-reply-fill fw"></i></a> </label>
	                                            <label class="label label-success"><i class=" icon-checkmark-thick fw"></i>
	                                            </label>
	                                            <div class="clearfix"></div>
	                                            <div class="content-text"><p><strong>[RE: Coral Question]</strong> Lorem ipsum dolor sit amet, consectetur <a href="">adipisicing elit</a>. Fugiat molestiae qui fuga ..</p></div>
	                                            <div class="clearfix"></div>
	                                            <small><i class="icon-time-clock fw"></i> on: 12:51 AM</small> <small><i class=" icon-life-raft innerL"></i> Agent: <a href="">Bogdan</a></small>
	                                        </div>
	                                    </li>
	                                </ul>


	                            </div>
	                            <div class="col-sm-2">
	                                <div class="innerT float-right">
	                                    <a href="" class="btn btn-success btn-xs btn-regular"><i class="fa fa-check"></i> Mark Solved</a>
	                                </div>
	                            </div>
	                        </div>

	                    </div>

	                    <div class="innerAll border-bottom tickets">
	                        <div class="row">

	                            <div class="col-sm-10">
	                                <ul class="media-list">
	                                    <li class="media">
	                                        <div class="float-left">
	                                            <div class="center">
	                                                <div class="checkbox">
	                                                    <label class="checkbox-custom">
	                                                        <i class="fa fa-fw fa-square-o"></i>
	                                                        <input type="checkbox">
	                                                    </label>
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <a class="float-left" href="#">

	                                            <img class="media-object" src="MelisDesign/images/people/50/13.jpg" alt="...">
	                                        </a>
	                                        <div class="media-body">
	                                            <a href="" class="media-heading">John Carsten</a>
	                                            <label class="label label-default">#2129</label>
	                                            <label class="label label-primary"><a href="" class="user-ticket-action "><i class="icon-reply-fill fw"></i></a> </label>
	                                            <label class="label label-info"><a href="" class="user-ticket-action "><i class=" icon-refresh-6 fw"></i> Pending</a> </label>
	                                            <div class="clearfix"></div>
	                                            <div class="content-text"><p><strong>[RE: Coral Question]</strong> Lorem ipsum dolor sit amet, consectetur repellendus amet distinctio inventore possimus cum dicta enim!..</p></div>
	                                            <div class="clearfix"></div>
	                                            <small><i class="icon-time-clock fw"></i> on: 12:51 AM</small> <small><i class=" icon-life-raft innerL"></i> Agent: <a href="">Bogdan</a></small>
	                                        </div>
	                                    </li>
	                                </ul>


	                            </div>
	                            <div class="col-sm-2">
	                                <div class="innerT float-right">
	                                    <a href="" class="btn btn-success btn-xs btn-regular"><i class="fa fa-check"></i> Mark Solved</a>
	                                </div>
	                            </div>
	                        </div>

	                    </div>

	                    <div class="innerAll border-bottom tickets">
	                        <div class="row">

	                            <div class="col-sm-10">
	                                <ul class="media-list">
	                                    <li class="media">
	                                        <div class="float-left">
	                                            <div class="center">
	                                                <div class="checkbox">
	                                                    <label class="checkbox-custom">
	                                                        <i class="fa fa-fw fa-square-o"></i>
	                                                        <input type="checkbox">
	                                                    </label>
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <a class="float-left" href="#">

	                                            <img class="media-object" src="MelisDesign/images/people/50/14.jpg" alt="...">
	                                        </a>
	                                        <div class="media-body">
	                                            <a href="" class="media-heading">Bogdan Laza</a>
	                                            <label class="label label-default">#2129</label>
	                                            <label class="label label-primary"><a href="" class="user-ticket-action "><i class="icon-reply-fill fw"></i></a> </label>
	                                            <label class="label label-success"><i class=" icon-checkmark-thick fw"></i>
	                                            </label>
	                                            <div class="clearfix"></div>
	                                            <div class="content-text"><p><strong>[RE: Coral Question]</strong> Lorem ipsum dolor sit amet, consectetur <a href="">adipisicing elit</a>. Fugiat molestiae qui fuga ..</p></div>
	                                            <div class="clearfix"></div>
	                                            <small><i class="icon-time-clock fw"></i> on: 12:51 AM</small> <small><i class=" icon-life-raft innerL"></i> Agent: <a href="">Bogdan</a></small>
	                                        </div>
	                                    </li>
	                                </ul>


	                            </div>
	                            <div class="col-sm-2">
	                                <div class="innerT float-right">
	                                    <a href="" class="btn btn-success btn-xs btn-regular"><i class="fa fa-check"></i> Mark Solved</a>
	                                </div>
	                            </div>
	                        </div>

	                    </div>

	                    <div class="innerAll border-bottom tickets">
	                        <div class="row">

	                            <div class="col-sm-10">
	                                <ul class="media-list">
	                                    <li class="media">
	                                        <div class="float-left">
	                                            <div class="center">
	                                                <div class="checkbox">
	                                                    <label class="checkbox-custom">
	                                                        <i class="fa fa-fw fa-square-o"></i>
	                                                        <input type="checkbox">
	                                                    </label>
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <a class="float-left" href="#">

	                                            <img class="media-object" src="MelisDesign/images/people/50/15.jpg" alt="...">
	                                        </a>
	                                        <div class="media-body">
	                                            <a href="" class="media-heading">John Doe</a>
	                                            <label class="label label-default">#2129</label>
	                                            <label class="label label-primary"><a href="" class="user-ticket-action "><i class="icon-reply-fill fw"></i></a> </label>
	                                            <label class="label label-info"><a href="" class="user-ticket-action "><i class=" icon-refresh-6 fw"></i> Pending</a> </label>
	                                            <div class="clearfix"></div>
	                                            <div class="content-text"><p><strong>[RE: Coral Question]</strong> Lorem ipsum dolor sit amet, consectetur repellendus amet distinctio inventore possimus cum dicta enim!..</p></div>
	                                            <div class="clearfix"></div>
	                                            <small><i class="icon-time-clock fw"></i> on: 12:51 AM</small> <small><i class=" icon-life-raft innerL"></i> Agent: <a href="">Bogdan</a></small>
	                                        </div>
	                                    </li>
	                                </ul>


	                            </div>
	                            <div class="col-sm-2">
	                                <div class="innerT float-right">
	                                    <a href="" class="btn btn-success btn-xs btn-regular"><i class="fa fa-check"></i> Mark Solved</a>
	                                </div>
	                            </div>
	                        </div>

	                    </div>

	                    <div class="innerAll border-bottom tickets">
	                        <div class="row">

	                            <div class="col-sm-10">
	                                <ul class="media-list">
	                                    <li class="media">
	                                        <div class="float-left">
	                                            <div class="center">
	                                                <div class="checkbox">
	                                                    <label class="checkbox-custom">
	                                                        <i class="fa fa-fw fa-square-o"></i>
	                                                        <input type="checkbox">
	                                                    </label>
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <a class="float-left" href="#">

	                                            <img class="media-object" src="MelisDesign/images/people/50/16.jpg" alt="...">
	                                        </a>
	                                        <div class="media-body">
	                                            <a href="" class="media-heading">Suzanne Marie</a>
	                                            <label class="label label-default">#2129</label>
	                                            <label class="label label-primary"><a href="" class="user-ticket-action "><i class="icon-reply-fill fw"></i></a> </label>
	                                            <label class="label label-success"><i class=" icon-checkmark-thick fw"></i>
	                                            </label>
	                                            <div class="clearfix"></div>
	                                            <div class="content-text"><p><strong>[RE: Coral Question]</strong> Lorem ipsum dolor sit amet, consectetur <a href="">adipisicing elit</a>. Fugiat molestiae qui fuga ..</p></div>
	                                            <div class="clearfix"></div>
	                                            <small><i class="icon-time-clock fw"></i> on: 12:51 AM</small> <small><i class=" icon-life-raft innerL"></i> Agent: <a href="">Bogdan</a></small>
	                                        </div>
	                                    </li>
	                                </ul>


	                            </div>
	                            <div class="col-sm-2">
	                                <div class="innerT float-right">
	                                    <a href="" class="btn btn-success btn-xs btn-regular"><i class="fa fa-check"></i> Mark Solved</a>
	                                </div>
	                            </div>
	                        </div>

	                    </div>

	                    <div class="innerAll border-bottom tickets">
	                        <div class="row">

	                            <div class="col-sm-10">
	                                <ul class="media-list">
	                                    <li class="media">
	                                        <div class="float-left">
	                                            <div class="center">
	                                                <div class="checkbox">
	                                                    <label class="checkbox-custom">
	                                                        <i class="fa fa-fw fa-square-o"></i>
	                                                        <input type="checkbox">
	                                                    </label>
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <a class="float-left" href="#">

	                                            <img class="media-object" src="MelisDesign/images/people/50/17.jpg" alt="...">
	                                        </a>
	                                        <div class="media-body">
	                                            <a href="" class="media-heading">John Carsten</a>
	                                            <label class="label label-default">#2129</label>
	                                            <label class="label label-primary"><a href="" class="user-ticket-action "><i class="icon-reply-fill fw"></i></a> </label>
	                                            <label class="label label-info"><a href="" class="user-ticket-action "><i class=" icon-refresh-6 fw"></i> Pending</a> </label>
	                                            <div class="clearfix"></div>
	                                            <div class="content-text"><p><strong>[RE: Coral Question]</strong> Lorem ipsum dolor sit amet, consectetur repellendus amet distinctio inventore possimus cum dicta enim!..</p></div>
	                                            <div class="clearfix"></div>
	                                            <small><i class="icon-time-clock fw"></i> on: 12:51 AM</small> <small><i class=" icon-life-raft innerL"></i> Agent: <a href="">Bogdan</a></small>
	                                        </div>
	                                    </li>
	                                </ul>


	                            </div>
	                            <div class="col-sm-2">
	                                <div class="innerT float-right">
	                                    <a href="" class="btn btn-success btn-xs btn-regular"><i class="fa fa-check"></i> Mark Solved</a>
	                                </div>
	                            </div>
	                        </div>

	                    </div>

	                    <div class="innerAll border-bottom tickets">
	                        <div class="row">

	                            <div class="col-sm-10">
	                                <ul class="media-list">
	                                    <li class="media">
	                                        <div class="float-left">
	                                            <div class="center">
	                                                <div class="checkbox">
	                                                    <label class="checkbox-custom">
	                                                        <i class="fa fa-fw fa-square-o"></i>
	                                                        <input type="checkbox">
	                                                    </label>
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <a class="float-left" href="#">

	                                            <img class="media-object" src="MelisDesign/images/people/50/18.jpg" alt="...">
	                                        </a>
	                                        <div class="media-body">
	                                            <a href="" class="media-heading">Bogdan Laza</a>
	                                            <label class="label label-default">#2129</label>
	                                            <label class="label label-primary"><a href="" class="user-ticket-action "><i class="icon-reply-fill fw"></i></a> </label>
	                                            <label class="label label-success"><i class=" icon-checkmark-thick fw"></i>
	                                            </label>
	                                            <div class="clearfix"></div>
	                                            <div class="content-text"><p><strong>[RE: Coral Question]</strong> Lorem ipsum dolor sit amet, consectetur <a href="">adipisicing elit</a>. Fugiat molestiae qui fuga ..</p></div>
	                                            <div class="clearfix"></div>
	                                            <small><i class="icon-time-clock fw"></i> on: 12:51 AM</small> <small><i class=" icon-life-raft innerL"></i> Agent: <a href="">Bogdan</a></small>
	                                        </div>
	                                    </li>
	                                </ul>


	                            </div>
	                            <div class="col-sm-2">
	                                <div class="innerT float-right">
	                                    <a href="" class="btn btn-success btn-xs btn-regular"><i class="fa fa-check"></i> Mark Solved</a>
	                                </div>
	                            </div>
	                        </div>

	                    </div>

	                    <div class="innerAll border-bottom tickets">
	                        <div class="row">

	                            <div class="col-sm-10">
	                                <ul class="media-list">
	                                    <li class="media">
	                                        <div class="float-left">
	                                            <div class="center">
	                                                <div class="checkbox">
	                                                    <label class="checkbox-custom">
	                                                        <i class="fa fa-fw fa-square-o"></i>
	                                                        <input type="checkbox">
	                                                    </label>
	                                                </div>
	                                            </div>
	                                        </div>
	                                        <a class="float-left" href="#">

	                                            <img class="media-object" src="MelisDesign/images/people/50/19.jpg" alt="...">
	                                        </a>
	                                        <div class="media-body">
	                                            <a href="" class="media-heading">John Carsten</a>
	                                            <label class="label label-default">#2129</label>
	                                            <label class="label label-primary"><a href="" class="user-ticket-action "><i class="icon-reply-fill fw"></i></a> </label>
	                                            <label class="label label-info"><a href="" class="user-ticket-action "><i class=" icon-refresh-6 fw"></i> Pending</a> </label>
	                                            <div class="clearfix"></div>
	                                            <div class="content-text"><p><strong>[RE: Coral Question]</strong> Lorem ipsum dolor sit amet, consectetur repellendus amet distinctio inventore possimus cum dicta enim!..</p></div>
	                                            <div class="clearfix"></div>
	                                            <small><i class="icon-time-clock fw"></i> on: 12:51 AM</small> <small><i class=" icon-life-raft innerL"></i> Agent: <a href="">Bogdan</a></small>
	                                        </div>
	                                    </li>
	                                </ul>


	                            </div>
	                            <div class="col-sm-2">
	                                <div class="innerT float-right">
	                                    <a href="" class="btn btn-success btn-xs btn-regular"><i class="fa fa-check"></i> Mark Solved</a>
	                                </div>
	                            </div>
	                        </div>

	                    </div>


	                </div>


	            </div>
	        </div>
	    </div>





	</div>
	<!-- // Content END -->
    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->