<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;
        
?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">

    <div id="content">
        <h1 class="content-heading bg-white border-bottom">Medical appointments</h1>
        <div class="bg-white innerAll border-bottom">
            <ul class="menubar">
                <li><a href="index.html?lang=en">Dashboard</a>
                </li>
                <li><a href="#"><span class="badge badge-primary float-right">30</span> Button</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Dropdown Link #1</a>
                        </li>
                        <li><a href="#">Dropdown Link #2</a>
                        </li>
                        <li><a href="#">Dropdown Link #3</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="innerAll spacing-x2">

            <!-- row-app -->
            <div class="row row-app">

                <!-- col -->
                <div class="col-md-8 col-lg-9">

                    <div class="box-generic padding-none">

                        <div class="innerAll half">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search appointments ...">
                                <div class="input-group-btn">
                                    <button class="btn btn-inverse"><i class="fa fa-fw fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </div>

                        <div class="innerAll half bg-primary">
                            <div class="float-left">
                                <a href="" class="text-white strong"><i class="fa fa-fw fa-plus"></i> Add appointment</a>
                            </div>
                            <div class="float-right">
                                <a href="" class="text-white strong"><i class="fa fa-arrow-left"></i></a>
                                <span class="strong innerLR">Friday, Nov 15, 2013</span>
                                <a href="" class="text-white strong"><i class="fa fa-arrow-right"></i></a>
                            </div>
                            <div class="clearfix"></div>
                        </div>

                        <ul class="list-unstyled timeline-appointments bg-primary-light">
                            <li>
                                <div class="time">8:00 <span class="text-primary">am</span>
                                </div>
                                <i class="fa fa-dot-circle-o text-primary dot"></i>
                                <div class="appointments">
                                    <ul class="list-unstyled">
                                        <li>
                                            <div class="apt">
                                                <div class="btn-group btn-group-xs float-right">
                                                    <a href="" class="btn btn-default"><i class="fa fa-edit"></i></a>
                                                    <a href="" class="btn btn-default"><i class="fa fa-times"></i></a>
                                                </div>
                                                <a href="" class="text-regular strong"><i class="fa fa-fw fa-user"></i> Saul Jehonathan</a> <i class="text-faded fa fa-ellipsis-h"></i> Ultrasonographer
                                                <i class="text-faded fa fa-tag"></i> <span class="label label-inverse">Upcoming</span>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="apt">
                                                <div class="btn-group btn-group-xs float-right">
                                                    <a href="" class="btn btn-default"><i class="fa fa-edit"></i></a>
                                                    <a href="" class="btn btn-default"><i class="fa fa-times"></i></a>
                                                </div>
                                                <a href="" class="text-regular strong"><i class="fa fa-fw fa-user"></i> Gautam Alain</a> <i class="text-faded fa fa-ellipsis-h"></i> Gynaecologist
                                            </div>
                                        </li>
                                    </ul>




                                </div>
                            </li>
                            <li>
                                <div class="time">9:00 <span class="text-primary">am</span>
                                </div>
                                <i class="fa fa-dot-circle-o text-primary dot"></i>
                                <div class="appointments">




                                </div>
                            </li>
                            <li>
                                <div class="time">10:00 <span class="text-primary">am</span>
                                </div>
                                <i class="fa fa-dot-circle-o text-primary dot"></i>
                                <div class="appointments">

                                    <ul class="list-unstyled">
                                        <li>
                                            <div class="apt">
                                                <div class="btn-group btn-group-xs float-right">
                                                    <a href="" class="btn btn-default"><i class="fa fa-edit"></i></a>
                                                    <a href="" class="btn btn-default"><i class="fa fa-times"></i></a>
                                                </div>
                                                <a href="" class="text-regular strong"><i class="fa fa-fw fa-female"></i> Fima Brennus</a> <i class="text-faded fa fa-stethoscope"></i> Consultation
                                            </div>
                                        </li>
                                    </ul>



                                </div>
                            </li>
                            <li>
                                <div class="time">11:00 <span class="text-primary">am</span>
                                </div>
                                <i class="fa fa-dot-circle-o text-primary dot"></i>
                                <div class="appointments">


                                    <ul class="list-unstyled">
                                        <li>
                                            <div class="apt">
                                                <div class="btn-group btn-group-xs float-right">
                                                    <a href="" class="btn btn-inverse"><i class="fa fa-plus"></i></a>
                                                </div>
                                                <span class="text-faded">Empty time slot ...</span>
                                            </div>
                                        </li>
                                        <li class="bg-primary-light text-primary">
                                            <i class="fa fa-fw fa-clock-o"></i> Half an hour break
                                        </li>
                                    </ul>


                                </div>
                            </li>
                            <li>
                                <div class="time">12:00 <span class="text-primary">pm</span>
                                </div>
                                <i class="fa fa-dot-circle-o text-primary dot"></i>
                                <div class="appointments">




                                </div>
                            </li>
                            <li>
                                <div class="time">1:00 <span class="text-primary">pm</span>
                                </div>
                                <i class="fa fa-dot-circle-o text-primary dot"></i>
                                <div class="appointments">



                                    <ul class="list-unstyled">
                                        <li class="text">
                                            <div class="strong text-regular"><i class="fa fa-fw fa-file-text-o"></i> Just a note</div>
                                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste, enim culpa adipisci atque consequatur sequi eligendi dignissimos minus asperiores esse. Numquam, voluptates, explicabo doloremque obcaecati laboriosam nulla ab fugiat hic.
                                        </li>
                                    </ul>

                                </div>
                            </li>
                            <li>
                                <div class="time">2:00 <span class="text-primary">pm</span>
                                </div>
                                <i class="fa fa-dot-circle-o text-primary dot"></i>
                                <div class="appointments">




                                </div>
                            </li>
                            <li>
                                <div class="time">3:00 <span class="text-primary">pm</span>
                                </div>
                                <i class="fa fa-dot-circle-o text-primary dot"></i>
                                <div class="appointments">




                                </div>
                            </li>
                            <li>
                                <div class="time">4:00 <span class="text-primary">pm</span>
                                </div>
                                <i class="fa fa-dot-circle-o text-primary dot"></i>
                                <div class="appointments">




                                </div>
                            </li>
                            <li>
                                <div class="time">5:00 <span class="text-primary">pm</span>
                                </div>
                                <i class="fa fa-dot-circle-o text-primary dot"></i>
                                <div class="appointments">




                                </div>
                            </li>
                        </ul>

                    </div>

                </div>
                <!-- // END col -->

                <!-- col -->
                <div class="col-md-4 col-lg-3">

                    <div class="box-generic padding-none">
                        <div class="bg-inverse text-white border-bottom text-center innerAll">
                            <div class="innerAll bg-trans">
                                <div class="strong">Next appointment</div>
                                <div class="text-large">2h 15min</div>
                                <div class="innerT">
                                    <a href="" class="btn btn-primary btn-lg">Cancel</a>
                                </div>
                            </div>
                        </div>
                        <div class="bg-white innerAll half text-center">
                            <span class="strong">Saul Jehonathan</span> Ultrasonographer
                        </div>
                    </div>

                    <div class="box-generic innerAll half">
                        <div class="datepicker-block"></div>



                    </div>

                </div>
                <!-- // END col -->

            </div>
            <!-- // END row-app -->

        </div>





    </div>
    <!-- // Content END -->
        
<div class="clearfix"></div>
<!-- // Sidebar menu & content wrapper END -->


</div>
<!-- // Tab END -->