<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    <div id="content" class="render-sliders">
        <h1 class="content-heading bg-white border-bottom">Range Sliders</h1>
        <div class="innerAll spacing-x2">

            <div class="row">
                <div class="col-md-6">

                    <!-- Widget -->
                    <div class="widget widget-inverse">

                        <!-- Widget heading -->
                        <div class="widget-head">
                            <h4 class="heading glyphicons adjust_alt"><i></i>Basic Range Slider</h4>
                        </div>
                        <!-- // Widget heading END -->

                        <div class="widget-body">
                            <!-- Slider -->
                            <div class="sliderContainer">
                                <div id="rangeSlider"></div>
                            </div>
                            <!-- // Slider END -->


                        </div>
                    </div>
                    <!-- // Widget END -->

                </div>
                <div class="col-md-6">

                    <!-- Widget -->
                    <div class="widget widget-inverse">

                        <!-- Widget heading -->
                        <div class="widget-head">
                            <h4 class="heading glyphicons adjust_alt"><i></i>Edit Range Slider</h4>
                        </div>
                        <!-- // Widget heading END -->

                        <div class="widget-body">
                            <!-- Slider -->
                            <div class="sliderContainer">
                                <div id="rangeSliderEdit" class="rangeslider-success"></div>
                            </div>
                            <!-- // Slider END -->


                        </div>
                    </div>
                    <!-- // Widget END -->

                </div>
            </div>

            <div class="row">
                <div class="col-md-6">

                    <!-- Widget -->
                    <div class="widget widget-inverse">

                        <!-- Widget heading -->
                        <div class="widget-head">
                            <h4 class="heading glyphicons adjust_alt"><i></i>Date Range Slider</h4>
                        </div>
                        <!-- // Widget heading END -->

                        <div class="widget-body">
                            <!-- Slider -->
                            <div class="sliderContainer">
                                <div id="rangeSliderDate"></div>
                            </div>
                            <!-- // Slider END -->


                        </div>
                    </div>
                    <!-- // Widget END -->

                </div>
                <div class="col-md-6">

                    <!-- Widget -->
                    <div class="widget widget-inverse">

                        <!-- Widget heading -->
                        <div class="widget-head">
                            <h4 class="heading glyphicons adjust_alt"><i></i>Range Slider without Arrows</h4>
                        </div>
                        <!-- // Widget heading END -->

                        <div class="widget-body">
                            <!-- Slider -->
                            <div class="sliderContainer">
                                <div id="rangeSliderWArrows" class="rangeslider-warning"></div>
                            </div>
                            <!-- // Slider END -->


                        </div>
                    </div>
                    <!-- // Widget END -->

                </div>
            </div>

            <div class="row">
                <div class="col-md-6">

                    <!-- Widget -->
                    <div class="widget widget-inverse">

                        <!-- Widget heading -->
                        <div class="widget-head">
                            <h4 class="heading glyphicons adjust_alt"><i></i>Range Slider with formatter</h4>
                        </div>
                        <!-- // Widget heading END -->

                        <div class="widget-body">
                            <!-- Slider -->
                            <div class="sliderContainer">
                                <div id="rangeSliderFormatter"></div>
                            </div>
                            <!-- // Slider END -->


                        </div>
                    </div>
                    <!-- // Widget END -->

                </div>
                <div class="col-md-6">

                    <!-- Widget -->
                    <div class="widget widget-inverse">

                        <!-- Widget heading -->
                        <div class="widget-head">
                            <h4 class="heading glyphicons adjust_alt"><i></i>Range Slider Rulers</h4>
                        </div>
                        <!-- // Widget heading END -->

                        <div class="widget-body">
                            <!-- Slider -->
                            <div class="sliderContainer">
                                <div id="rangeSliderRuler" class="rangeslider-danger"></div>
                            </div>
                            <!-- // Slider END -->


                        </div>
                    </div>
                </div>
            </div>

            <!-- Widget -->
            <div class="widget widget-inverse">

                <!-- Widget heading -->
                <div class="widget-head">
                    <h4 class="heading glyphicons adjust_alt"><i></i>Date Range Slider Ruler</h4>
                </div>
                <!-- // Widget heading END -->

                <div class="widget-body">
                    <!-- Slider -->
                    <div class="sliderContainer">
                        <div id="rangeSliderRulerDate" class="rangeslider-success"></div>
                    </div>
                    <!-- // Slider END -->


                </div>
            </div>
            <!-- // Widget END -->

            <!-- Widget -->
            <div class="widget widget-inverse">

                <!-- Widget heading -->
                <div class="widget-head">
                    <h4 class="heading glyphicons adjust_alt"><i></i>Range Slider Step</h4>
                </div>
                <!-- // Widget heading END -->

                <div class="widget-body">
                    <!-- Slider -->
                    <div class="sliderContainer">
                        <div id="rangeSliderStep"></div>
                    </div>
                    <!-- // Slider END -->


                </div>
            </div>
            <!-- // Widget END -->

            <div class="row">
                <div class="col-md-6">

                    <!-- Widget -->
                    <div class="widget widget-inverse">

                        <!-- Widget heading -->
                        <div class="widget-head">
                            <h4 class="heading glyphicons adjust_alt"><i></i>Range Slider Wheel Zoom</h4>
                        </div>
                        <!-- // Widget heading END -->

                        <div class="widget-body">
                            <!-- Slider -->
                            <div class="sliderContainer">
                                <div id="rangeSliderWheelZoom"></div>
                            </div>
                            <!-- // Slider END -->


                        </div>
                    </div>
                    <!-- // Widget END -->

                </div>
                <div class="col-md-6">

                    <!-- Widget -->
                    <div class="widget widget-inverse">

                        <!-- Widget heading -->
                        <div class="widget-head">
                            <h4 class="heading glyphicons adjust_alt"><i></i>Range Slider Wheel Scroll</h4>
                        </div>
                        <!-- // Widget heading END -->

                        <div class="widget-body">
                            <!-- Slider -->
                            <div class="sliderContainer">
                                <div id="rangeSliderWheelScroll"></div>
                            </div>
                            <!-- // Slider END -->


                        </div>
                    </div>
                </div>
            </div>

        </div>

        <h2 class="content-heading bg-white border-bottom border-top">JQueryUI Sliders</h2>
        <div class="innerAll spacing-x2">

            <!-- Simple slider -->
            <div class="widget widget-inverse">

                <!-- Widget heading -->
                <div class="widget-head">
                    <h4 class="heading">Simple Slider</h4>
                </div>
                <!-- // Widget heading END -->

                <div class="widget-body">
                    <!-- Slider -->
                    <div class="slider-single slider-primary"></div>
                </div>
            </div>
            <!-- // Simple slider END -->

            <!-- Range slider -->
            <div class="widget widget-inverse">

                <!-- Widget heading -->
                <div class="widget-head">
                    <h4 class="heading">Range Slider</h4>
                </div>
                <!-- // Widget heading END -->

                <div class="widget-body">
                    <!-- Slider -->
                    <div class="range-slider row">
                        <div class="col-md-3">
                            <input type="text" id="amount" class="amount form-control" />
                        </div>
                        <div class="col-md-9" style="padding-top: 9px;">
                            <div class="ui-slider-wrap">
                                <div class="slider slider-primary"></div>
                            </div>
                        </div>
                    </div>
                    <!-- // Slider END -->


                </div>
            </div>
            <!-- // Range slider END -->

            <!-- Range fixed minimum slider -->
            <div class="widget widget-inverse">

                <!-- Widget heading -->
                <div class="widget-head">
                    <h3 class="heading">Range Fixed Minimum Slider</h3>
                </div>
                <!-- // Widget heading END -->

                <div class="widget-body">
                    <!-- Slider -->
                    <div class="slider-range-min row form-horizontal">
                        <div class="col-md-3">
                            <div class="control-group">
                                <label class="col-md-8 control-label">Maximum price:</label>
                                <div class="col-md-4 padding-none">
                                    <input type="text" class="amount form-control" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-9" style="padding-top: 9px;">
                            <div class="slider slider-primary"></div>
                        </div>
                    </div>
                    <!-- // Slider END -->


                </div>
            </div>
            <!-- // Range fixed minimum slider END -->

            <!-- Range fixed maximum slider -->
            <div class="widget widget-inverse">

                <!-- Widget heading -->
                <div class="widget-head">
                    <h3 class="heading">Range Fixed Maximum Slider</h3>
                </div>
                <!-- // Widget heading END -->

                <div class="widget-body">
                    <!-- Slider -->
                    <div class="slider-range-max row form-horizontal">
                        <div class="col-md-3">
                            <div class="control-group">
                                <label class="col-md-8 control-label">Maximum price:</label>
                                <div class="col-md-4 padding-none">
                                    <input type="text" class="amount form-control" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-9" style="padding-top: 9px;">
                            <div class="slider slider-primary"></div>
                        </div>
                    </div>
                    <!-- // Slider END -->


                </div>
            </div>
            <!-- // Range fixed maximum slider -->

            <!-- Snap to increments slider -->
            <div class="widget widget-inverse">

                <!-- Widget heading -->
                <div class="widget-head">
                    <h3 class="heading">Snap to Increments Slider</h3>
                </div>
                <!-- // Widget heading END -->

                <div class="widget-body">
                    <!-- Slider -->
                    <div class="increments-slider row form-horizontal">
                        <div class="col-md-3">
                            <div class="control-group">
                                <label class="col-md-8 control-label">$50 increments:</label>
                                <div class="col-md-4 padding-none">
                                    <input type="text" class="amount form-control" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-9" style="padding-top: 9px;">
                            <div class="slider slider-primary"></div>
                        </div>
                    </div>
                    <!-- // Slider END -->


                </div>
            </div>
            <!-- // Snap to increments slider END -->

            <!-- Vertical sliders -->
            <div class="widget widget-inverse">

                <!-- Widget heading -->
                <div class="widget-head">
                    <h3 class="heading">Vertical Sliders</h3>
                </div>
                <!-- // Widget heading END -->

                <div class="widget-body">
                    <!-- Slider -->
                    <div class="sliders-vertical">
                        <span>77</span>
                        <span>55</span>
                        <span>33</span>
                        <span>40</span>
                        <span>45</span>
                        <div class="clearfix"></div>
                    </div>
                    <!-- // Slider END -->


                </div>
            </div>
            <!-- // Vertical sliders END -->

            <div class="separator bottom"></div>
            <!-- // Sliders END -->

        </div>
    </div>
    <!-- // Content END -->
        
    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->
</div>
<!-- // Tab END -->