<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
	<div id="content">
	    <div class="heading-buttons bg-white border-bottom innerAll">
	        <h1 class="content-heading padding-none float-left">How do I change the skin of Coral?</h1>
	        <div class="clearfix"></div>
	    </div>

	    <div class="innerAll spacing-x2">

	        <!-- row -->
	        <div class="row">


	            <div class="col-md-9 col-sm-8">
	                <div class="widget">
	                    <div class="innerT">
	                        <!-- Post List -->
	                        <div class="media innerLR border-bottom">

	                            <div class="float-left media-object" style="width:100px">
	                                <div class="text-center">
	                                    <a href="#" class="clearfix">
	                                        <img src="MelisDesign/images/people/50/1.jpg" class="rounded-none" />
	                                    </a>
	                                    <small class="text-small">Junior Member</small>

	                                    <div class="innerT half">

	                                        <a href="" class="text-muted"><i class="icon-user-1"></i></a>
	                                        <a href="" class="text-muted"><i class="icon-trophy-fill"></i></a>
	                                        <a href="" class="text-muted"><i class="icon-star-fill"></i></a>
	                                    </div>
	                                </div>
	                            </div>

	                            <div class="media-body">
	                                <small class="float-right label label-default">3 days ago</small>
	                                <h5><a href="" class="text-inverse">joanne</a> <span>wrote:</span></h5>
	                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam, animi, quis, perferendis unde atque eveniet itaque magnam id error eius rerum amet quibusdam nobis voluptatem vitae aut quos consequuntur impedit quo corporis. Est, atque, accusantium, voluptates, distinctio molestias culpa provident quos in consectetur quo optio voluptate tempora. Ex, veniam in.</p>
	                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas, accusamus!</p>

	                                <div class="innerB">
	                                    <small class="text-muted">
	                                wrote by <a href="">by John</a> | 
	                                posted in <a href="">Category</a> |
	                                <span class="text-success"><i class="fa fa-check"></i> Answered</span> 

	                            </small>
	                                </div>

	                            </div>
	                        </div>

	                        <div class="media innerLR border-bottom">

	                            <div class="float-left media-object" style="width:100px">
	                                <div class="text-center">
	                                    <a href="#" class="clearfix">
	                                        <img src="MelisDesign/images/people/50/2.jpg" class="rounded-none" />
	                                    </a>
	                                    <small class="text-small">Junior Member</small>

	                                    <div class="innerT half">

	                                        <a href="" class="text-muted"><i class="icon-user-1"></i></a>
	                                        <a href="" class="text-muted"><i class="icon-trophy-fill"></i></a>
	                                        <a href="" class="text-muted"><i class="icon-star-fill"></i></a>
	                                    </div>
	                                </div>
	                            </div>

	                            <div class="media-body">
	                                <small class="float-right label label-default">3 days ago</small>
	                                <h5><a href="" class="text-inverse">bill14</a> <span>wrote:</span></h5>
	                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam, animi, quis, perferendis unde atque eveniet itaque magnam id error eius rerum amet quibusdam nobis voluptatem vitae aut quos consequuntur impedit quo corporis. Est, atque, accusantium, voluptates, distinctio molestias culpa provident quos in consectetur quo optio voluptate tempora. Ex, veniam in.</p>
	                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas, accusamus!</p>

	                                <div class="innerB">
	                                    <small class="text-muted">
	                                wrote by <a href="">by John</a> | 
	                                posted in <a href="">Category</a> |
	                                <span class="text-success"><i class="fa fa-check"></i> Answered</span> 

	                            </small>
	                                </div>

	                            </div>
	                        </div>

	                        <div class="media innerLR border-bottom">

	                            <div class="float-left media-object" style="width:100px">
	                                <div class="text-center">
	                                    <a href="#" class="clearfix">
	                                        <img src="MelisDesign/images/people/50/3.jpg" class="rounded-none" />
	                                    </a>
	                                    <small class="text-small">Junior Member</small>

	                                    <div class="innerT half">

	                                        <a href="" class="text-muted"><i class="icon-user-1"></i></a>
	                                        <a href="" class="text-muted"><i class="icon-trophy-fill"></i></a>
	                                        <a href="" class="text-muted"><i class="icon-star-fill"></i></a>
	                                    </div>
	                                </div>
	                            </div>

	                            <div class="media-body">
	                                <small class="float-right label label-default">3 days ago</small>
	                                <h5><a href="" class="text-inverse">mary</a> <span>wrote:</span></h5>
	                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam, animi, quis, perferendis unde atque eveniet itaque magnam id error eius rerum amet quibusdam nobis voluptatem vitae aut quos consequuntur impedit quo corporis. Est, atque, accusantium, voluptates, distinctio molestias culpa provident quos in consectetur quo optio voluptate tempora. Ex, veniam in.</p>
	                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas, accusamus!</p>

	                                <div class="innerB">
	                                    <small class="text-muted">
	                                wrote by <a href="">by John</a> | 
	                                posted in <a href="">Category</a> |
	                                <span class="text-success"><i class="fa fa-check"></i> Answered</span> 

	                            </small>
	                                </div>

	                            </div>
	                        </div>

	                        <div class="media innerLR border-bottom">

	                            <div class="float-left media-object" style="width:100px">
	                                <div class="text-center">
	                                    <a href="#" class="clearfix">
	                                        <img src="MelisDesign/images/people/50/4.jpg" class="rounded-none" />
	                                    </a>
	                                    <small class="text-small">Junior Member</small>

	                                    <div class="innerT half">

	                                        <a href="" class="text-muted"><i class="icon-user-1"></i></a>
	                                        <a href="" class="text-muted"><i class="icon-trophy-fill"></i></a>
	                                        <a href="" class="text-muted"><i class="icon-star-fill"></i></a>
	                                    </div>
	                                </div>
	                            </div>

	                            <div class="media-body">
	                                <small class="float-right label label-default">3 days ago</small>
	                                <h5><a href="" class="text-inverse">mycompany</a> <span>wrote:</span></h5>
	                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam, animi, quis, perferendis unde atque eveniet itaque magnam id error eius rerum amet quibusdam nobis voluptatem vitae aut quos consequuntur impedit quo corporis. Est, atque, accusantium, voluptates, distinctio molestias culpa provident quos in consectetur quo optio voluptate tempora. Ex, veniam in.</p>
	                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas, accusamus!</p>

	                                <div class="innerB">
	                                    <small class="text-muted">
	                                wrote by <a href="">by John</a> | 
	                                posted in <a href="">Category</a> |
	                                <span class="text-success"><i class="fa fa-check"></i> Answered</span> 

	                            </small>
	                                </div>

	                            </div>
	                        </div>

	                        <!-- // END Category Listing -->
	                        <div class="innerAll text-right">
	                            <ul class="pagination margin-none">
	                                <li class="page-item disabled"><a class="page-link" href="#">&laquo;</a>
	                                </li>
	                                <li class="page-item active"><a class="page-link" href="#">1</a>
	                                </li>
	                                <li class="page-item"><a class="page-link" href="#">2</a>
	                                </li>
	                                <li class="page-item"><a class="page-link" href="#">3</a>
	                                </li>
	                                <li class="page-item"><a class="page-link" href="#">&raquo;</a>
	                                </li>
	                            </ul>

	                        </div>

	                    </div>

	                    <h4 class="innerLR innerT">Reply to Post</h4>
	                    <form class="text-right innerAll">
	                        <div class="innerB">
	                            <textarea name="" id="" cols="30" rows="3" class="form-control rounded-none margin-bottom" placeholder="Type here..."></textarea>
	                        </div>
	                        <a href="" class="btn btn-primary btn-sm strong">Submit <i class="fa fa-arrow-right"></i> </a>
	                    </form>



	                </div>
	            </div>
	            <div class="col-md-3 col-sm-4">
	                <div class="widget ">
	                    <div class="innerAll half border-bottom bg-gray">
	                        <div class="input-group">
	                            <input type="text" class="form-control" placeholder="Search posts ...">
	                            <span class="input-group-btn">
	                        <button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button>
	                    </span>
	                        </div>
	                    </div>
	                </div>
	                <div class="widget">
	                    <h4 class="innerAll half bg-primary margin-none">Latest Posts</h4>
	                    <div class="row-hover border-bottom innerAll half">

	                        <h5 class="margin-none"><a href="">Post title goes here</a></h5>
	                        <div class="clearfix"></div>
	                        <span class="text-small">1 hour ago</span> <a href="" class="text-small">by joanne</a>
	                    </div>
	                    <div class="row-hover border-bottom innerAll half">

	                        <h5 class="margin-none"><a href="">Post title goes here</a></h5>
	                        <div class="clearfix"></div>
	                        <span class="text-small">1 hour ago</span> <a href="" class="text-small">by bill14</a>
	                    </div>
	                    <div class="row-hover border-bottom innerAll half">

	                        <h5 class="margin-none"><a href="">Post title goes here</a></h5>
	                        <div class="clearfix"></div>
	                        <span class="text-small">1 hour ago</span> <a href="" class="text-small">by mary</a>
	                    </div>
	                    <div class="row-hover border-bottom innerAll half">

	                        <h5 class="margin-none"><a href="">Post title goes here</a></h5>
	                        <div class="clearfix"></div>
	                        <span class="text-small">1 hour ago</span> <a href="" class="text-small">by mycompany</a>
	                    </div>
	                    <div class="row-hover border-bottom innerAll half">

	                        <h5 class="margin-none"><a href="">Post title goes here</a></h5>
	                        <div class="clearfix"></div>
	                        <span class="text-small">1 hour ago</span> <a href="" class="text-small">by bogdan</a>
	                    </div>
	                    <div class="row-hover border-bottom innerAll half">

	                        <h5 class="margin-none"><a href="">Post title goes here</a></h5>
	                        <div class="clearfix"></div>
	                        <span class="text-small">1 hour ago</span> <a href="" class="text-small">by andrew</a>
	                    </div>
	                </div>
	            </div>
	        </div>


	    </div>
	</div>
	<!-- // Content END -->

    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->
</div>
<!-- // Tab END -->