<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    <div id="content">
        <h1 class="bg-white content-heading border-bottom">User Interface Elements</h1>
        <div class="innerAll bg-white border-bottom">
            <ul class="menubar">
                <li class="active"><a href="ui.html?lang=en">Buttons</a>
                </li>
                <li><a href="icons.html?lang=en">Icons</a>
                </li>
            </ul>
        </div>

        <div class="innerAll spacing-x2">

            <div class="widget widget-inverse">
                <div class="widget-head">
                    <div class="btn-group btn-group-xs pull-right">
                        <button class="btn btn-inverse"><i class="fa fa-fw fa-refresh"></i>
                        </button>
                        <button class="btn btn-inverse"><i class="fa fa-fw fa-times"></i>
                        </button>
                    </div>
                    <h4 class="heading"><i class="fa fa-fw fa-square"></i> Buttons Styles</h4>
                </div>
                <div class="widget-body text-center">
                    <div class="text-center separator bottom ui">

                        <div class="row">
                            <div class="col-md-6">

                                <div class="innerAll">
                                    <h5 class="strong">Stroke buttons</h5>
                                    <button class="btn btn-primary btn-stroke">Primary</button>
                                    <button class="btn btn-inverse btn-stroke">Inverse</button>
                                    <button class="btn btn-danger btn-stroke">Danger</button>
                                    <button class="btn btn-success btn-stroke">Success</button>
                                    <button class="btn btn-warning btn-stroke">
                                        Warning</button>
                                    <button class="btn btn-info btn-stroke">Info</button>
                                </div>

                                <div class="innerAll">
                                    <h5 class="strong">Circle Buttons</h5>
                                    <button class="btn btn-circle btn-default btn-regular"><i class="fa fa-home"></i>
                                    </button>
                                    <button class="btn btn-circle btn-primary"><i class="fa fa-lock"></i>
                                    </button>
                                    <button class="btn btn-circle btn-info btn-regular"><i class="fa fa-google-plus"></i>
                                    </button>
                                    <button class="btn btn-circle btn-inverse"><i class="fa fa-user"></i>
                                    </button>
                                    <button class="btn btn-circle btn-danger btn-regular"><i class="fa fa-trash-o"></i>
                                    </button>
                                    <button class="btn btn-circle btn-warning"><i class="fa fa-linkedin"></i>
                                    </button>
                                    <button class="btn btn-circle btn-success btn-regular"><i class="fa fa-twitter"></i>
                                    </button>
                                </div>

                                <div class="innerAll">
                                    <h5 class="strong">Circle Stroke</h5>
                                    <button class="btn btn-stroke btn-circle btn-primary"><i class="fa fa-lock"></i>
                                    </button>
                                    <button class="btn btn-stroke btn-circle btn-info"><i class="fa fa-google-plus"></i>
                                    </button>
                                    <button class="btn btn-stroke btn-circle btn-inverse"><i class="fa fa-user"></i>
                                    </button>
                                    <button class="btn btn-stroke btn-circle btn-danger"><i class="fa fa-trash-o"></i>
                                    </button>
                                    <button class="btn btn-stroke btn-circle btn-warning"><i class="fa fa-linkedin"></i>
                                    </button>
                                    <button class="btn btn-stroke btn-circle btn-success"><i class="fa fa-twitter"></i>
                                    </button>
                                </div>

                            </div>
                            <div class="col-md-6">

                                <div class="innerAll">
                                    <h5 class="strong">Regular buttons</h5>
                                    <button class="btn btn-default btn-regular">Default</button>
                                    <button class="btn btn-primary">Primary</button>
                                    <button class="btn btn-inverse">Inverse</button>
                                    <button class="btn btn-danger btn-regular">Danger</button>
                                    <button class="btn btn-success btn-regular">Success</button>
                                    <button class="btn btn-warning">Warning</button>
                                </div>

                                <div class="innerAll">
                                    <h5 class="strong">Buttons + Icons</h5>
                                    <button class="btn btn-default btn-regular"><i class="fa fa-home"></i> Default</button>
                                    <button class="btn btn-primary"><i class="fa fa-lock"></i> Primary</button>
                                    <button class="btn btn-inverse"><i class="fa fa-user"></i> Inverse</button>
                                    <button class="btn btn-danger btn-regular"><i class="fa fa-trash-o"></i> Danger</button>
                                    <button class="btn btn-success btn-regular"><i class="fa fa-twitter"></i> Success</button>
                                </div>

                            </div>
                        </div>
                        <div class="separator"></div>

                        <div class="innerAll">
                            <h5 class="strong">Buttons + Dropdowns</h5>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-regular dropdown-toggle" data-toggle="dropdown">
                                    Dropdown Default
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a>
                                    </li>
                                    <li><a href="#">Another action</a>
                                    </li>
                                    <li><a href="#">Something else here</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li><a href="#">Separated link</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="btn-group">
                                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                    Dropdown Primary
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="#">Action</a>
                                    </li>
                                    <li><a href="#">Another action</a>
                                    </li>
                                    <li><a href="#">Something else here</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li><a href="#">Separated link</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="btn-group">
                                <button type="button" class="btn btn-inverse dropdown-toggle" data-toggle="dropdown">
                                    Dropdown Inverse
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="#">Action</a>
                                    </li>
                                    <li><a href="#">Another action</a>
                                    </li>
                                    <li><a href="#">Something else here</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li><a href="#">Separated link</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="btn-group">
                                <button type="button" class="btn btn-danger btn-regular dropdown-toggle" data-toggle="dropdown">
                                    Dropdown Danger
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="#">Action</a>
                                    </li>
                                    <li><a href="#">Another action</a>
                                    </li>
                                    <li><a href="#">Something else here</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li><a href="#">Separated link</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="btn-group">
                                <button type="button" class="btn btn-success btn-regular dropdown-toggle" data-toggle="dropdown">
                                    Dropdown Success
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="#">Action</a>
                                    </li>
                                    <li><a href="#">Another action</a>
                                    </li>
                                    <li><a href="#">Something else here</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li><a href="#">Separated link</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="btn-group">
                                <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown">
                                    Dropdown Warning
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="#">Action</a>
                                    </li>
                                    <li><a href="#">Another action</a>
                                    </li>
                                    <li><a href="#">Something else here</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li><a href="#">Separated link</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="separator"></div>

                        <div class="innerAll">
                            <h5 class="strong">Double buttons</h5>
                            <button class="btn btn-default btn-icon-stacked btn-regular"><i class="fa fa-2x fa-facebook"></i> <span>Join using your<br/>Facebook Account</span>
                            </button>
                            <button class="btn btn-primary btn-icon-stacked"><i class="fa fa-2x fa-twitter"></i> <span>Join using your<br/>Twitter Account</span>
                            </button>
                            <button class="btn btn-inverse btn-icon-stacked"><i class="fa fa-2x fa-google-plus"></i> <span>Join using your<br/>Google Account</span>
                            </button>
                            <button class="btn btn-danger btn-icon-stacked btn-regular"><i class="fa fa-2x fa-facebook"></i> <span>Join using your<br/>Facebook Account</span>
                            </button>
                            <button class="btn btn-success btn-icon-stacked btn-regular"><i class="fa fa-2x fa-facebook"></i> <span>Join using your<br/>Facebook Account</span>
                            </button>
                            <button class="btn btn-warning btn-icon-stacked"><i class="fa fa-2x fa-facebook"></i> <span>Join using your<br/>Facebook Account</span>
                            </button>
                        </div>
                        <div class="separator"></div>

                        <div class="innerAll">
                            <h5 class="strong">Double Stroke</h5>
                            <button class="btn btn-stroke btn-primary btn-icon-stacked"><i class="fa fa-2x fa-twitter"></i> <span>Join using your<br/>Twitter Account</span>
                            </button>
                            <button class="btn btn-stroke btn-inverse btn-icon-stacked"><i class="fa fa-2x fa-google-plus"></i> <span>Join using your<br/>Google Account</span>
                            </button>
                            <button class="btn btn-stroke btn-danger btn-icon-stacked"><i class="fa fa-2x fa-facebook"></i> <span>Join using your<br/>Facebook Account</span>
                            </button>
                            <button class="btn btn-stroke btn-success btn-icon-stacked"><i class="fa fa-2x fa-facebook"></i> <span>Join using your<br/>Facebook Account</span>
                            </button>
                            <button class="btn btn-stroke btn-warning btn-icon-stacked"><i class="fa fa-2x fa-facebook"></i> <span>Join using your<br/>Facebook Account</span>
                            </button>
                        </div>
                        <div class="separator"></div>

                    </div>
                    <div class="separator bottom"></div>





                </div>
            </div>

            <div class="widget widget-inverse">
                <div class="widget-head">
                    <div class="btn-group btn-group-xs pull-right">
                        <button class="btn btn-inverse"><i class="fa fa-fw fa-refresh"></i>
                        </button>
                        <button class="btn btn-inverse"><i class="fa fa-fw fa-times"></i>
                        </button>
                    </div>
                    <h4 class="heading"><i class="fa fa-fw fa-exclamation"></i> Alerts</h4>
                </div>
                <div class="widget-body text-center">
                    <div class="row">
                        <div class="col-md-6">
                            <!-- Alert -->
                            <div class="alert alert-primary">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <strong>Warning!</strong> Best check yo self, you're not looking too good.
                            </div>
                            <!-- // Alert END -->


                            <!-- Alert -->
                            <div class="alert alert-warning">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <strong>Warning!</strong> Best check yo self, you're not looking too good.
                            </div>
                            <!-- // Alert END -->


                        </div>
                        <div class="col-md-6">
                            <!-- Alert -->
                            <div class="alert alert-success">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <strong>Warning!</strong> Best check yo self, you're not looking too good.
                            </div>
                            <!-- // Alert END -->


                            <!-- Alert -->
                            <div class="alert alert-danger">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <strong>Warning!</strong> Best check yo self, you're not looking too good.
                            </div>
                            <!-- // Alert END -->


                        </div>
                    </div>
                </div>
            </div>

            <div class="widget widget-inverse">
                <div class="widget-head">
                    <div class="btn-group btn-group-xs pull-right">
                        <button class="btn btn-inverse"><i class="fa fa-fw fa-refresh"></i>
                        </button>
                        <button class="btn btn-inverse"><i class="fa fa-fw fa-times"></i>
                        </button>
                    </div>
                    <h4 class="heading"><i class="fa fa-fw  fa-bookmark-o"></i> Ribbons</h4>
                </div>
                <div class="widget-body text-center">
                    <!-- Ribbons START -->
                    <!-- Row -->
                    <div class="row">

                        <!-- Column -->
                        <div class="col-md-8">

                            <h4>Default</h4>

                            <!-- Row -->
                            <div class="row">

                                <!-- Column -->
                                <div class="col-md-6">
                                    <div class="box-generic">
                                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.

                                        <!-- Ribbon -->
                                        <!-- Ribbon -->
                                        <div class="ribbon-wrapper">
                                            <div class="ribbon">50% Off</div>
                                        </div>


                                    </div>
                                </div>
                                <!-- // Column END -->

                                <!-- Column -->
                                <div class="col-md-6">
                                    <div class="box-generic">
                                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.

                                        <!-- Ribbon -->
                                        <!-- Ribbon -->
                                        <div class="ribbon-wrapper">
                                            <div class="ribbon primary">50% Off</div>
                                        </div>


                                    </div>
                                </div>
                                <!-- // Column END -->

                            </div>
                            <!-- // Row END -->
                            <div class="separator bottom"></div>

                            <!-- Row -->
                            <div class="row">

                                <!-- Column -->
                                <div class="col-md-6">
                                    <div class="box-generic">
                                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.

                                        <!-- Ribbon -->
                                        <!-- Ribbon -->
                                        <div class="ribbon-wrapper">
                                            <div class="ribbon warning">50% Off</div>
                                        </div>


                                    </div>
                                </div>
                                <!-- // Column END -->

                                <!-- Column -->
                                <div class="col-md-6">
                                    <div class="box-generic">
                                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.

                                        <!-- Ribbon -->
                                        <!-- Ribbon -->
                                        <div class="ribbon-wrapper">
                                            <div class="ribbon danger">50% Off</div>
                                        </div>


                                    </div>
                                </div>
                                <!-- // Column END -->

                            </div>
                            <!-- // Row END -->

                            <div class="separator bottom"></div>


                        </div>
                        <!-- // Column END -->

                        <!-- Column -->
                        <div class="col-md-4">
                            <h4>Smaller</h4>
                            <div class="box-generic">
                                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took ...

                                <!-- Ribbon -->
                                <!-- Ribbon -->
                                <div class="ribbon-wrapper small">
                                    <div class="ribbon success">50% Off</div>
                                </div>


                            </div>

                            <div class="box-generic">
                                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took ...

                                <!-- Ribbon -->
                                <!-- Ribbon -->
                                <div class="ribbon-wrapper small">
                                    <div class="ribbon warning">50% Off</div>
                                </div>


                            </div>

                        </div>
                        <!-- // Column END -->

                    </div>
                    <!-- // Row END -->
                    <!-- Ribbons END -->
                </div>
            </div>



            <div class="widget widget-inverse">
                <div class="widget-head">
                    <div class="btn-group btn-group-xs pull-right">
                        <button class="btn btn-inverse"><i class="fa fa-fw fa-refresh"></i>
                        </button>
                        <button class="btn btn-inverse"><i class="fa fa-fw fa-times"></i>
                        </button>
                    </div>
                    <h4 class="heading"><i class="fa fa-fw  fa-text-width"></i> Labels and Badges</h4>
                </div>
                <div class="widget-body">

                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Type</th>
                                <th>Badges</th>
                                <th>Labels</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Default</td>
                                <td>
                                    <span class="badge">1</span>
                                    <span class="badge badge-stroke">1</span>
                                </td>
                                <td>
                                    <span class="label label-default">Default</span>
                                    <span class="label label-default label-stroke">Default Stroke</span>
                                </td>
                            </tr>
                            <tr>
                                <td>Primary</td>
                                <td>
                                    <span class="badge badge-primary">1</span>
                                    <span class="badge badge-primary badge-stroke">1</span>
                                </td>
                                <td>
                                    <span class="label label-primary">Primary</span>
                                    <span class="label label-primary label-stroke">Primary Stroke</span>
                                </td>
                            </tr>
                            <tr>
                                <td>Success</td>
                                <td>
                                    <span class="badge badge-success">2</span>
                                    <span class="badge badge-success badge-stroke">2</span>
                                </td>
                                <td>
                                    <span class="label label-success">Success</span>
                                    <span class="label label-success label-stroke">Success Stroke</span>
                                </td>
                            </tr>
                            <tr>
                                <td>Warning</td>
                                <td>
                                    <span class="badge badge-warning">4</span>
                                    <span class="badge badge-warning badge-stroke">4</span>
                                </td>
                                <td>
                                    <span class="label label-warning">Warning</span>
                                    <span class="label label-warning label-stroke">Warning Stroke</span>
                                </td>
                            </tr>
                            <tr>
                                <td>Danger</td>
                                <td>
                                    <span class="badge badge-danger">6</span>
                                    <span class="badge badge-danger badge-stroke">6</span>
                                </td>
                                <td>
                                    <span class="label label-danger">Danger</span>
                                    <span class="label label-danger label-stroke">Danger Stroke</span>
                                </td>
                            </tr>
                            <tr>
                                <td>Info</td>
                                <td>
                                    <span class="badge badge-info">8</span>
                                    <span class="badge badge-info badge-stroke">8</span>
                                </td>
                                <td>
                                    <span class="label label-info">Info</span>
                                    <span class="label label-info label-stroke">Info Stroke</span>
                                </td>
                            </tr>
                            <tr>
                                <td>Inverse</td>
                                <td>
                                    <span class="badge badge-inverse">10</span>
                                    <span class="badge badge-inverse badge-stroke">10</span>
                                </td>
                                <td>
                                    <span class="label label-inverse">Inverse</span>
                                    <span class="label label-inverse label-stroke">Inverse Stroke</span>
                                </td>
                            </tr>
                        </tbody>
                    </table>


                </div>

            </div>
            <div class="widget widget-inverse">
                <div class="widget-head">
                    <div class="btn-group btn-group-xs pull-right">
                        <button class="btn btn-inverse"><i class="fa fa-fw fa-refresh"></i>
                        </button>
                        <button class="btn btn-inverse"><i class="fa fa-fw fa-times"></i>
                        </button>
                    </div>
                    <h4 class="heading"><i class="fa fa-fw  fa-text-width"></i> Pagination </h4>
                </div>
                <div class="widget-body">

                    <div class="row">
                        <div class="col-md-3">
                            <h5 class="strong">Pagination</h5>
                            <ul class="pagination margin-none">
                                <li class="disabled"><a href="#">&laquo;</a>
                                </li>
                                <li class="active"><a href="#">1</a>
                                </li>
                                <li><a href="#">2</a>
                                </li>
                                <li><a href="#">3</a>
                                </li>
                                <li><a href="#">&raquo;</a>
                                </li>
                            </ul>

                        </div>
                        <div class="col-md-6">
                            <p class="jquery-bootpag-content">Dynamic content here.</p>
                            <p class="jquery-bootpag-pagination"></p>


                        </div>
                        <div class="col-md-3">
                            <h5 class="strong">Pager</h5>
                            <ul class="pager margin-none">
                                <li class="previous disabled"><a href="#">&larr; Older</a>
                                </li>
                                <li class="next"><a href="#">Newer &rarr;</a>
                                </li>
                            </ul>


                        </div>
                    </div>
                </div>

            </div>

            <!-- Progress bars -->
            <div class="widget widget-inverse">
                <div class="widget-head">
                    <h4 class="heading glyphicons show_thumbnails"><i></i>Progress bars</h4>
                </div>
                <div class="widget-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="shortRight">Styles</th>
                                <th>Preview</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="shortRight">Default</td>
                                <td>
                                    <div class="progress">
                                        <div class="progress-bar progress-bar-default" style="width: 20%;"></div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="shortRight">Primary</td>
                                <td>
                                    <div class="progress">
                                        <div class="progress-bar progress-bar-primary" style="width: 30%;"></div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="shortRight">Success</td>
                                <td>
                                    <div class="progress">
                                        <div class="progress-bar progress-bar-success" style="width: 60%;"></div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="shortRight">Warning</td>
                                <td>
                                    <div class="progress">
                                        <div class="progress-bar progress-bar-warning" style="width: 55%;"></div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="shortRight">Danger</td>
                                <td>
                                    <div class="progress">
                                        <div class="progress-bar progress-bar-danger" style="width: 80%;"></div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="shortRight">Inverse</td>
                                <td>
                                    <div class="progress">
                                        <div class="progress-bar progress-bar-inverse" style="width: 30%;"></div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="shortRight">Mini</td>
                                <td>
                                    <div class="progress progress-mini">
                                        <div class="progress-bar" style="width: 40%;"></div>
                                    </div>
                                    <div class="progress progress-mini">
                                        <div class="progress-bar progress-bar-danger" style="width: 55%;"></div>
                                    </div>
                                    <div class="progress progress-mini">
                                        <div class="progress-bar progress-bar-success" style="width: 80%;"></div>
                                    </div>
                                    <div class="progress progress-mini">
                                        <div class="progress-bar progress-bar-warning" style="width: 60%;"></div>
                                    </div>
                                    <div class="progress progress-mini">
                                        <div class="progress-bar progress-bar-primary" style="width: 75%;"></div>
                                    </div>
                                    <div class="progress progress-mini">
                                        <div class="progress-bar progress-bar-inverse" style="width: 50%;"></div>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- // Progress bars END -->



            <!-- Tooltips -->
            <div class="widget widget-inverse">

                <!-- Widget Heading -->
                <div class="widget-head">
                    <h3 class="heading glyphicons show_thumbnails"><i></i>Tooltips</h3>
                </div>
                <!-- // Widget Heading END -->

                <div class="widget-body">

                    <!-- Row -->
                    <div class="row">

                        <!-- Column -->
                        <div class="col-md-6">
                            <p class="muted">Tight pants next level keffiyeh <a href="#" data-toggle="tooltip" title="" data-original-title="Default tooltip">you probably</a> haven't heard of them. Photo booth beard raw denim letterpress vegan messenger bag stumptown. Farm-to-table seitan, mcsweeney's fixie sustainable quinoa 8-bit american apparel <a href="#" data-toggle="tooltip" title="" data-original-title="Another tooltip">have a</a> terry richardson vinyl chambray. Beard stumptown, cardigans banh mi lomo thundercats. Tofu biodiesel williamsburg marfa, four loko mcsweeney's cleanse vegan chambray. A really ironic artisan <a href="#" data-toggle="tooltip" title="" data-original-title="A much longer tooltip belongs right here to demonstrate the max-width we apply.">whatever keytar</a>, scenester farm-to-table banksy Austin <a href="#" data-toggle="tooltip" title="" data-original-title="The last tip!">twitter handle</a> freegan cred raw denim single-origin coffee viral.</p>
                        </div>
                        <!-- // Column END -->

                        <!-- Column -->
                        <div class="col-md-6">
                            <div class="innerAll">

                                <!-- Live DEMO Tooltip Options Table -->
                                <table class="table table-bordered table-vertical-center">
                                    <tbody>
                                        <tr>
                                            <td class="center"><span class="btn btn-primary" data-toggle="tooltip" data-original-title="Tooltip on Left" data-placement="left">Tooltip on Left</span>
                                            </td>
                                            <td class="center"><span class="btn btn-primary" data-toggle="tooltip" data-original-title="Tooltip on Top" data-placement="top">Tooltip on Top</span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="center"><span class="btn btn-primary" data-toggle="tooltip" data-original-title="Tooltip on Right" data-placement="right">Tooltip on Right</span>
                                            </td>
                                            <td class="center"><span class="btn btn-primary" data-toggle="tooltip" data-original-title="Tooltip on Bottom" data-placement="bottom">Tooltip on Bottom</span>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <!-- // Live DEMO Tooltip Options Table END -->

                            </div>
                        </div>
                        <!-- // Column END -->

                    </div>
                    <!-- // Row END -->
                </div>
            </div>
            <!-- // Tooltips END -->



            <!-- Popovers -->
            <div class="widget widget-inverse">

                <!-- Widget Heading -->
                <div class="widget-head">
                    <h3 class="heading glyphicons show_thumbnails"><i></i>Popovers</h3>
                </div>
                <!-- // Widget Heading END -->

                <div class="widget-body">

                    <!-- Row -->
                    <div class="row">

                        <!-- Column -->
                        <div class="col-md-7" id="demo_popovers">

                            <!-- Row -->
                            <div class="row">

                                <!-- Column -->
                                <div class="col-md-6">
                                    <div class="inner">

                                        <!-- Popover Top -->
                                        <div class="popover top">
                                            <div class="arrow"></div>
                                            <h3 class="popover-title">Popover top</h3>
                                            <div class="popover-content">
                                                <p>Sed posuere consectetur est at lobortis. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.</p>
                                            </div>
                                        </div>
                                        <!-- // Popover Top END -->

                                    </div>
                                </div>
                                <!-- // Column END -->

                                <!-- Column -->
                                <div class="col-md-6">
                                    <div class="innerLR">

                                        <!-- Popover Right -->
                                        <div class="popover right">
                                            <div class="arrow"></div>
                                            <h3 class="popover-title">Popover right</h3>
                                            <div class="popover-content">
                                                <p>Sed posuere consectetur est at lobortis. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.</p>
                                            </div>
                                        </div>
                                        <!-- // Popover Right END -->

                                    </div>
                                </div>
                                <!-- // Column END -->

                            </div>
                            <!-- // Row END -->

                            <!-- Row -->
                            <div class="row">

                                <!-- Column -->
                                <div class="col-md-6">
                                    <div class="innerT">

                                        <!-- Popover Bottom -->
                                        <div class="popover bottom">
                                            <div class="arrow"></div>
                                            <h3 class="popover-title">Popover bottom</h3>
                                            <div class="popover-content">
                                                <p>Sed posuere consectetur est at lobortis. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.</p>
                                            </div>
                                        </div>
                                        <!-- // Popover Bottom END -->

                                    </div>
                                </div>
                                <!-- // Column END -->

                                <!-- Column -->
                                <div class="col-md-6">
                                    <div class="innerAll">

                                        <!-- Popover Left -->
                                        <div class="popover left">
                                            <div class="arrow"></div>
                                            <h3 class="popover-title">Popover left</h3>
                                            <div class="popover-content">
                                                <p>Sed posuere consectetur est at lobortis. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.</p>
                                            </div>
                                        </div>
                                        <!-- // Popover Left END -->

                                    </div>
                                </div>
                                <!-- // Column END -->

                            </div>
                            <!-- // Row END -->

                        </div>
                        <!-- // Column END -->

                        <!-- Column -->
                        <div class="col-md-5">
                            <div class="inner">

                                <!-- Live DEMO Popover Options Table -->
                                <table class="table table-bordered table-vertical-center">
                                    <tbody>
                                        <tr>
                                            <td class="center"><span class="btn btn-inverse" data-toggle="popover" data-title="Popover on Left" data-content="Sed posuere consectetur est at lobortis. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum." data-placement="left">Popover on Left</span>
                                            </td>
                                            <td class="center"><span class="btn btn-inverse" data-toggle="popover" data-title="Popover on Top" data-content="Sed posuere consectetur est at lobortis. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum." data-placement="top">Popover on Top</span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="center"><span class="btn btn-inverse" data-toggle="popover" data-title="Popover on Right" data-content="Sed posuere consectetur est at lobortis. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum." data-placement="right">Popover on Right</span>
                                            </td>
                                            <td class="center"><span class="btn btn-inverse" data-toggle="popover" data-title="Popover on Bottom" data-content="Sed posuere consectetur est at lobortis. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum." data-placement="bottom">Popover on Bottom</span>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <div class="separator bottom"></div>
                                <!-- // Live DEMO Popover Options Table END -->
                            </div>
                        </div>
                        <!-- // Column END -->

                    </div>
                    <!-- // Row END -->

                </div>
            </div>
            <!-- // Popovers END -->



        </div>




    </div>
    <!-- // Content END -->

    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->

