<?php

    $name = '';
    $id = '';
    if (!empty($this->zoneconfig['conf']['name']))
        $name = $this->zoneconfig['conf']['name'];
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;
        
?>
<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a page-elements">
    <div id="content">
        <h1 class="content-heading bg-white border-bottom">Medical memos</h1>
        <div class="bg-white innerAll border-bottom">
            <ul class="menubar">
                <li><a href="index.html?lang=en">Dashboard</a>
                </li>
                <li><a href="#"><span class="badge badge-primary pull-right">30</span> Button</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Dropdown Link #1</a>
                        </li>
                        <li><a href="#">Dropdown Link #2</a>
                        </li>
                        <li><a href="#">Dropdown Link #3</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="innerAll spacing-x2">

            <!-- row-app -->
            <div class="row row-app">

                <!-- col -->
                <div class="col-md-4">

                    <h4 class="box-generic innerAll half"><i class="fa fa-fw fa-bar-chart-o text-primary pull-right"></i> Metrics</h4>

                    <div class="box-generic padding-none border-bottom-none">
                        <div id="metrics"></div>
                    </div>

                    <div class="box-generic">
                        <div class="innerAll text-center">
                            <p class="lead margin-none">
                                <span class="text-large text-regular">540,120</span>
                            </p>
                            <p class="lead">
                                <span class="text-primary">transactions</span> this month</p>
                            <div class="progress progress-mini">
                                <div class="progress-bar progress-bar-primary" style="width: 30%"></div>
                            </div>
                            <p class="margin-none">November, 2013</p>
                        </div>
                    </div>

                </div>
                <!-- // END col -->

                <!-- col -->
                <div class="col-md-8">

                    <div class="box-generic padding-none">
                        <div class="heading-buttons innerAll half border-bottom">
                            <div class="btn-group pull-right btn-group-sm" data-toggle="charts-metrics-changedata">
                                <button class="btn btn-primary">Oct</button>
                                <button class="btn btn-primary active">Nov</button>
                                <button class="btn btn-primary">Dec</button>
                            </div>
                            <h4 class="margin-none"><i class="fa fa-fw fa-shield text-primary"></i> Transactions</h4>
                        </div>

                        <div class="innerAll">
                            <div id="chart_metrics"></div>
                        </div>
                    </div>

                </div>
                <!-- // END col -->

            </div>
            <!-- // END row-app -->

        </div>


    </div>
    <!-- // Content END -->
        
<div class="clearfix"></div>
<!-- // Sidebar menu & content wrapper END -->

</div>
<!-- // Tab END -->